### ISSUE TITLE
Broken link to Composing Data tutorial in Nesting Layouts warning

### ISSUE THREAD

**Issue by jordansamuels** [ioam/holoviews#1595] opened 2017-06-21 19:13 UTC
This warning appears when nesting layouts:
```
WARNING:root:Warning: Nesting Layouts within a HoloMap makes it difficult to access your data or control how it appears; we recommend calling .collate() on the HoloMap in order to follow the recommended nesting structure shown in the Composing Data tutorial(http://git.io/vtIQh)
```
however, http://git.io/vtIQh points to http://ioam.github.io/holoviews/Tutorials/Composing_Data.html, not the new link at http://holoviews.org/Tutorials/Composing_Data.html .

Repro code:
```
curve = hv.Curve(([0,1],[0,1]))
points = hv.Points(np.random.rand(100,2))
hv.HoloMap([(0, curve*points + points)])
```

http://ioam.github.io/holoviews/Tutorials/Composing_Data.html

**Comment by jordansamuels** [comment] 2017-06-21 19:14
I can try to submit a PR, but I wasn't sure how to fix because we can't use http://git.io to shorten http://holoviews.org/Tutorials/Composing_Data.html since it's not a GitHub.com URL.  Can we use http://bit.ly or another shortener?

**Comment by jlstevens** [comment] 2017-06-21 19:37
Thanks for reporting this though I do think this is a duplicate of #1455. All those links will need to have entirely new URLs soon for the new website we are working on.

I've assigned myself this issue and don't worry about submitting a PR as I'll be fixing it soon!

**Comment by jordansamuels** [comment] 2017-06-21 23:30
Doh! I should have searched for a duplicate first.  Thanks.

**Closed** 2017-06-21 23:37 UTC
Labels: duplicate
