### ISSUE TITLE
Image and key_dimensions

### ISSUE THREAD

**Issue by vascotenner** [ioam/holoviews#42] opened 2015-04-28 14:36 UTC
https://ioam.github.io/holoviews/Tutorials/Introduction:
> **Dimensions of your data**. The key_dimensions describe how your data can be indexed. The value_dimensions describe what the resulting indexed data represents. A numerical Dimension can have a name, type, range, and unit. This information allows HoloViews to rescale and label axes and allows HoloViews be smart in how it processes your data.

The syntax to get the right ranges in an image is different however:
* **Does not work:** 
```python
data = np.mgrid[:100,:100][0]+2*np.mgrid[:100,:100][1]
img = hv.Image(data, key_dimensions=[
               hv.Dimension('xa', range=(0,100)),
               hv.Dimension('ya', range=(0,100))
           ])
```
* **Works**: 
```python
data = np.mgrid[:100,:100][0]+2*np.mgrid[:100,:100][1]
hv.Image(data, bounds=(0,0,100,100))
```
The first one is what I would expect from Holoviews, but the implemented one is shorter, and closer the the matplotlib.imshow implementation. I opt that both work, aka, that bounds is a shortcut for defining the ranges via the dimension function.

**Comment by jlstevens** [comment] 2015-05-04 17:33
Yes, I think you have a good point and I don't see why it should work this way. Right now, if you don't supply bounds, you get the default (i.e unit) bounding box. This means that if a range is set on those dimensions, we should use those values to update the default bounds.

Of course, if you specify inconsistent dimension ranges as well as bounds, we'll have to complain! Other than that, I think it makes sense although I don't am not sure that setting the bounds should set the dimension ranges. I'll have to think about that.  

Philipp?

**Comment by philippjfr** [comment] 2015-05-04 17:37
Right, I also agree that this is the correct behavior. Image should instantiate the bounds either through an explicitly supplied bounds tuple OR via the supplied Dimension.range for the two key_dimensions, if both are supplied and are inconsistent we should complain. The Dimension.range should however not be set by us, since we have generally avoided mutating Dimension objects internally.

**Comment by jlstevens** [comment] 2015-05-04 22:29
Ok. After much discussion we reminded ourselves why it is actually correct the way it is. :-)

Here is an example that illustrates how bounds and the key_dimensions are actually different concepts:

```python
%%opts Image [situate_axes=True]
data = np.mgrid[:100,:100][0]+2*np.mgrid[:100,:100][1]
hv.Image(data, bounds=(0,0,100,100), 
         key_dimensions=[Dimension('x', range=(-200,200)), 
                                     Dimension('y', range=(-200,200))])
```

The key point is that the bounds is *about* the particular array you supply: it is the space covered by the samples in that array. The ``key_dimensions`` on the other hand have a  less strict semantics regarding where the data 'lives': the above code presents a figure in the  overall space ``[-200,200]`` which the actual array data living in a portion of that space ``[0,100]``.

Note that this is consistent with our Chart elements. For instance compare these two things:

```python
Curve(zip(range(10), range(10)))
```

Versus:

```python
 Curve(zip(range(10), range(10)), key_dimensions=[Dimension('x', range=(-5,15))])
```

The key difference is that ``Curve`` doesn't need a bounds argument (the positions are explicit in the coordinates supplied) whereas when you have an array living in a continuous space, the spatial information is *not* in the data itself which is why it must be supplied with a separate bounds argument.

The issue is rather subtle and can be quite confusing (which is why we had to spend a while dicussing it) but there is a real (and important) distinction to make. What do think there are a couple of things we could do to help avoid such confusion in future:

1. Make ``situate_axes=True`` by default for ``Image`` and its sub-classes. Setting ``situate_axes=False`` is important when you have a ``Layout`` of multiple Images (for instance) and you don't want the spatial scales to be normalized (which makes the spatial extents comparable but which can be a big problem if the spatial extents are very different).
2. Add an example like this one to the Elements notebook so there is a clear example of the distinction.

This has forced us to carefully revisit the semantics of dimension ranges and it has helped clarify the situation in our heads. Hopefully this is all now clearer for you too!

**Comment by basnijholt** [comment] 2015-05-07 13:45
In the example you gave the bounds you supply in ```bounds``` are exclusive. Take a look at 
```
hv.Image(data, bounds=(0,0,100,100), 
         key_dimensions=[Dimension('x', range=(-200,200)), 
                         Dimension('y', range=(-200,200))]).table()
```

I'm having this issue for my own data as well, how can I make the bounds inclusive?

**Comment by jlstevens** [comment] 2015-05-07 17:00
I had a look at your example table and firstly it reveals a bug in our sampling code! The ranges set on the dimensions shouldn't change the values in the table as the data positions is defined by the array shape and bounds only.

Omitting the ranges, the example I am using is this:

```python
import holoviews as hv
import numpy as np
data = np.ones((3,3))
hv.Image(data, bounds=(0,0,100,100), 
         key_dimensions=[hv.Dimension('x'),  hv.Dimension('y')]).table()
```

I assume you were expecting to see points with *x,y* coordinates of (0,0) and (100,100)?

If so, this comes down to how we are the array samples with their position in the continuous, spatial coordinate system. The bounds don't go through the sample centers but around the corresponding spatial bins i.e imagine your pixels as areas instead of point samples.

This is shown in this [illustration](http://ioam.github.io/topographica/_images/matrix_coords.png) and explained in the [Continuous Coordinates Tutorial](http://ioam.github.io/holoviews/Tutorials/Continuous_Coordinates.html).  Without knowing more about how your data is defined, it is hard to tell whether there is a strong case in favor of having bounds pass through the pixel centers.

Alternatively, maybe you are better off working in matrix coordinates in which case the ``Raster`` element is more appropriate (and doesn't require bounds):

```python
import holoviews as hv
import numpy as np
data = np.ones((3,3))
hv.Raster(data,  key_dimensions=[hv.Dimension('x'),  hv.Dimension('y')]).table()
```

Thank you for reporting this as it has helped us discover a couple of issues with how we are sampling our raster elements into tables!

**Comment by basnijholt** [comment] 2015-05-07 17:47
Thank you for your explanation. 

I actually know the ```X``` and ```Y``` values exactly and would like to use in a way similar to the way I do this with matplotlib: ```ax.pcolor(X, Y, data)```.

How could I do this in the easiest/best way?

**Comment by philippjfr** [comment] 2015-05-07 18:02
Quick question before I can give a sensible answer to that question. Are your X and Y values evenly sampled or do you need pixels with varying sizes?

**Comment by basnijholt** [comment] 2015-05-07 18:03
It's evenly sampled.

**Comment by philippjfr** [comment] 2015-05-07 18:09
The simplest thing to do is probably just to use a HeatMap Element in that case. The data structure of a HeatMap is a dictionary of the form {(x, y): value}, you'll also probably want to turn off the show_values plot options, e.g.:

%%opts HeatMap [show_values=False]
hv.HeatMap({(0, 1): 0.5, (1, 0): 1.5})

If this is too slow or doesn't quite do what you want we'll have to consider implementing a new Element type, which would hold the data in a format compatible with the ax.pcolor signature.

**Comment by basnijholt** [comment] 2015-05-07 18:16
Thanks a lot! I'm pretty determined in adopting HoloViews and will present some nice features here on my university sometime soon.

Something similar to ax.pcolor would be really useful though, but will try this for now :)

**Comment by basnijholt** [comment] 2015-05-07 18:36
**Update:**

Unfortunately hv.HeatMap is not an realistic option, it takes > 3 minutes to make one plot, and I will need ~100 in the HoloMap.

The dictionary that I create has 15000 entries, and I wouldn't consider this a big data set.

**Comment by jlstevens** [comment] 2015-05-07 18:48
Implementing a new raster element type is something we are certainly happy to do if there is a clear need. That said, in this case, that maybe that may unnecessary: maybe a ``Raster`` with specified extents will work for your visualization purposes?

```python
data = np.random.rand(50,50)
hv.Raster(data, extents = (0,0,100,100))
``

Then we would just need to take extents into account when sampling a Raster into a table (which is currently still using matrix coordinates).

**Comment by philippjfr** [comment] 2015-05-07 18:48
Agreed, HeatMap isn't meant to handle large amounts of data, it's really meant for (very) small parameter spaces that you want to visualize quickly. Sounds like we'll need a Histogram2D object, which holds xedges, yedges and the luminance matrix and a corresponding Histogram2D plot, which uses plt.pcolor internally.

**Comment by philippjfr** [comment] 2015-05-07 18:56
@jlstevens suggestion is probably the easier solution at least for now. Only uneven sampling should require my proposed Histogram2D Element.

**Comment by jlstevens** [comment] 2015-05-07 18:59
I am not sure I like the name ``Histogram2D`` but the basic idea is sound. Note that a very natural way to view a ``Histogram2D`` would be as a 3D plot where the bin values map to the z-axis! 

Although I realize the '2D' does refers to the number key dimensions, I still think there is a lot of potential for such a name to be confusing...

**Comment by basnijholt** [comment] 2015-05-07 19:06
```Raster``` does the trick but now I'm missing the ```style(origin='lower')``` option.

```ax.pcolor``` would solve all issues (for me at least), as it also has a more natural orientation when working with 3D data.

**Comment by philippjfr** [comment] 2015-05-07 19:16
Only reason why I suggested it is because it matches np.histogram2d.

**Comment by philippjfr** [comment] 2015-05-07 19:46
You can use either:

```python
%%opts Raster [invert_yaxis=True] 
hv.Raster(np.random.rand(25, 25))
```

Or

```python
%%opts Raster (origin=' lower') 
hv.Raster(np.random.rand(25, 25))
```

**Comment by basnijholt** [comment] 2015-05-09 13:15
```
%%opts Raster (origin='upper')
hv.Image(test)
```
and 
```
%%opts Raster (origin='lower')
hv.Image(test)
```

produce the same Raster, same goes for ``[invert_yaxis=False]`` and ``[invert_yaxis=True]``.

**Comment by philippjfr** [comment] 2015-05-09 17:50
Posted that from my mobile without testing it sorry. Not entirely sure why it ignores the origin but I just pushed a fix for RasterPlot so invert_yaxis=True should now work for Raster.

**Comment by philippjfr** [comment] 2015-05-18 19:07
I think we addressed the problems brought up in this issue:

* Sorted out the semantics of Dimension ranges vs. bounds on Image
* Fixed sampling of Image and Raster types
* Addressed invert_yaxis issues for Raster

I'll close this now. Please file new issues if you find anything mentioned here doesn't in fact work for you.

**Closed by philippjfr** 2015-05-18 19:07 UTC
