### ISSUE TITLE
Make BarPlot implementations more general/robust

### ISSUE THREAD

**Issue by courcelm** [ioam/holoviews#1047] opened 2017-01-10 19:29 UTC
Is there any way to make horizontal bar plot?

**Comment by philippjfr** [comment] 2017-01-16 13:29
Not easy way currently, I'd very much like to rewrite both the matplotlib and the bokeh bar plot implementations because they are either not very flexible or very general. I'll repurpose this issue for that purpose. I'll quickly list the issues:

* Bokeh implementation:
  - Based on bokeh charts, therefore not very flexible
  - Unclear if updating the chart works in latest versions of bokeh/holoviews
  - Does not allow horizontal bars
* Matplotlib implementation:
  - Needlessly complex implementation
  - Hard to maintain or refactor
  - Not that general, e.g. horizontal bars not supported

**Comment by courcelm** [comment] 2017-01-16 14:07
Thank for your reply. I will stick to Matplotlib or Seaborn horizontal barplot for the moment.

**Comment by philippjfr** [comment] 2018-11-26 18:16
Duplicate of #1407

**Closed by philippjfr** 2018-11-26 18:16 UTC
Labels: feature, plotting
