### ISSUE TITLE
Only raster GridSpaces support titles

### ISSUE THREAD

**Issue by jlstevens** [ioam/holoviews#88] opened 2015-05-19 08:38 UTC
This is a limitation that we are aware of and is a consequence of the general approach used in ``GridPlot`` (the general plot class) and the optimized ``RasterGridPlot`` (faster but only for ``imshow``).

As getting this to work would require a major rewrite of ``GridPlot``, this probably won't be fixed anytime soon. It is worth filing this issue to remind ourself of this limitation if ever the time comes to refactor/reimplement ``GridPlot``.

@philippjfr Out of curiosity, I am wondering if you get round this limitation by using a ``Layout`` title for a single ``GridSpace`` in a ``Layout``? I believe Layouts only show titles when they have more than one element but this restriction could possibly be lifted for ``GridSpace`` objects. Just a thought.

**Comment by philippjfr** [comment] 2015-05-19 11:28
The suptitle, which is what's used for Layouts, is very fragile in its positioning and can't be adjusted relative to an axis. So no I don't think it's a good idea to use it for GridSpaces. Don't have a reasonable solution for this and the related missing sublabels in #37 at the moment.

**Comment by philippjfr** [comment] 2016-02-04 02:09
This is a duplicate of #37. Closing.

**Closed by philippjfr** 2016-02-04 02:09 UTC
Labels: feature
