### ISSUE TITLE
IOPub data rate exceeded

### ISSUE THREAD

**Issue by jbednar** [ioam/holoviews#1181] opened 2017-03-08 19:41 UTC
With the 5.0.0b1 version of the Jupyter notebook server, I'm getting error messages instead of some of my HoloViews plots:

![image](https://cloud.githubusercontent.com/assets/1695496/23720499/6eaaaf0a-0404-11e7-821c-2c5073913cb9.png)

If this is a new thing, should HoloViews be increasing the limit to something more in line with the amount of data that HoloViews notebooks typically generate?

```
You are using Jupyter notebook.

The version of the notebook server is 5.0.0b1 and is running on:
Python 2.7.13 |Anaconda 2.5.0 (x86_64)| (default, Dec 20 2016, 23:05:08) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)]

Python 2.7.13 |Anaconda 2.5.0 (x86_64)| (default, Dec 20 2016, 23:05:08) 
Type "copyright", "credits" or "license" for more information.

IPython 5.3.0 -- An enhanced Interactive Python.
```

**Comment by jbednar** [comment] 2017-03-08 19:48
For the Showcase notebook, I was able to get the output to appear in place of those error messages if I launched the server with:

```
jupyter notebook --NotebookApp.iopub_data_rate_limit=10000000  Showcase.ipynb 
```

Not sure what units that value is in; 10 million somethings...

**Comment by philippjfr** [comment] 2017-03-08 22:14
Here's what their docs say:
```python
NotebookApp.iopub_data_rate_limit : Float
Default: 1000000

(bytes/sec) Maximum rate at which messages can be sent on iopub before they are limited.
```

Surely there must be a way to override this for certain output, this was just meant to prevent a lot of text being dumped into your browser at once, which is a problem. I'll do some digging.

**Comment by philippjfr** [comment] 2017-03-13 17:02
As far as I can tell there is no way to override this expect setting a higher rate in your Jupyter config, which would be a real pain.

**Comment by jbednar** [comment] 2017-03-14 03:20
Should we file an issue with Jupyter?

**Comment by philippjfr** [comment] 2017-03-15 19:14
Looks like this will be fixed in Jupyter 5.1, which means we'll have to pin 4.2.2 in our requirements or provide guidance to increase the limit.

**Comment by philippjfr** [comment] 2017-04-05 01:15
I can confirm that using 5.0 a bunch of examples in ``Showcase`` and ``Exploring Data`` now raise this error. What should we do until 5.1 is out?

**Comment by jbednar** [comment] 2017-04-05 04:24
Is there a dev release we can rely on?

**Comment by philippjfr** [comment] 2017-04-05 13:14
The actual fix has not even been merged yet (see https://github.com/jupyter/notebook/pull/2368), so no dev release we can use. Suppose pinning 4.2.2 is our only option but then that's bound to annoy people if we downgrade their Jupyter on install.

**Comment by jbednar** [comment] 2017-04-05 13:21
Yep, it's very annoying.  I would argue that the Jupyter 5.0 release is broken with its default values for the data rate, for visualization purposes, so I don't see any other option.

**Comment by jlstevens** [comment] 2017-04-05 14:52
> ... if they are doing viz in a notebook, downgrading to 4.2.2 is actually doing them a favor.

I agree! Just need to make it clear somehow that *we're* not the ones causing problems and that *Jupyter 5.0* is what is causing some general problems for a lot of notebook users.

**Comment by jlstevens** [comment] 2017-04-05 14:53
This may deserve a section in the release notes, not only to explain why we are pinning but what people who've upgrades to 5.0 anyway should do if they see those warnings.

**Comment by jbednar** [comment] 2017-04-05 14:53
Right.

**Comment by jbednar** [comment] 2017-04-05 14:55
Note that the PR has now been merged to Jupyter master again, so whatever next dev release there is should be ok again.

**Comment by philippjfr** [comment] 2017-04-05 16:51
>Basically, anything they do with any viz program is likely to run into problems with 5.0

I don't think this is true really, you'll be hard pressed to reach the limit with bokeh plots as bokeh will likely fall over before it bites and in matplotlib you have to push at least a 2000x2000 pixels (I suspect a lot more) to trigger it. I'm still fairly annoyed with it because it doesn't make sense to limit the data throughput, but I actually think outside of HoloMaps this will be a fairly rare problem.

**Comment by jbednar** [comment] 2017-04-05 17:07
I ran into the issue with vastly smaller plots in mpl, I just wasn't able to reproduce it *reliably*.  It's not the total size that matters, it's the data rate...

**Comment by jlstevens** [comment] 2017-04-05 17:09
> I ran into the issue with vastly smaller plots in mpl, I just wasn't able to reproduce it reliably. It's not the total size that matters, it's the data rate...

That is worrying - I was about to suggest we update the tutorials so they don't trigger this warning and leave notebook unpinned (and warn the user in the release notes). Sounds like that might not be possible.

**Comment by philippjfr** [comment] 2017-04-05 17:19
>I ran into the issue with vastly smaller plots in mpl, I just wasn't able to reproduce it reliably. It's not the total size that matters, it's the data rate...

It is related to total size though since it averages the throughput over some small period of time and anything that completes before that time is up won't be affected. As far as I can tell the effective limit is about 2MB (after 100 attempts I haven't been able to reproduce it at that size).

**Comment by jbednar** [comment] 2017-04-05 17:33
A 2MB plot is not all that much...

**Comment by philippjfr** [comment] 2017-04-05 17:38
>A 2MB plot is not all that much...

Agreed, for an completely random image exported to png that's only about 1200x1200.

**Comment by jlongwe** [comment] 2017-04-11 09:48
Hi @jlstevens 

Please share how you downgraded to v4.2.2

I unistalled and tried `pip3 install jupyter==4.2.2`

but i am not winning.

**Comment by BoomBidiBuyBuy** [comment] 2017-05-23 22:29
Hello, I'm sorry, my question is might be a little dummy, but I wonder how to resolve it for jupyerhub? I've tried pass the coressponding argument argument right to 'jupyterhub' and tried to set it in config file, but without any  success.

**Comment by philippjfr** [comment] 2017-05-24 12:29
@BoomBidiBuyBuy That's probably a question for the [JupyterHub](https://github.com/jupyterhub/jupyterhub) repo.

**Comment by philippjfr** [comment] 2017-06-19 02:13
There really isn't much more we can do here except hope that Jupyter 5.1 is released soon. Going to close.

**Closed by philippjfr** 2017-06-19 02:13 UTC
Labels: docs, notebook

**Comment by DataPsycho** [comment] 2018-01-29 11:58
Good Choice: `jupyter notebook --NotebookApp.iopub_data_rate_limit=1.0e10`  . It works for me. I had the same problem. https://community.plot.ly/t/tips-for-using-plotly-with-jupyter-notebook-5-0-the-latest-version/4156
