### ISSUE TITLE
Overlaying Curve and Scatter, order matters

### ISSUE THREAD

**Issue by vascotenner** [ioam/holoviews#41] opened 2015-04-20 14:59 UTC
I try to overlay a cross-section with some points. However, it matters in which order I create the overlay:

Works
```python
fs = Raster(np.array([[1]]))
hv.Overlay([hv.Scatter([[1,1]]),fs.sample(y=0),fs.sample(y=0)])
```

Does not work
```python
fs = Raster(np.array([[1]]))
hv.Overlay([fs.sample(y=0),hv.Scatter([[1,1]]),fs.sample(y=0)])
```
```python
Traceback (most recent call last):
  File "/home/xx/src/holoviews/holoviews/ipython/display_hooks.py", line 197, in wrapped
    **kwargs)
  File "/home/xx/src/holoviews/holoviews/ipython/display_hooks.py", line 227, in element_display
    **opts(element, get_plot_size(element, size)))()
  File "/home/xx/src/holoviews/holoviews/plotting/element.py", line 514, in __init__
    self.subplots = self._create_subplots(ranges)
  File "/home/xx/src/holoviews/holoviews/plotting/element.py", line 528, in _create_subplots
    cyclic_index,  _ = next(style_iter[style_key])
StopIteration
```
```
:Overlay
   .Curve.I   :Curve   [x]   (z)
   .Scatter.I :Scatter   [x]   (y)
   .Curve.II  :Curve   [x]   (z)
```
I use master, with the last commit a696bd28fd491c

**Comment by jlstevens** [comment] 2015-04-20 15:39
Thanks for the bug report!

We've looked into it and we realize our algorithm for plotting overlays isn't quite right. Essentially, in order to handle missing elements in Overlay correctly we need to figure our a total ordering given a set of partial orderings (i.e topological sort!).

Thankfully, we think we've figured out how to do it properly now and should have the bug fixed very soon.

**Comment by jlstevens** [comment] 2015-04-22 20:04
Philipp has now committed the fix in 56af71f1.

The issue is rather subtle so we will probably have a few more commits before the updated code works exactly the way we want it to. At the minimum we will want docstrings and comments to explain why this code is needed!

**Comment by philippjfr** [comment] 2015-04-22 20:25
I've tested it and the behavior should be largely unchanged from what it was before, while fixing issues when interleaving Elements. The previous algorithm produced almost identical output as long as the Elements in the Layouts weren't interleaved, with interleaving now being supported your example now works as expected.

What has changed and might need further adjustment is how the zorder of the layers in the Overlay interacts with axis gridlines and other axis artists. Further tests and documentation for this code should be added, but I'm going away for a few days and won't be able to get on it right away.

**Comment by jbednar** [comment] 2015-04-22 20:26
The fix is also in c4f1685.

**Comment by jlstevens** [comment] 2015-04-23 13:49
I think it might be worth having plot instantiation tests where you don't test the display output but you do test whether the plot class can be created and used. That might be a good way to test for issues such as this one.

If we can add some of these tests and they pass, then I think we can close the issue.

**Comment by jbednar** [comment] 2015-04-23 15:26
Sure.

**Comment by philippjfr** [comment] 2015-04-23 18:33
Agreed plot instantiation tests would be very helpful. As part of the recent refactor most plots were rewritten in such a way that most things are precomputed on instantiation, which means simple plot instantiation should provide a decent amount of coverage.

**Comment by jlstevens** [comment] 2015-04-26 17:09
I thought I could close [this issue via commit](https://help.github.com/articles/closing-issues-via-commit-messages/) but it didn't seem to work. 

Anyway, I added one plot instantiation unit test (67733f40) to avoid regression so I will close this issue now.

**Closed by jlstevens** 2015-04-26 17:09 UTC
