### ISSUE TITLE
DynamicMap not fully working in Jupyterlab

### ISSUE THREAD

**Issue by michaelaye** [ioam/holoviews#1803] opened 2017-08-09 22:25 UTC
Using jupyterlab 0.26.4 (conda-forge) on Python 3.6 and holoviews 1.8.2-x-g7df251bcd
I have the following happening:

<img width="1128" alt="screenshot 2017-08-09 16 24 28" src="https://user-images.githubusercontent.com/69774/29146605-3bdca80a-7d1f-11e7-926e-2649c2fe9fcb.png">

As you can see, the automatic display with range widgets fails.

**Comment by jlstevens** [comment] 2017-08-09 23:00
I'm surprised anything is working in JupyterLab! Bokeh isn't and the last time I looked at it, the holoviews extension failed to load.

**Comment by michaelaye** [comment] 2017-08-09 23:00
ah, okay. thanks! :)

**Comment by jbednar** [comment] 2017-08-09 23:02
That said, getting Bokeh working in JupyterLab is something we are working on with urgency, and after that, it will be time to make HoloViews work with it too.  Stay tuned!

**Comment by stonebig** [comment] 2017-09-30 22:02
Bokeh works in Jupyterlab now.

**Comment by philippjfr** [comment] 2018-01-04 18:47
Will close as duplicate of https://github.com/ioam/holoviews/issues/687. We really have to bite the bullet on this soon.

**Comment by philippjfr** [comment] 2018-01-04 18:48
@stonebig Yes, static bokeh plots do work now, but all the machinery to get comms working is not yet there, which is our main sticking point.

**Closed by philippjfr** 2018-01-04 18:47 UTC
