### ISSUE TITLE
Add some margin to plots by default

### ISSUE THREAD

**Issue by dclong** [ioam/holoviews#3407] opened 2019-01-17 03:11 UTC
Below is a plot generated with default settings. There are 2 points in the upper-right corner which is hardly noticeable. It's better to add some margin to the plot some that all points on the plot are easily visible. 

![image](https://user-images.githubusercontent.com/824507/51293177-878c9d00-19c2-11e9-810f-b4620b65aeb2.png)

**Comment by philippjfr** [comment] 2019-01-17 04:08
This is a duplicate of https://github.com/ioam/holoviews/issues/1090 which I just reopened. We added a padding option in 1.11.0 and will enable it by default at least for some elements in 1.12.0.

**Closed by philippjfr** 2019-01-17 04:08 UTC
