### ISSUE TITLE
Document regrid operation

### ISSUE THREAD

**Issue by jbednar** [ioam/holoviews#1909] opened 2017-09-21 20:54 UTC
I'm not sure if I'm going about this the right way, but I don't seem to get anything reasonable out of datashading an Image:

```
import holoviews as hv
import numpy as np
from holoviews.operation.datashader import datashade, shade, aggregate, regrid
hv.extension("bokeh")

x,y = np.mgrid[-50:51, -50:51] * 0.1
r = 0.5*np.sin(np.pi+3*x**2+y**2)+0.5
g = 0.5*np.sin(x**2+2*y**2)+0.5
b = 0.5*np.sin(np.pi/2+x**2+y**2)+0.5

hv.Image(r) + datashade(hv.Image(r))
```

![image](https://user-images.githubusercontent.com/1695496/30718276-08b3d5f6-9ee5-11e7-8229-64039ceadc8a.png)

I had expected this to use datashader's raster support, but when first loading there is no image at all in the second subfigure, and then on zooming out and back in I get various crazy patterns like this.  

Eventually I don't want an Image, but an RGB where each of 3 or 4 underlying images is datashaded, but I can't see how I would even express that (``datashade(hv.RGB(...))``?).  I'm trying to implement https://anaconda.org/jbednar/landsat using holoviews, but am not having much luck.

**Comment by philippjfr** [comment] 2017-09-21 21:29
Yes, you're going about this wrong, the default aggregator is ``count`` which does nothing here. What you want is the ``regrid`` operation.

**Comment by philippjfr** [comment] 2017-09-21 21:32
Repurposed the issue to document ``regrid`` in HoloViews.

**Comment by jbednar** [comment] 2017-09-21 21:32
Hmm. Regrid is better, but doesn't work either:

![image](https://user-images.githubusercontent.com/1695496/30719789-7a4f7774-9eea-11e7-8ebe-bb057bb861c4.png)

**Comment by philippjfr** [comment] 2017-09-21 21:36
Can't reproduce that, this works fine:

```python
img = hv.Image(np.arange(10)* np.arange(10)[np.newaxis].T)
img + regrid(img)
```

What version of datashader do you have?

**Comment by jbednar** [comment] 2017-09-21 21:41
Github master (0.6.1-6-g09973d3).

![image](https://user-images.githubusercontent.com/1695496/30720029-8f03e0a0-9eeb-11e7-85dc-77d0cc21179b.png)

**Comment by jbednar** [comment] 2017-09-21 21:47
You should try the code in the first cell above, but with datashade replaced by regrid.  In your range based example I can't tell if it's working properly or not, but with the above code I can see that it definitely is not.

**Comment by philippjfr** [comment] 2017-09-21 21:58
Could you paste the code?

**Comment by philippjfr** [comment] 2017-09-21 22:11
Sigh...there appears to be another bug in datashader.

**Comment by jbednar** [comment] 2017-09-21 22:56
The code is in the first cell...

**Comment by jbednar** [comment] 2017-09-21 22:56
(Only the very last line changes in any of the examples here).

**Comment by jbednar** [comment] 2017-09-21 23:12
I know this isn't the way it's currently implemented, but the way I *expected* this to work is:

1. aggregate(hv.Points(..)) uses canvas.points(agg=count()).
2. aggregate(hv.Path(...)) (or Curve) uses canvas.line(agg=any())
3. aggregate(hv.Image(...)) (or RGB, which would work individually) uses canvas.raster(agg=mean()))

Each of the indicated agg defaults is the default value in datashader (for None).

I know raster() doesn't currently use the same agg options, but I think it should eventually, at least for downsampling, so it would be nice to unify that at the ds level.  Otherwise, is this very different from how you think it should be?

**Comment by philippjfr** [comment] 2017-09-21 23:25
I'd be happy for aggregate to provide some convenience around ``regrid`` but I don't think it replaces ``regrid`` because that is more general than what aggregate can provide. Apart from that the main thing I'm worried about is that it would have to ignore the default ``count `` ``aggregator`` and that some others like ``count_cat`` and ``any`` are also pointless for an Image.

>I know raster() doesn't currently use the same agg options, but I think it should eventually, at least for downsampling, so it would be nice to unify that at the ds level. 

The agg objects are a bit weird in the case of images because there is no column to refer to, so there's no reason to do ``ds.mean('z')`` and just using ``ds.mean`` would still be inconsistent.

**Comment by jbednar** [comment] 2017-09-21 23:42
Well, all of the canvas glyphs actually default to None; can't we use that?

**Comment by jbednar** [comment] 2017-09-21 23:46
``any`` isn't pointless for an image with an alpha mask; it should basically extract that mask at a different resolution.  ``count_cat`` is meant to be generalized to ``cat(count...)``, and some of the aggregations provided to it may be more meaningful.

**Comment by philippjfr** [comment] 2017-09-22 18:22
Fixed in https://github.com/bokeh/datashader/pull/475, please test when you get a minute.

**Comment by jbednar** [comment] 2017-10-03 22:00
The bug is fixed, but I do think we need to address the API issues still.

**Comment by philippjfr** [comment] 2017-10-03 22:43
As a first step we'd have to support ``ds.mean()``, ``ds.min()`` etc. so the API in datashader is at least consistent. Currently that results in:

    TypeError: __init__() missing 1 required positional argument: 'column'

**Comment by jlstevens** [comment] 2017-10-04 09:56
It may be mentioned in another issue, but I would like ``datashade`` to do regridding when passed a raster type. This doesn't mean there can always be a dedicated ``regrid`` operation for more advanced control with its own documentation.

If you agree with that idea, I would document the regridding capability of ``datashade`` first (once it is added) as passing rasters to ``datashade`` seemed like a pretty intuitive thing and something I expected to 'just work'.

**Comment by philippjfr** [comment] 2017-10-04 13:34
I believe that's exactly what we already decided above.

**Comment by jlstevens** [comment] 2017-10-04 13:36
I'm talking about documentation: we should document ``datashade`` first as being able to do regridding then the ``regrid`` operation itself.

**Comment by jbednar** [comment] 2017-10-05 01:51
I agree with all that.  Yes, sounds like we need to make those changes to ds.mean(), etc.

**Comment by jbednar** [comment] 2018-02-09 17:54
Those changes are now done, as of Datashader 0.6.5, so hv can now be updated to match.

**Comment by philippjfr** [comment] 2018-03-19 18:53
I'll hand this over to you once I've improved ``rasterize``.

**Comment by philippjfr** [comment] 2018-04-03 19:59
While you're working on these docs there are a few performance related things to point out:

1. Dask dataframes are going to be fastest, pandas dataframes a close second
2. ``precompute`` can be used to cache the last set of data, for dataframes/dask tabular datasets and xarray gridded datasets this makes no difference, for TriMesh/QuadMesh this will make a huge difference
3. When using datashader+geoviews the data should be projected first using ``gv.operation.project``.

**Closed** 2018-04-08 03:27 UTC
Labels: docs
