### ISSUE TITLE
GridSpace Fails with Bokeh extension

### ISSUE THREAD

**Issue by Rahuketu86** [ioam/holoviews#2173] opened 2017-12-04 09:19 UTC
```
import numpy as np
import holoviews as hv
hv.extension('bokeh')
np.random.seed(10)

def sine_curve(phase, freq, amp, power, samples=102):
    xvals = [0.1* i for i in range(samples)]
    return [(x, amp*np.sin(phase+freq*x)**power) for x in xvals]

phases =      [0, np.pi/2, np.pi, 3*np.pi/2]
powers =      [1,2,3]
amplitudes =  [0.5,0.75, 1.0]
frequencies = [0.5, 0.75, 1.0, 1.25, 1.5, 1.75]


gridspace = hv.GridSpace(kdims=['Amplitude', 'Power'], group='Parameters', label='Sines')

for power in powers:
    for amplitude in amplitudes:
        holomap = hv.HoloMap(kdims=['Frequency'])
        for frequency in frequencies:
            sines = {phase : hv.Curve(sine_curve(phase, frequency, amplitude, power))
                     for phase in phases}
            ndoverlay = hv.NdOverlay(sines , kdims=['Phase']).relabel(group='Phases',
                                                                      label='Sines', depth=1)
            overlay = ndoverlay * hv.Points([(i,0) for i in range(0,10)], group='Markers', label='Dots')
            holomap[frequency] = overlay
        gridspace[amplitude, power] = holomap

penguins = hv.RGB.load_image('../reference/elements/assets/penguins.png').relabel(group="Family", label="Penguin")

layout = gridspace + penguins
```

Fails with following error:

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\formatters.py in __call__(self, obj)
    305                 pass
    306             else:
--> 307                 return printer(obj)
    308             # Finally look for special method names
    309             method = get_real_method(obj, self.print_method)

C:\ProgramData\Anaconda3\lib\site-packages\holoviews\ipython\display_hooks.py in pprint_display(obj)
    257     if not ip.display_formatter.formatters['text/plain'].pprint:
    258         return None
--> 259     return display(obj, raw=True)
    260 
    261 

C:\ProgramData\Anaconda3\lib\site-packages\holoviews\ipython\display_hooks.py in display(obj, raw, **kwargs)
    240     elif isinstance(obj, (Layout, NdLayout, AdjointLayout)):
    241         with option_state(obj):
--> 242             html = layout_display(obj)
    243     elif isinstance(obj, (HoloMap, DynamicMap)):
    244         with option_state(obj):

C:\ProgramData\Anaconda3\lib\site-packages\holoviews\ipython\display_hooks.py in wrapped(element)
    130         try:
    131             html = fn(element,
--> 132                       max_frames=OutputSettings.options['max_frames'])
    133 
    134             # Only want to add to the archive for one display hook...

C:\ProgramData\Anaconda3\lib\site-packages\holoviews\ipython\display_hooks.py in layout_display(layout, max_frames)
    211         return None
    212 
--> 213     return render(layout)
    214 
    215 

C:\ProgramData\Anaconda3\lib\site-packages\holoviews\ipython\display_hooks.py in render(obj, **kwargs)
     60     if renderer.fig == 'pdf':
     61         renderer = renderer.instance(fig='png')
---> 62     return renderer.html(obj, **kwargs)
     63 
     64 

C:\ProgramData\Anaconda3\lib\site-packages\holoviews\plotting\renderer.py in html(self, obj, fmt, css, comm, **kwargs)
    256         code to initialize a Comm, if the plot supplies one.
    257         """
--> 258         plot, fmt =  self._validate(obj, fmt)
    259         figdata, _ = self(plot, fmt, **kwargs)
    260         if css is None: css = self.css

C:\ProgramData\Anaconda3\lib\site-packages\holoviews\plotting\renderer.py in _validate(self, obj, fmt)
    192         if isinstance(obj, tuple(self.widgets.values())):
    193             return obj, 'html'
--> 194         plot = self.get_plot(obj, renderer=self)
    195 
    196         fig_formats = self.mode_formats['fig'][self.mode]

C:\ProgramData\Anaconda3\lib\site-packages\holoviews\plotting\bokeh\renderer.py in get_plot(self_or_cls, obj, doc, renderer)
    115         combining the bokeh model with another plot.
    116         """
--> 117         plot = super(BokehRenderer, self_or_cls).get_plot(obj, renderer)
    118         if self_or_cls.mode == 'server' and doc is None:
    119             doc = curdoc()

C:\ProgramData\Anaconda3\lib\site-packages\holoviews\plotting\renderer.py in get_plot(self_or_cls, obj, renderer)
    179             plot = self_or_cls.plotting_class(obj)(obj, renderer=renderer,
    180                                                    **plot_opts)
--> 181             plot.update(0)
    182         else:
    183             plot = obj

C:\ProgramData\Anaconda3\lib\site-packages\holoviews\plotting\plot.py in update(self, key)
    484         if len(self) == 1 and key == 0 and not self.drawn:
    485             return self.initialize_plot()
--> 486         item = self.__getitem__(key)
    487         self.traverse(lambda x: setattr(x, '_updated', True))
    488         return item

C:\ProgramData\Anaconda3\lib\site-packages\holoviews\plotting\plot.py in __getitem__(self, frame)
    219         if isinstance(frame, int) and frame > len(self):
    220             self.warning("Showing last frame available: %d" % len(self))
--> 221         if not self.drawn: self.handles['fig'] = self.initialize_plot()
    222         if not isinstance(frame, tuple):
    223             frame = self.keys[frame]

C:\ProgramData\Anaconda3\lib\site-packages\holoviews\plotting\bokeh\plot.py in initialize_plot(self, plots, ranges)
    655             if subplot is not None:
    656                 shared_plots = passed_plots if self.shared_axes else None
--> 657                 subplots = subplot.initialize_plot(ranges=ranges, plots=shared_plots)
    658 
    659                 # Computes plotting offsets depending on

C:\ProgramData\Anaconda3\lib\site-packages\holoviews\plotting\bokeh\plot.py in initialize_plot(self, ranges, plots)
    787             if subplot:
    788                 passed_plots = plots  + adjoined_plots
--> 789                 adjoined_plots.append(subplot.initialize_plot(ranges=ranges, plots=passed_plots))
    790             else:
    791                 adjoined_plots.append(empty_plot(0, 0))

C:\ProgramData\Anaconda3\lib\site-packages\holoviews\plotting\bokeh\plot.py in initialize_plot(self, ranges, plots)
    420 
    421         plot = gridplot(plots[::-1])
--> 422         plot = self._make_axes(plot)
    423 
    424         title = self._get_title(self.keys[-1])

C:\ProgramData\Anaconda3\lib\site-packages\holoviews\plotting\bokeh\plot.py in _make_axes(self, plot)
    438 
    439     def _make_axes(self, plot):
--> 440         width, height = self.renderer.get_size(plot)
    441         x_axis, y_axis = None, None
    442         kwargs = dict(sizing_mode=self.sizing_mode)

C:\ProgramData\Anaconda3\lib\site-packages\holoviews\plotting\bokeh\renderer.py in get_size(self_or_cls, plot)
    284             raise ValueError('Can only compute sizes for HoloViews '
    285                              'and bokeh plot objects.')
--> 286         return compute_plot_size(plot)
    287 
    288 

C:\ProgramData\Anaconda3\lib\site-packages\holoviews\plotting\bokeh\util.py in compute_plot_size(plot)
    159         else:
    160             w_agg, h_agg = (np.max, np.sum)
--> 161         widths, heights = zip(*[compute_plot_size(child) for child in plot.children])
    162         width, height = w_agg(widths), h_agg(heights)
    163     elif isinstance(plot, (Figure, Chart)):

C:\ProgramData\Anaconda3\lib\site-packages\holoviews\plotting\bokeh\util.py in <listcomp>(.0)
    159         else:
    160             w_agg, h_agg = (np.max, np.sum)
--> 161         widths, heights = zip(*[compute_plot_size(child) for child in plot.children])
    162         width, height = w_agg(widths), h_agg(heights)
    163     elif isinstance(plot, (Figure, Chart)):

C:\ProgramData\Anaconda3\lib\site-packages\holoviews\plotting\bokeh\util.py in compute_plot_size(plot)
    152         return 0, 0
    153     elif isinstance(plot, (Row, Column, ToolbarBox, WidgetBox, Tabs)):
--> 154         if not plot.children: return 0, 0
    155         if isinstance(plot, Row) or (isinstance(plot, ToolbarBox) and plot.toolbar_location not in ['right', 'left']):
    156             w_agg, h_agg = (np.sum, np.max)

AttributeError: 'ToolbarBox' object has no attribute 'children'

:Layout
   .Parameters.Sines :GridSpace   [Amplitude,Power]
      :HoloMap   [Frequency]
         :Overlay
            .Phases.Sines :NdOverlay   [Phase]
               :Curve   [x]   (y)
            .Markers.Dots :Points   [x,y]
   .Family.Penguin   :RGB   [x,y]   (R,G,B,A)
```

Changing  to hv.extension('matplotlib') works .  I am using holoviews version 1.9 and bokeh version 0.12.11

**Comment by philippjfr** [comment] 2017-12-04 12:34
Closing as duplicate of https://github.com/ioam/holoviews/issues/2173, this has already been fixed in master. We'll try to have a 1.9.2 release to fix this soon.

**Closed by philippjfr** 2017-12-04 12:34 UTC
