### ISSUE TITLE
Bare element

### ISSUE THREAD

**Issue by jbednar** [ioam/holoviews#125] opened 2015-06-03 02:43 UTC
Is it possible to have an Element that shows up bare (no axes, ticks, boxes, etc.) by default, not because of plot options but because of the Element type or some flag stored on the Element itself when it is created?  I'm thinking specifically here of an Image that's a figure reprinted from another paper.  Such images often form parts of figures, but it's very rarely appropriate to put our own axes on them, and it might be nice to be able to indicate succinctly that they are already preformatted by whatever generated the image.  Moreover, it would be nice if they could use the full available subfigure space, without reserving room for the non-existent axes and labels.  Would it make sense to have a RawImage type, or some flag on Image, to achieve this?  I would want it to be very easy for people to put such images into mixtures of other subfigures without having to specify special options in each such notebook or cell.  I think the idea of an alias was mentioned before, so that one could create such a RawImage to work like a new type, but I can't remember whether that was actually implemented or would solve this issue.  I guess we could make a special group and label for it, but whatever it is I think there should be one obvious way to do it that we make clear in the tutorials.

**Comment by jlstevens** [comment] 2015-06-04 16:26
I think ``Image`` or ``RGB`` is a special case because any other element won't contain enough data to reproduce or reprint a figure from a paper.

I am not in favor of adding attributes to any ``Raster`` class to support this but I can imagine supporting a ``bare`` option in the ``load`` classmethod. This would be used when loading data from file and would simply disable the axes, ticks, frame etc by setting plot options appropriately using ``__call__`` before returning the loaded element.

**Comment by philippjfr** [comment] 2015-09-18 03:14
As the commit referenced above suggests ``RGB.load_image`` now supports a ``bare`` option, which will disable the axis labels on the loaded image. Closing this issue.

**Closed by philippjfr** 2015-09-18 03:14 UTC
