### ISSUE TITLE
Only when using matplotlib backend, AssertionError: DynamicMap must only contain one type of object, not both NdOverlay and Overlay.

### ISSUE THREAD

**Issue by daliu87** [ioam/holoviews#2359] opened 2018-02-21 00:54 UTC
Using bokeh, embedded NdOverlay and Overlay together in a DynamicMap seems to work fine, but when switching to a matplotlib backend I get the following error:

```python
Traceback (most recent call last):
  File "/home/daliu/anaconda3/lib/python3.6/site-packages/holoviews/plotting/util.py", line 196, in get_plot_frame
    return map_obj[key]
  File "/home/daliu/anaconda3/lib/python3.6/site-packages/holoviews/core/spaces.py", line 1029, in __getitem__
    self._cache(tuple_key, val)
  File "/home/daliu/anaconda3/lib/python3.6/site-packages/holoviews/core/spaces.py", line 1076, in _cache
    self[key] = val
  File "/home/daliu/anaconda3/lib/python3.6/site-packages/holoviews/core/ndmapping.py", line 520, in __setitem__
    self._add_item(key, value, update=False)
  File "/home/daliu/anaconda3/lib/python3.6/site-packages/holoviews/core/ndmapping.py", line 157, in _add_item
    self._item_check(dim_vals, data)
  File "/home/daliu/anaconda3/lib/python3.6/site-packages/holoviews/core/ndmapping.py", line 821, in _item_check
    (self.__class__.__name__, type(data).__name__, self.type.__name__))
AssertionError: DynamicMap must only contain one type of object, not both NdOverlay and Overlay.
```

The Dynamic map still seems render and work fine, there's just the AssertionError.

Any idea what might be happening?

**Comment by jlstevens** [comment] 2018-02-23 15:44
Looking at the traceback, I can't see why this code path would only apply to matplotlib and not bokeh. Seems like a bug to me!

**Comment by philippjfr** [comment] 2018-02-24 13:52
Duplicate of https://github.com/ioam/holoviews/issues/2284

**Closed by philippjfr** 2018-02-24 13:52 UTC
Labels: bug
