### ISSUE TITLE
operation.gradient and cyclic ranges

### ISSUE THREAD

**Issue by vascotenner** [ioam/holoviews#238] opened 2015-08-21 14:26 UTC
The operation.gradient is not working on Images with cyclic ranges, and not working properly on images with no cyclic ranges.

In element.py:319 to 329 the logic is wrong. If the input is not a cyclic range, then it should not try to wrap it.

I did not supply a PR, because also when the image has a cyclic range, but an asymnetric range, it requires some thought what to do.

**Comment by jlstevens** [comment] 2015-08-21 14:52
The implementation of the gradient operation inherited some rather old code that pre-dated HoloViews. It was probably never designed to handle cyclic quantities so I would be very happy to merge any PR that helps generalizes this operation properly.

I am also happy to fix the lines you mention although I would prefer to fix generalize this code properly. Even a PR that raises an exception when an asymmetric cyclic range is detected would be better than what we have now! If you are willing to submit such a PR, the issue of asymmetric cyclic ranges could be addressed at a later date,

**Comment by vascotenner** [comment] 2015-08-21 15:18
Furthermore, it would be useful to to extend this function also to different dimensions (1D curves for example).

**Comment by jbednar** [comment] 2015-08-21 15:27
The gradient code *was* originally designed for cyclic quantities, because it was first implemented for 2D maps of orientation (a pi-periodic quantity).  So it's the non-cyclic case that would need the most attention.  Can you explain more specifically what you mean by an asymmetric cyclic range, perhaps with  some code and output and what the problem is in that case?

**Comment by vascotenner** [comment] 2015-08-21 15:37
For the non_cyclic range, there is no wrapping needed. In that case the conditional codeblock should not run.

One of the problems is that Dimension.range is a tuple, not an float.
For range=(-5,100), the code should wrap between -5 and 100, not between 0 and 100. This can be obtained by first shifting the values to the range 0,105, and then wrapping, and then back again.

**Comment by jlstevens** [comment] 2015-08-21 15:42
> The gradient code was originally designed for cyclic quantities

Yes sorry! Wasn't thinking properly when I typed that.

> For the non_cyclic range, there is no wrapping needed. In that case the conditional codeblock should not run.

That sounds correct. As for the handling of the tuple, it sounds plausible but I would need to think about it a bit more carefully first...

**Comment by vascotenner** [comment] 2015-08-21 15:43
I submitted a PR with my prosition.

**Comment by jbednar** [comment] 2015-08-21 15:44
Yes, what you suggest for -5..100 sounds correct to me.

**Comment by vascotenner** [comment] 2015-08-21 17:05
Now there is taken into account for the wrapping. Small differences are preferred above large ones.

**Comment by philippjfr** [comment] 2015-11-10 16:22
The PR has merged a while back, so I'll close the issue.

**Closed by philippjfr** 2015-11-10 16:22 UTC
