### ISSUE TITLE
Bokeh reset button causes loss of axes in HoloMap

### ISSUE THREAD

**Issue by jordansamuels** [ioam/holoviews#1615] opened 2017-06-26 23:37 UTC
Using the following code for a repro, the attached animated gif shows that if you set the kdim to non-zero and hit the reset button, the x- and y- axes and their ticks/labels are removed.  This is using latest master.

```
import holoviews as hv
hv.extension('bokeh')
hv.HoloMap({p: hv.Curve([(0,0),(1,1),(2,p)]) for p in np.linspace(0, 1, 17)}).collate()
```

![reset_button_loss_axes](https://user-images.githubusercontent.com/610909/27564609-ed339ae6-5aa6-11e7-801a-253fcdc3d203.gif)

**Comment by jlstevens** [comment] 2017-06-26 23:39
Wow! Never seen this issue myself but it will need investigating before we release tomorrow...

**Comment by philippjfr** [comment] 2017-06-26 23:44
I've occasionally seen this but have never tracked it down to a reproducible example. I suspect this may be an issue in bokeh so it's worth looking at the browser JS console. If we can confirm it's a bokeh issue we can open an issue there as well.

**Comment by jlstevens** [comment] 2017-06-26 23:46
For what it is worth, I just used the snippet shown above and failed to reproduce the issue.

**Comment by philippjfr** [comment] 2017-06-26 23:47
I can definitely reproduce it.

**Comment by jlstevens** [comment] 2017-06-26 23:50
Sorry, I was too quick trying it out and forgot to click the reset button. I can reproduce it although I don't see anything in the web console...

**Comment by jordansamuels** [comment] 2017-06-26 23:54
@jlstevens I'd be fine with releasing and fixing later.  This issue also exists in 1.7.0, so it's not new.
> Wow! Never seen this issue myself but it will need investigating before we release tomorrow...

**Comment by timothydmorton** [comment] 2017-07-31 18:03
Just confirming that I also lose axes with a simple bokeh+datashaded image, when I click reset.

**Comment by timothydmorton** [comment] 2017-07-31 18:28
(p.s. only in the notebook though; not when viewing the same plot through a bokeh server)

**Comment by jlstevens** [comment] 2017-07-31 19:46
> only in the notebook though; not when viewing the same plot through a bokeh server

That is useful information, thanks!

**Comment by jordansamuels** [comment] 2017-08-21 20:05
This issues does appear in e.g. http://holoviews.org/getting_started/Introduction.html in the NY Taxi plots.

**Comment by philippjfr** [comment] 2017-09-15 10:45
I can no longer reproduce this with bokeh 0.12.9. If someone else can confirm I'll close this.

**Comment by jlstevens** [comment] 2017-09-15 12:11
I also tried to reproduce this recently and couldn't. If @jordansamuels or @timothydmorton can confirm that this issue seems to be fixed, I agree we can finally close this issue.

**Comment by jordansamuels** [comment] 2017-09-15 13:40
Agree, with bokeh 0.12.9 and holoviews 1.8.4 this issue doesn't seem to exist.  Thanks!

**Comment by jlstevens** [comment] 2017-09-15 14:02
Very happy to close this issue without having had to make a fix in HoloViews! :-)

**Closed by jlstevens** 2017-09-15 14:02 UTC
Labels: bokeh, bug
