### ISSUE TITLE
DynamicMaps fails on clone due to duplicate callback argument

### ISSUE THREAD

**Issue by philippjfr** [ioam/holoviews#326] opened 2015-12-04 04:13 UTC
Here's the example of where I encountered it:

```python
def test(a):
    return hv.Image(np.random.rand(10, 10))

def test2(a):
    return hv.Curve(np.random.rand(10, 2)) * hv.VLine(a)

hv.DynamicMap(test, kdims=[hv.Dimension('A', range=(0, 5))]) +\
hv.DynamicMap(test, kdims=[hv.Dimension('A', range=(0, 5))]) + \
hv.DynamicMap(test2, kdims=[hv.Dimension('A', range=(0, 5))])
```

```bash
  File "/Users/prudiger/topographica/external/holoviews/holoviews/core/spaces.py", line 481, in clone
    *(data,) + args, **overrides)
  File "/Users/prudiger/topographica/external/holoviews/holoviews/core/ndmapping.py", line 266, in clone
    *args, **overrides)
  File "/Users/prudiger/topographica/external/holoviews/holoviews/core/dimension.py", line 286, in clone
    return clone_type(data, *args, **{k:v for k,v in settings.items()
TypeError: __init__() got multiple values for keyword argument 'callback
```

**Comment by jlstevens** [comment] 2015-12-04 10:35
I know exactly what the issue is - clone isn't getting ``__pos_params``:

```
class Foo(object):
    __test = 3
    _test = 5
    
f = Foo()
getattr(f, '_test')   # Works
getattr(f, '__test') #Doesn't work
```

This is due to the name mangling that occurs when you use ``__`` (which I used to avoid this being added to ``AttrTrees``). Thankfully the fix is easy (82c47e4) and I'll add a couple of unit tests for ``DynamicMap.clone``. 

I'll close this issue but I am happy to reopen it if you are still having problems.

**Closed by jlstevens** 2015-12-04 10:35 UTC
Labels: bug
