### ISSUE TITLE
Working with IPython.widgets.interact (feature request)

### ISSUE THREAD

**Issue by basnijholt** [ioam/holoviews#62] opened 2015-05-11 10:20 UTC
Plotting a HoloMaps for my (big) dataset takes nearly 10 minutes, so I thought I could use ``IPython.widgets.interact`` to create the plots on the fly like:

```python
from IPython.html.widgets import interact
import holoviews as hv

def plot_graphs(xsize, ysize):
    return hv.Image(np.random.randn(xsize, ysize))

interact(plot_graphs, xsize=(0, 100, 10), ysize=(0, 100, 10))
```

Unfortunately this doesn't plot anything. Would it be difficult to support this? Or potentially an option which doesn't pregenerates all plots in one go?

**Comment by philippjfr** [comment] 2015-05-11 11:08
We have such an option, just haven't documented it very well. Try:

```python
%output holomap='widgets' widgets='live'
```

Optionally you can even use the nbagg backend like this allowing you to resize plots and rotate/pan 3d plots, just add backend='nbagg' to the line above. 

We won't provide any interface to IPython.interact until they declare it stable again.

**Comment by philippjfr** [comment] 2015-05-11 11:34
As sidenote, we are working on adding a truly dynamic HoloMap types, which can load/generate data on the fly as the live widgets described above still require all the data to be be precomputed and just does the rendering on the fly.

**Comment by basnijholt** [comment] 2015-05-11 11:37
Is it also possible to save the rendered HoloMap and load it again the next time it's computed?

**Comment by philippjfr** [comment] 2015-05-11 11:43
No, we're still considering how to best make that work. It should be possible to leave the widget in a semi-cached state where the frames that have been generated are cached in the notebook json, while new frames are transferred on the fly but we haven't gotten around to implementing that.

**Comment by philippjfr** [comment] 2015-05-11 13:00
Actually I'm not entirely sure what you means by:

>load it again the next time that the cell is evaluated

Do you mean when reloading the notebook or simply when re-executing the cell? For the latter you could use the %%capture magic, e.g.:

```
%%capture curves
display(hv.HoloMap({1:hv.Curve(np.random.rand(10, 2), label='A Blah'), 2:hv.Curve(np.random.rand(10, 2), label='A Blah')}))
```

Now you can do:

```
curves.show()
```

anywhere in the notebook and it will bring the widget back up.

**Comment by basnijholt** [comment] 2015-05-11 13:11
Didn't mean anything specific, but it would be nice to render all images once, and then if no data changes, it could bring up all images from some cache or something. At least that I don't have to wait a very long time.

**Comment by basnijholt** [comment] 2015-05-21 18:20
I would like to completely dump my use of ``matplotlib.pyplot`` in my scripts, and what I often do (amongst a lot of my colleagues) is to use ``interact`` to search an infinite parameter space, and calculating everything would be impossible.

Right now this works:
```python
import holoviews as hv
from IPython.html.widgets import interact
def fun(i):
    return hv.Image(np.random.randn(i,i))
```

then calling ``fun(10)`` produces an ``Image``, but when I try:
```python
interact(fun, i=(1,10))
```

this doesn't work, and merely puts out a slider with: ``<function __main__.fun>``.

I have no idea of how difficult this would be to implement, but it would certainly be a great argument in persuading the people here to use HoloViews.

**Comment by jlstevens** [comment] 2015-05-21 18:46
This is a request for a feature we've been intending for a long time and now have a rough protoype for: dynamic HoloMaps.

There are several major problems with the default IPython widgets using ``interact``:

* You cannot order them because the order it is up to the whims of Python dictionary ordering (at least the last time I checked!)
* They cannot be statically exported. This means means they lose their value when you don't have a live kernel (i.e when presenting your work to other people).
* There is generally very little control over caching, granularity etc.

When we get back to development after the next release, we will introduce ``DynamicMaps`` which are ``HoloMaps`` whose elements are generated dynamically using a function (i.e the same as ``fun`` in your example). They will support a fair bit more than interact does:

* You'll be able to  explore *bounded* parameter spaces to any precision (as interact does).
* You'll be able to explore *unbounded* parameter spaces - for instance simulation results that keep getting generated for as long as the simulation is running.
* You'll have the ability to export the ``DynamicMaps`` to static HTML (how much is exported will depend on a cache size value).
* You'll have the ability to generate normal ``HoloMaps`` easily from ``DynamicMaps``.

Generally, this is a feature we have wanted a long time and which we are very excited about! Personally, I am looking forward to having support for open-ended simulations without having to wait for the whole thing to run and doing so in a much more memory efficient way.

**Comment by philippjfr** [comment] 2015-05-21 19:11
Now that Jean-Luc has hopefully convinced you that our DynamicMap proposal will provide a far more customizable and reproducable alternative  to ``interact`` eventually, I've also drawn up a workaround for the meantime.

```python
import holoviews as hv
from IPython.html.widgets import interact
from IPython.display import display, HTML
from holoviews.ipython.display_hooks import display_widgets, process_object, display_figure, opts
from holoviews.ipython.magics import OutputMagic

def display_object(obj):
    info = process_object(obj)
    size = OutputMagic.options['size']
    if info:
        display(info)
        return
    
    if isinstance(obj, hv.HoloMap):
        otype = obj.type
    else:
        otype = type(obj)
    if otype not in hv.Store.registry: return None
    plot = hv.Store.registry[otype](obj, **opts(obj, size))
    use_widgets = len(obj.traverse(lambda x: x, [hv.HoloMap]))
    if use_widgets:
        html = display_widgets(plot)
    else:
        fig = plot()
        html = display_figure(fig)
    display(HTML(html))

def fun(i):
    img_fn = lambda: hv.Image(np.random.randn(i,i))
    hmap = hv.HoloMap({i: img_fn() for i in range(3)})
    display_object(hmap + img_fn())

interact(fun, i=(1,10))
```

The display_object function should display all HoloViews objects correctly, which means you can even generate nested widgets, where ``interact`` controls some outer hyperparameters, passing them to your function, which generates the HoloViews object. The ``display_object`` function then generates either the selected HoloViews widgets or a simple figure (if you want I could extend this to video). Let me know how it works for you.

**Comment by jlstevens** [comment] 2015-05-21 20:37
Philipp's code works for me which is nice but it has also reminded me of a few more reasons why I dislike interact:

* Horrible flickering which is difficult to get rid of.
* You can close the widgets and the only way to get rid of them is to re-run the cell.
* Although it *does* export the last frame shown, the parameters that were used to generate are not shown anywhere making the export useless (in my opinion!)

I would consider officially adding Philipp's code to holoviews if we could mitigate some of these problems, some of which I think are quite severe. As it is, I think we'll be able to offer a much nicer solution with ``DynamicMap``!

**Comment by philippjfr** [comment] 2015-05-21 22:50
I do think this might be useful to include anyway and despite those shortcomings. We put emphasis on being to export everything but for very large parameter spaces this simply becomes infeasible. This also allows you to do something DynamicMaps won't be able to do, which is to have nested widgets. Using this interface you could for example parameterize video output.

Another useful example would be to parameterize style or plot options, where you don't care about the value of whatever you picked anyway. This way you could fiddle with the plot and style options before exporting the notebook. Here's an example based on my code from above:

```
from matplotlib import cm

def fun(cmap, interpolation):
    style = dict(cmap=cmap, interpolation=interpolation)
    img_fn = lambda: hv.Image(np.random.randn(10,10))(style=style)
    hmap = hv.HoloMap({i: img_fn() for i in range(3)})
    display_object(hmap + img_fn())

interact(fun, cmap=cm.cmap_d.keys(), interpolation=('nearest', 'bilinear'))
```

![screenshot from 2015-05-21 23 38 55](https://cloud.githubusercontent.com/assets/1550771/7760349/b3c23c18-0012-11e5-8879-d0c624fd6862.png)

**Comment by basnijholt** [comment] 2015-05-22 07:35
The ``DynamicMap`` sounds amazing! 

For the moment I'm really happy with the ``interact`` sliders though, they are especially useful if your looking for some parameters and you can't precompute everything.

Now my last reason to use ``pyplot`` has disappeared as well :+1:

**Comment by jlstevens** [comment] 2015-05-22 10:04
> Now my last reason to use pyplot has disappeared as well 

Fantastic!

I don't think we are going to include Philipp's interact code in the imminent release. What I think we shall do is work on ``DynamicMap`` and see if we want to support ``interact`` once we've figured out the various pros and cons of the two approaches.

The fact you can nest widgets is certainly interesting and I could see that it would be useful - if only you could see the parameters used after export! 

In my opinion, not showing the selected parameters on export is absolutely not acceptable when it comes to achieving reproducibility. The state needed to reproduce what is such a notebook is lost when the kernel is killed; once the memory is cleared, there is no way for someone looking at the notebook later to achieve the same state.

Manually exploring a live version to try and match a snapshot in a notebook not an option:

1. For large parameter spaces this is not feasible.
2. Multiple points in the space may results that are different but look very similar.
3. This is a waste of time and is unnecessary if only the parameters were captured in the export!

I'm not against nesting widgets, but I don't want to encourage people to work in the notebook in a way that isn't reproducible.

**Comment by jlstevens** [comment] 2015-06-12 20:54
We have refactored some the backend system so the code Philipp posted is now stale. We are still working on a superior solution but as of writing, this is the updated version of Philipp's  code (which may well break again in future!):

```python
import holoviews as hv
import numpy as np
from IPython.html.widgets import interact
from IPython.display import display, HTML
from holoviews.ipython.display_hooks import display_widgets, process_object, display_frame
from holoviews.ipython.magics import OutputMagic
from holoviews.plotting import MPLRenderer

def display_object(obj):
    info = process_object(obj)
    size = OutputMagic.options['size']
    if info:
        display(info)
        return

    if isinstance(obj, hv.HoloMap):
        otype = obj.type
    else:
        otype = type(obj)
    if otype not in hv.Store.registry: return None
    plot = hv.Store.registry[otype](obj, **MPLRenderer.plot_options(obj, size))
    use_widgets = len(obj.traverse(lambda x: x, [hv.HoloMap]))
    if use_widgets:
        options = dict(dpi=72, backend='mpl', figure_format='png', css={}, message=None)
        html = display_widgets(plot, 'auto', 'embed', **options)
    else:
        fig = plot()
        html = display_frame(fig)
    display(HTML(html))

def fun(i):
    img_fn = lambda: hv.Image(np.random.randn(i,i))
    hmap = hv.HoloMap({i: img_fn() for i in range(3)})
    display_object(hmap + img_fn())
    
interact(fun, i=(1,10))
```

**Comment by basnijholt** [comment] 2015-06-15 08:26
```from holoviews.plotting import MPLRenderer```
should change into:
```from holoviews.plotting.mpl.renderer import MPLRenderer```

**Comment by jlstevens** [comment] 2015-06-15 15:09
Updated again:

```python
import holoviews as hv
import numpy as np
from IPython.html.widgets import interact
from IPython.display import display, HTML
from holoviews.ipython.display_hooks import display_widgets, process_object, display_frame
from holoviews.ipython.magics import OutputMagic
from holoviews import Store

def display_object(obj):
    info = process_object(obj)
    size = OutputMagic.options['size']
    if info:
        display(info)
        return

    if isinstance(obj, hv.HoloMap):
        otype = obj.type
    else:
        otype = type(obj)
    if otype not in hv.Store.registry['matplotlib']: return None
    print otype
    plot = hv.Store.registry['matplotlib'][otype](obj, **Store.renderers['matplotlib'].plot_options(obj, size))
    use_widgets = len(obj.traverse(lambda x: x, [hv.HoloMap]))
    if use_widgets:
        options = dict(dpi=72, backend='mpl', figure_format='png', css={}, message=None)
        html = display_widgets(plot, 'auto', 'embed', **options)
    else:
        plot.update(0)
        html = display_frame(plot.state)
        
    display(HTML(html))

def fun(i):
    img_fn = lambda: hv.Image(np.random.randn(i,i))
    hmap = hv.HoloMap({i: img_fn() for i in range(3)})
    display_object(hmap + img_fn())

interact(fun, i=(1,10))
```

**Comment by basnijholt** [comment] 2015-06-15 19:20
What about implementing this by default?

I'm sure that now I've convinced my colleagues to try ``holoviews`` that they will miss this feature.

**Comment by philippjfr** [comment] 2015-06-15 19:24
Yes I think we will ship a solution that addresses this. I'll be refactoring a lot of the widget and plotting code tonight but after that's done we can consider shipping something like it by default.

**Comment by jlstevens** [comment] 2015-06-24 18:00
I think it would be reasonable to ship something even if it isn't broadly advertised. If people are going to want to use something like this, it is better to have an officially supported approach instead of having to keep maintaining ad hoc code like this.

**Comment by philippjfr** [comment] 2015-06-25 15:07
So we've just refactored some of our display hooks and as a consequence we now have a general function that can display any valid HoloViews object in the notebook or return the HTML. This also happens to be exactly what you need for interact. You can import and use it as follows:

```python
import numpy as np
import holoviews as hv
from holoviews.ipython import display
from IPython.html.widgets import interact

def img_fn(fn, f):
    xs = np.linspace(-1*f, 1*f, 50)
    ys = np.linspace(-1*f, 1*f, 50)
    Xs, Ys = np.meshgrid(ys, xs)
    img = hv.Image(fn(xs)*fn(Ys))
    display(img+img.sample(y=0))
    
interact(img_fn, fn={'sin':np.sin, 'cos':np.cos, 'arctan':np.arctan}, f=(1, 10))
```

![image](https://cloud.githubusercontent.com/assets/1550771/8357678/1c5c6918-1b54-11e5-8ac1-f09f0dbb0618.png)

This is much better than continuously updating this ad hoc script we gave you. Now that we have this functionality I'll close the issue.

**Closed by philippjfr** 2015-06-25 15:07 UTC
Labels: feature

**Comment by basnijholt** [comment] 2015-06-25 15:14
Works like a charm!

**Comment by jbednar** [comment] 2015-06-25 18:15
Where will this be documented on the website? :-)

**Comment by jlstevens** [comment] 2015-06-25 18:57
As soon as someone has time. ;-)

**Comment by vascotenner** [comment] 2015-11-17 17:14
Notice that you have to use 
'''from holoviews.ipython import display'''

And not
'''from IPython.display import  display'''

**Comment by jlstevens** [comment] 2015-11-17 17:39
Yes. We extend ``display`` from ``IPython.display`` to be HoloViews aware. 

There should be no harm using ``holoviews.ipython.display`` anywhere you used the IPython version as the behavior for anything that isn't HoloViews should be unchanged. :-)

**Comment by philippjfr** [comment] 2015-11-17 19:40
Hmm, technically to say we extend it isn't true. Should the display function mirror the IPython.display.display functions behavior for non-holoviews types?

**Comment by jlstevens** [comment] 2015-11-17 20:25
So it doesn't work quite as I thought it did. Given that our version of display is in the ipython module, that means we have access to the IPython version of display. In which case shouldn't we simply extend it?

**Comment by philippjfr** [comment] 2015-11-17 20:36
That's what I was asking and I agree we should.
