### ISSUE TITLE
overlay default highlighted 

### ISSUE THREAD

**Issue by euacar** [ioam/holoviews#2809] opened 2018-06-18 23:33 UTC
After generating the html using overlay, I can click each group in the legend and de-highlight.
How do I set the options  so that every group is by default not selected, i.e., user clicks needed group to highlight rather than clicking each group to turn it off.

**Comment by ahuang11** [comment] 2018-06-25 17:07
I think this is a duplicate of https://github.com/ioam/holoviews/issues/2742

**Comment by philippjfr** [comment] 2018-06-25 18:57
Thanks for pointing that out @ahuang11. I'll close this one.

**Closed by philippjfr** 2018-06-25 18:57 UTC
