### ISSUE TITLE
fontsize doesn't work for Table/ItemTable

### ISSUE THREAD

**Issue by jordansamuels** [ioam/holoviews#1584] opened 2017-06-19 17:35 UTC
The fontsize appears to be ignored, e.g.

```
%%opts ItemTable [fontsize=24] Table[fontsize=24]
hv.ItemTable([('x',100)]) + hv.Table(pd.DataFrame({'hello': ['world']}))
```

**Comment by philippjfr** [comment] 2018-11-08 03:46
Duplicate of https://github.com/ioam/holoviews/issues/1742

**Closed by philippjfr** 2018-11-08 03:46 UTC
Labels: bug
