### ISSUE TITLE
No Legend for NdLayout of Distribution

### ISSUE THREAD

**Issue by ruoyu0088** [ioam/holoviews#1392] opened 2017-05-02 01:32 UTC
Here is the code 

```
a = np.random.normal(size=1000)
b = np.random.exponential(size=500)
df = pd.concat([pd.Series(a), pd.Series(b)], 
    keys=["normal", "exponential"], names=["dist"]).reset_index(0, name="value")

hv.Table(df, kdims=["dist"]).to.distribution(groupby=["dist"]).overlay()
```
and the output:

![image](https://cloud.githubusercontent.com/assets/826871/25600882/6ab5a6fe-2f22-11e7-8ff3-4e438b9aa231.png)

There is no legend, and shows some warning:

> /usr/local/share/miniconda3/lib/python3.5/site-packages/matplotlib/axes/_axes.py:545: UserWarning: No labelled objects found. Use label='...' kwarg on individual plots.
>   warnings.warn("No labelled objects found. "
>

**Comment by philippjfr** [comment] 2017-05-02 11:03
We will be reimplementing many of the statistical elements for version 2.0 (see https://github.com/ioam/holoviews/issues/1200) and the Distribution element will be one of the first and easiest to implement, as part of that we can fix this issue.

**Comment by philippjfr** [comment] 2017-12-08 17:57
This reimplementation has now happened, while the issue is still there it is now better addressed by: https://github.com/ioam/holoviews/issues/2118

**Closed by philippjfr** 2017-12-08 17:57 UTC
