### ISSUE TITLE
Colorscale of .hist() doesn't normalise

### ISSUE THREAD

**Issue by basnijholt** [ioam/holoviews#101] opened 2015-05-23 13:06 UTC
```python
%%opts Image(cmap='jet') {+framewise}
%output size=100 dpi=100
hv.HoloMap(data, key_dimensions=['file']).hist()
```
![download 2](https://cloud.githubusercontent.com/assets/6897215/7784202/3c1514aa-015d-11e5-97d3-da98dfdfe7ea.png)

```python
%%opts Image(cmap='jet') {+axiswise}
%output size=100 dpi=100
hv.HoloMap(data, key_dimensions=['file']).hist()
```
![download 3](https://cloud.githubusercontent.com/assets/6897215/7784203/512383f4-015d-11e5-8cf8-3e2a2766c7ef.png)

In making this example I found an other bug, related to https://github.com/ioam/holoviews/issues/93 I suppose.
```python
%%opts Image.framewise (cmap='jet') {+framewise} Image.axiswise (cmap='jet') {+axiswise}
%output size=100 dpi=100
hv.HoloMap(data, key_dimensions=['file'], group="framewise").hist() + hv.HoloMap(data, key_dimensions=['file'], group="axiswise").hist()
```
![download 1](https://cloud.githubusercontent.com/assets/6897215/7784199/22969a26-015d-11e5-9178-764e3684b71d.png)

**Comment by jlstevens** [comment] 2015-05-24 16:46
> In making this example I found an other bug, related to #93 I suppose.

That bug should be fixed now. Can you please confirm that part is now working for this example?

**Comment by basnijholt** [comment] 2015-05-24 17:14
@jlstevens behaviour is still exactly the same for that particular example.

**Comment by philippjfr** [comment] 2015-05-24 17:16
I'm on it, this shouldn't be too hard to fix. The code dates from before color ranges could be shared across plots but it should be fairly straightforward update and fix. Will hopefully have a fix very soon.

**Comment by philippjfr** [comment] 2015-05-24 19:35
The commits above include a fix to this issue and an update to the reference data because the same bug was actually evident in one of the examples in the Elements Tutorial. I'll close the issue now, please test it for yourself and reopen if necessary.

**Closed** 2015-05-24 19:35 UTC

**Comment by philippjfr** [comment] 2015-05-24 19:53
I just realized there was actually two bugs here and I only fixed the first one. Could you confirm whether your second example is fixed now too? The options fixes @jlstevens and I made should hopefully have addressed that.

**Comment by basnijholt** [comment] 2015-05-24 20:18
The first bug is fixed. But the options are still not working.

I mean this example:
```python
%%opts Image.framewise (cmap='jet') {+framewise} Image.axiswise (cmap='jet') {+axiswise}
%output size=100 dpi=100
hv.HoloMap(ims, key_dimensions=['file'], group="framewise").hist() + hv.HoloMap(ims, key_dimensions=['file'], group="axiswise").hist()
```

**Comment by jlstevens** [comment] 2015-05-24 23:56
We have spotted the problem: you are setting ``group="framewise"`` and ``group="axiswise"`` on the two HoloMaps (left and right) whereas the ``%%opts`` definition you have used is setting options on ``Images``, not ``HoloMaps``.

If you set the group value to 'framewise' in all the images on the left and to 'axiswise' for all the images on the right, then it will work. I realize this might be a bit awkard but there is one another approach:

```python
%%opts Image.framewise {+framewise} Image.axiswise {+axiswise}
from holoviews import Image, HoloMap
import numpy as np
ims = {i:Image(np.random.rand(10,10) * i) for i in range(1,10)}
(HoloMap(ims).map(lambda x: x.relabel(group='framewise')) 
+ HoloMap(ims).map(lambda x: x.relabel(group='axiswise')))
```

Unfortunately, this is a bit more awkward than I would like but it does work!

**Comment by jlstevens** [comment] 2015-05-25 00:00
This raises an important issue to consider: should setting the group on a ``HoloMap`` propagate that group to the elements *if* they haven't already been customized? What is only some elements have been customized, should that be an error? Is there any cases where the elements of a ``HoloMap`` will have groups different from the holomap itself?

I can see why you expected it to work the way you did so I am wondering if there is a sensible policy that works well in  general.

**Comment by jbednar** [comment] 2015-05-25 03:13
Automatically setting the group of the contained Elements when the Holomap's group is set seems like it would be surprising to me.  I can't think of a sensible policy that would be reasonable to apply in this case, though getting the behavior Bas wanted does seem awkward.

**Comment by jlstevens** [comment] 2015-05-25 12:21
> Automatically setting the group of the contained Elements when the Holomap's group is set seems like it would be surprising to me.

Right.

Philipp suggested a deep flag on the ``.relabel`` method but I am wary of that as you don't want to relabel everything to one group/label in a highly nested datastructure. That said, with a bit more control, I think it *could* work. Maybe something like:

```python
HoloMap(ims).relabel(group='framewise', levels=2)
```

Then the default is ``levels=1``, implementing the current behavior. I'm not quite sure if ``levels`` should index from 0 or 1 in this case. If it indexes from zero, it would mean 'extra levels' otherwise the level includes the top level object. 

I think this would be an improvement over having to define lambdas! Thoughts?

**Comment by basnijholt** [comment] 2015-05-25 12:53
I think the idea of having a ``dept`` parameter would be nice, where this also might be useful for is ``.select()``.

**Comment by philippjfr** [comment] 2015-05-25 13:04
I agree a ``depth`` or ``levels`` parameter to control the depth of renaming seems like a good idea. 

@basnijholt: ``.select`` has a more robust mechanism to determine what you want to apply the selection to. You can pass it a list of specs and the selection will only apply to the matches. For example let's say you have a HoloMap of Images:

```python
img_map.select([hv.Image], x=(0, 0.5))
```

This will apply the selection to all Image types. Valid specs include type.group.specs strings/tuples, types and functions. This let's you apply very specific selections, e.g.:

```python
img_map.select([lambda x: type(x) == hv.Image and x.range('x')[1] == 1.0], x=(0, 0.5))
```

This will only apply the selection on objects of type Image, with x-ranges above 1.0. Hope that makes sense.

**Comment by jlstevens** [comment] 2015-05-25 13:57
I vote for the name ``depth`` instead of ``levels``. 

The next question is whether ``depth=0`` by default  and I think that is correct. Obviously, if you are using ``relabel`` at all, you expect the object you are calling the method on to be relabeled. In that case ``depth=0``  means 'relabel this object but relabel no further'. 

This makes the most sense to me and I'll look into implementing this shortly.

**Comment by jlstevens** [comment] 2015-05-25 16:05
I've pushed the updated ``relabel`` method with support for the depth parameter in commit f89b89f.

It turns out that ``HoloMap`` already had a relabel that propagated to the elements so you could *already* have used relabel instead of my suggestion above! Anyway, I didn't expect this behavior which is why I suggested something else - the new depth parameter now makes propagation of labels/groups explicit and consistent.

I'll close this issue as soon as I can confirm the tests are passing.
