### ISSUE TITLE
X Axis name does not get consolidated

### ISSUE THREAD

**Issue by Berserker66** [ioam/holoviews#3172] opened 2018-11-12 16:33 UTC
![image](https://user-images.githubusercontent.com/3189725/48361014-d2c3c000-e6a0-11e8-81c6-7ac3c9be6488.png)

I'd like to have only one "Monat" under the final table and have the others refer to it.
According to some googling this is supposed to happen automatically (?), but it appears not.

The setup is identical to https://github.com/ioam/holoviews/issues/3171

However I've tried to help Holoviews by defining one Dimension:
months = hv.Dimension("month", label="Monat")
and then used that for all X-Axes. to no avail.

**Comment by philippjfr** [comment] 2018-11-12 16:42
Duplicate of https://github.com/ioam/holoviews/issues/2104. You could use a GridSpace or GridMatrix instead of a Layout for the time being, or manually disable the axes using ``.options(xaxis=None)`` on the plots you want to disable the axes for.

**Closed by philippjfr** 2018-11-12 16:42 UTC
