### ISSUE TITLE
holoviews   and  JupyterLab

### ISSUE THREAD

**Issue by maajdl** [ioam/holoviews#2212] opened 2017-12-18 07:47 UTC
Hello,

I just tried some holoviews graph with  JupyterLab.
I used a Jupyter Notebook that worked perfectly.
Using it from JupyterLab, nothing was displayed.

Would you have any suggestion?
Would that be a JupyterLab issue, or an Holoviews issue?

Thanks,

Michel

**Comment by jlstevens** [comment] 2017-12-18 09:57
We will be getting HoloViews working with JupyterLab once we figure out how to update the code using the Jupyterlab comms. As this issue is a duplicate of #687, I'll close this one and we can continue discussion there.

**Closed by jlstevens** 2017-12-18 09:57 UTC
