### ISSUE TITLE
Chart3D from Tutorials/Elements not working in example

### ISSUE THREAD

**Issue by basnijholt** [ioam/holoviews#90] opened 2015-05-19 09:58 UTC
I've tried 

```python
%load_ext holoviews.ipython
import numpy as np
from holoviews import Surface
```

```python
%%opts Surface [figure_size=125] (cmap='jet' rstride=20, cstride=2)
Surface(np.sin(np.linspace(0,100*np.pi*2,10000)).reshape(100,100))
```

and 

```python
%%opts Scatter3D [azimuth=40 elevation=20]
x,y = np.mgrid[-5:5, -5:5] * 0.1
heights = np.sin(x**2+y**2)
Scatter3D(zip(x.flat,y.flat,heights.flat))
```

both don't work

**Comment by jlstevens** [comment] 2015-05-19 12:02
Does the code generate a traceback? Or does nothing happen at all?

It is difficult to diagnose what is going wrong without knowing what happens when you run the code mentioned above.

**Comment by philippjfr** [comment] 2015-05-19 12:28
Yea I just checked and it's still working fine on my end and on the machine that builds the docs for us. I don't really think this is it, since I think matplotlib ships with the 3d toolkit now but could you try this import as well:

```python
from mpl_toolkits.mplot3d import Axes3D
```

A traceback would be helpful too.

**Comment by basnijholt** [comment] 2015-05-19 15:24
Ah, I thought it wouldn't work for anyone. But I tried on my own laptop and there it works.

```python
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/holoviews/ipython/display_hooks.py", line 212, in wrapped
    **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/holoviews/ipython/display_hooks.py", line 241, in element_display
    fig = Store.registry[element.__class__](element, **opts(element, size))()
  File "/usr/local/lib/python2.7/dist-packages/holoviews/plotting/element.py", line 132, in __init__
    uniform=uniform, **dict(params, **plot_opts))
  File "/usr/local/lib/python2.7/dist-packages/holoviews/plotting/plot.py", line 132, in __init__
    self.handles['axis'] = self._init_axis(axis)
  File "/usr/local/lib/python2.7/dist-packages/holoviews/plotting/plot.py", line 289, in _init_axis
    axis = fig.add_subplot(111, projection=self.projection)
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/figure.py", line 964, in add_subplot
    a = subplot_class_factory(projection_class)(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/axes/_subplots.py", line 78, in __init__
    self._axes_class.__init__(self, fig, self.figbox, **kwargs)
  File "/usr/lib/pymodules/python2.7/mpl_toolkits/mplot3d/axes3d.py", line 91, in __init__
    *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/axes/_base.py", line 437, in __init__
    self.cla()
  File "/usr/lib/pymodules/python2.7/mpl_toolkits/mplot3d/axes3d.py", line 1045, in cla
    Axes.cla(self)
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/axes/_base.py", line 908, in cla
    self.grid(self._gridOn, which=rcParams['axes.grid.which'])
  File "/usr/lib/pymodules/python2.7/mpl_toolkits/mplot3d/axes3d.py", line 1256, in grid
    self._draw_grid = maxes._string_to_bool(b)
AttributeError: 'module' object has no attribute '_string_to_bool'
:Surface   [x,y]   (z)
```


```from mpl_toolkits.mplot3d import Axes3D``` doesn't help.

**Comment by philippjfr** [comment] 2015-05-19 15:34
Have a look at [this Stackoverflow question](http://stackoverflow.com/questions/25383698/error-string-to-bool-in-mplot3d-workaround-found).

**Comment by philippjfr** [comment] 2015-05-19 17:02
Closing this as it is not a bug in HoloViews.

**Closed by philippjfr** 2015-05-19 17:02 UTC

**Comment by basnijholt** [comment] 2015-05-19 17:34
Of course, thanks, I'll try :)

**Comment by jlstevens** [comment] 2015-05-19 17:46
I wonder if there is some way we could check matplotlib installs before people try to use HoloViews features. I realize this is fanciful but if we could tell users to try something like:

```python
from holoviews.utils import test_matplotlib
test_matplotlib()
```

Then that would be a good way to know what is due to holoviews and what is due to the matplotlib install. Again, I realize this probably isn't feasible!
