### ISSUE TITLE
Deprecations for Matplotlib-3.0.0rc2

### ISSUE THREAD

**Issue by stonebig** [ioam/holoviews#2963] opened 2018-08-28 18:16 UTC
with matplotlib-3.0.0rc2, some annoying deprecation warning do arrive
![image](https://user-images.githubusercontent.com/4312421/44741951-ee3a1880-aafe-11e8-92c5-bb78d6228374.png)

apparently, holoviews still generates the now unwanted parameters.

https://github.com/ioam/holoviews/blob/63cfac9e104b134f9dcb7eb0f1b16196df16e2db/holoviews/plotting/mpl/plot.py#L133..L134

see:
- https://matplotlib.org/devdocs/api/next_api_changes/2018-05-15-AL.html
or 
- https://matplotlib.org/devdocs/api/api_changes.html

**Comment by jlstevens** [comment] 2018-08-29 11:26
Thanks for reporting this! 

It is good to have users report what is coming up in upcoming matplotlib versions as we use the stable releases for ourselves and for testing.

**Comment by stonebig** [comment] 2018-09-16 06:26
so you will test against matplotlib-3.0.0 (on Python 3.5+ branches), if it's released tomorrow ?

**Comment by philippjfr** [comment] 2018-09-17 11:04
I'll do my best.

**Comment by stonebig** [comment] 2018-09-23 06:09
matplotlib-3.0 final is out.

**Comment by philippjfr** [comment] 2018-09-23 11:35
Thanks, I'll try it now.

**Comment by philippjfr** [comment] 2018-09-23 11:51
Okay I also see those deprecation warnings:

```
/Users/philippjfr/miniconda/envs/anacondaviz/lib/python3.6/site-packages/matplotlib/__init__.py:846: MatplotlibDeprecationWarning: 
The text.latex.unicode rcparam was deprecated in Matplotlib 2.2 and will be removed in 3.1.
  "2.2", name=key, obj_type="rcparam", addendum=addendum)
/Users/philippjfr/miniconda/envs/anacondaviz/lib/python3.6/site-packages/matplotlib/__init__.py:855: MatplotlibDeprecationWarning: 
examples.directory is deprecated; in the future, examples will be found relative to the 'datapath' directory.
  "found relative to the 'datapath' directory.".format(key))
/Users/philippjfr/miniconda/envs/anacondaviz/lib/python3.6/site-packages/matplotlib/__init__.py:846: MatplotlibDeprecationWarning: 
The text.latex.unicode rcparam was deprecated in Matplotlib 2.2 and will be removed in 3.1.
  "2.2", name=key, obj_type="rcparam", addendum=addendum)
/Users/philippjfr/miniconda/envs/anacondaviz/lib/python3.6/site-packages/matplotlib/__init__.py:855: MatplotlibDeprecationWarning: 
examples.directory is deprecated; in the future, examples will be found relative to the 'datapath' directory.
  "found relative to the 'datapath' directory.".format(key))
```

But I can't figure out where they're coming from, we do load and ship a custom rc file but it specifies none of the options it's warning about.

**Comment by philippjfr** [comment] 2018-09-23 11:57
Nevermind I found it, the default rcparams in matplotlib still set these values. We use a context manager to temporarily override the options and when they are restored the warnings are generated.

**Comment by stonebig** [comment] 2018-10-06 13:27
reducing to my minimum I still have the issue... not sure where it's created
![image](https://user-images.githubusercontent.com/4312421/46571831-58ef3700-c97c-11e8-89a6-a2c3df27d19e.png)

**Comment by stonebig** [comment] 2018-10-06 13:34
don't know exactly how to set a
````
warnings.filterwarnings("ignore", category=mpl.cbook.MatplotlibDeprecationWarning)
èèèè

**Comment by stonebig** [comment] 2018-10-06 13:37
ok, workarounded in waiting of a better solution

````
import warnings
import matplotlib as mpl
# Holoviews
# for more example, see http://holoviews.org/Tutorials/index.html
import numpy as np
import holoviews as hv
hv.extension('matplotlib')
dots = np.linspace(-0.45, 0.45, 11)
fractal = hv.Image(image)

layouts = {y: (fractal * hv.Points(fractal.sample([(i,y) for i in dots])) +
               fractal.sample(y=y) )
            for y in np.linspace(0, 0.45,11)}
warnings.filterwarnings("ignore", category=mpl.cbook.MatplotlibDeprecationWarning)
hv.HoloMap(layouts, kdims=['Y']).collate().cols(2)
````

**Comment by philippjfr** [comment] 2018-10-06 14:52
I'll have another look, but I have mpl 3.0.0 and can't reproduce any warnings.

**Comment by philippjfr** [comment] 2018-10-06 14:56
Nevermind I can reproduce and I've got a fix.

**Comment by philippjfr** [comment] 2018-10-07 15:36
Merged that PR prematurely, still seeing those warnings.

**Comment by philippjfr** [comment] 2018-10-07 17:10
This one seems to have done it: https://github.com/ioam/holoviews/pull/3058

**Closed by philippjfr** 2018-10-07 17:10 UTC
Labels: mpl
