### ISSUE TITLE
The output of print is different to what is shown in the tutorial of holoveiws

### ISSUE THREAD

**Issue by pkmn99** [ioam/holoviews#1294] opened 2017-04-14 15:23 UTC
According the tutorial (introduction), the output "print(channels)" should give  
:Layout
   .Image.Red   :Image   [x,y]   (z)
   .Image.Green :Image   [x,y]   (G)
   .Image.Blue  :Image   [x,y]   (B)

But I can only get this output:
"Layout Layout00735"

Anyone know what is going on?

**Comment by jlstevens** [comment] 2017-04-14 16:24
Thanks for reporting this! Could you try the following:

```python
import holoviews as hv
layout = hv.Curve([1,2,3]) + hv.Curve([4,5,6])
print(layout)
print(hv.__version__)
```

I suspect it may come down to the HoloViews version but I would like to make sure.

**Comment by pkmn99** [comment] 2017-04-14 16:29
Thanks for your help. 
Here are what I get:
print(layout) only gives "Layout Layout00685"
print(hv.__version__) gives "1.6.2'

**Comment by jlstevens** [comment] 2017-04-14 16:56
The issue is that the tutorial reflects changes since 1.6.2 was released. If you are using conda, you can try our new release candidate for version 1.7 (which went live only a few minutes ago!):

```
conda install -c ioam/label/dev holoviews
```

That should make the print output match correctly.

**Comment by pkmn99** [comment] 2017-04-14 17:10
Yes, it works after updating to 1.7. Thanks!

**Comment by jlstevens** [comment] 2017-04-16 23:52
Ok great! 

Issue is now resolved, closing.

**Closed by jlstevens** 2017-04-16 23:52 UTC
