### ISSUE TITLE
New error with %load_ext holoviews.ipython

### ISSUE THREAD

**Issue by deep-introspection** [ioam/holoviews#144] opened 2015-06-11 07:49 UTC
The magic function `%load_ext holoviews.ipython` is now triggering a new error.
I have Python 2.7.10 with Anaconda 2.2.0 (x86_64) and have installed all the dependencies.
The current holoview version is the dev one but I got the same error with the stable version.
Here is the full error log:

    ---------------------------------------------------------------------------
    ImportError                               Traceback (most recent call last)
    <ipython-input-1-187c8bacc195> in <module>()
          3 import numpy as np
          4 
    ----> 5 get_ipython().magic(u'load_ext holoviews.ipython')

    /Users/XXX/anaconda/lib/python2.7/site-packages/IPython/core/interactiveshell.pyc in magic(self, arg_s)
       2305         magic_name, _, magic_arg_s = arg_s.partition(' ')
       2306         magic_name = magic_name.lstrip(prefilter.ESC_MAGIC)
    -> 2307         return self.run_line_magic(magic_name, magic_arg_s)
       2308 
       2309     #-------------------------------------------------------------------------

    /Users/XXX/anaconda/lib/python2.7/site-packages/IPython/core/interactiveshell.pyc in run_line_magic(self, magic_name, line)
       2226                 kwargs['local_ns'] = sys._getframe(stack_depth).f_locals
       2227             with self.builtin_trap:
    -> 2228                 result = fn(*args,**kwargs)
       2229             return result
       2230 

    /Users/XXX/anaconda/lib/python2.7/site-packages/IPython/core/magics/extension.pyc in load_ext(self, module_str)

    /Users/XXX/anaconda/lib/python2.7/site-packages/IPython/core/magic.pyc in <lambda>(f, *a, **k)
        191     # but it's overkill for just that one bit of state.
        192     def magic_deco(arg):
    --> 193         call = lambda f, *a, **k: f(*a, **k)
        194 
        195         if callable(arg):

    /Users/XXX/anaconda/lib/python2.7/site-packages/IPython/core/magics/extension.pyc in load_ext(self, module_str)
         61         if not module_str:
         62             raise UsageError('Missing module name.')
    ---> 63         res = self.shell.extension_manager.load_extension(module_str)
         64 
         65         if res == 'already loaded':

    /Users/XXX/anaconda/lib/python2.7/site-packages/IPython/core/extensions.pyc in load_extension(self, module_str)
         83             if module_str not in sys.modules:
         84                 with prepended_to_syspath(self.ipython_extension_dir):
    ---> 85                     __import__(module_str)
         86             mod = sys.modules[module_str]
         87             if self._call_load_ipython_extension(mod):

    /Users/XXX/anaconda/lib/python2.7/site-packages/holoviews/ipython/__init__.py in <module>()
          4 from ..element.comparison import ComparisonTestCase
          5 from ..interface.collector import Collector
    ----> 6 from .archive import notebook_archive
          7 from .magics import load_magics
          8 from .display_hooks import set_display_hooks, OutputMagic

    /Users/XXX/anaconda/lib/python2.7/site-packages/holoviews/ipython/archive.py in <module>()
         16 from ..core.io import FileArchive, Pickler
         17 from ..core.options import Store
    ---> 18 from ..plotting import HTML_TAGS, DEFAULT_RENDER_CLASS
         19 
         20 try:  # IPython 3

    /Users/XXX/anaconda/lib/python2.7/site-packages/holoviews/plotting/__init__.py in <module>()
         46 # Load the default renderer
         47 if DEFAULT_RENDERER=='matplotlib':
    ---> 48     from .mpl import *
         49 
         50 _public = list(set([_k for _k, _v in locals().items() if public(_v)]))

    ImportError: No module named mpl

**Comment by jlstevens** [comment] 2015-06-11 11:48
Hi!

Looking at your traceback, I am fairly sure you are working with the development version that is in flux right now. Make sure you fully uninstalled the development version and then try re-installing the stable version from pip.

We should also have a new stable pip version very soon for you to install to get all the latest improvements and features.

**Comment by jlstevens** [comment] 2015-06-12 17:29
Ah! I think I've realized the issue...

Did you try to ``pip install`` from GitHub? If so, the problem is that we forgot to update our ``setup.py`` after some recent refactoring. I'll tell you when this is fixed and thanks for reporting this!

**Comment by jlstevens** [comment] 2015-06-12 18:34
This issue should be fixed now -  if you ``pip install`` the dev version, you should be fine. 

I am still confused as to why you saw this error when try to use the stable version though...

**Comment by deep-introspection** [comment] 2015-06-13 06:18
It seems to work again. Thanks a lot!

**Closed** 2015-06-13 06:18 UTC
