### ISSUE TITLE
deprecation issue with matplotlib 1.5rc1

### ISSUE THREAD

**Issue by stonebig** [ioam/holoviews#274] opened 2015-09-26 12:30 UTC
with holoviews master of this 2015-09-26 morning + bokeh 0.10.0 + matplotlib1.5rc1;
````
from holoviews import *
%load_ext holoviews.ipython
fractal = Image(image)

((fractal * HLine(y=0.16)).hist() + fractal.sample(y=0.16))
````

gives
````
\lib\site-packages\matplotlib\__init__.py:872: UserWarning: axes.color_cycle is deprecated and replaced with axes.prop_cycle; please use the latter.
  warnings.warn(self.msg_depr % (key, alt_key))
\lib\site-packages\matplotlib\__init__.py:872: UserWarning: axes.color_cycle is deprecated and replaced with axes.prop_cycle; please use the latter.
  warnings.warn(self.msg_depr % (key, alt_key))
\lib\site-packages\matplotlib\__init__.py:892: UserWarning: axes.color_cycle is deprecated and replaced with axes.prop_cycle; please use the latter.
  warnings.warn(self.msg_depr % (key, alt_key))
````

**Comment by stonebig** [comment] 2015-09-26 12:32
then I have this, which may just be the eaxmple being to be changed ?:
````
The holoviews.ipython extension is already loaded. To reload it, use:
  %reload_ext holoviews.ipython

---------------------------------------------------------------------------
UnboundLocalError                         Traceback (most recent call last)
<ipython-input-8-879da5038b21> in <module>()
      3 fractal = Image(image)
      4 
----> 5 ((fractal * HLine(y=0.16)).hist() + fractal.sample(y=0.16))

D:\WinPythonQt5\basedir34\build\winpython-3.4.3.amd64Qt5build3\python-3.4.3.amd64\lib\site-packages\holoviews\core\overlay.py in hist(self, index, adjoin, **kwargs)
     50 
     51         hist_element = self.get(index).hist(adjoin=False, **kwargs)
---> 52         if not isinstance(dimension, list): dimension = [dimension]
     53         hists = []
     54         for idx, d in enumerate(dimension[::-1]):

UnboundLocalError: local variable 'dimension' referenced before assignment
````

**Comment by philippjfr** [comment] 2015-09-26 18:40
Thanks, I've just pushed a fix for the histograms, I'll have to look at that again. Hopefully I'll have some time to try out matplotlib 1.5 soon, so we can fix these changes. I'll probably have to do the same for Bokeh 0.10.0 at some point.

**Comment by stonebig** [comment] 2015-09-27 07:35
testing on seaborn, this `axes.color_cycle is deprecated and replaced with axes.prop_cycle`was the only warning coming from matplotlib 1.5rc1, so you should be ok https://github.com/mwaskom/seaborn/issues/711

I did the test on Bokeh 0.10.0, forgot to mention.

**Comment by stonebig** [comment] 2015-10-15 17:28
there is the simple patch:
'axes.color_cycle' per 'axes.prop_cycle'
then from time to time you find yourself sometimes with a 'cycle.Cycler' instead of a 'list'
````
type of is  <class 'list'>
type of is  <class 'cycler.Cycler'>
````

and you find yourself in his corner:
````
to_rgba: Invalid rgba arg "{'color': '#30A2DA'}"
length of rgba sequence should be either 3 or 4
````

 I did ugly patch for seaborn, but I don't guess how to do the same dark magic on holoviews
https://github.com/mwaskom/seaborn/pull/732

**Comment by philippjfr** [comment] 2015-10-15 17:44
Thanks, that's helpful. Hopefully I can look at it soon.

**Comment by stonebig** [comment] 2015-10-22 14:05
It would make a difference for me if you can have a simple fix on this before this october 24th week-end.

**Comment by philippjfr** [comment] 2015-10-22 14:32
I just tried it and couldn't reproduce the issue. I used the latest commit on matplotlib's GitHub, which version did you use?

**Comment by stonebig** [comment] 2015-10-22 14:59
a Matplotlib1.5rc2. Maybe there has been a fix in recent comits

I will retry with the Matplotlib 1.5rc3 which shoud be released tonight.

**Comment by stonebig** [comment] 2015-10-22 21:10
If I use holoviews master of now +  Matplotlib 1.5rc3, I have the shim warning `axes.color_cycle is deprecated and replaced with axes.prop_cycle`. Don't you ?

**Comment by philippjfr** [comment] 2015-10-22 21:58
On my machines those messages seem to get piped to standard output, so I didn't notice it in my console until I shut the server down. The only actual issue I see is that there is an ``axes.color_cycle`` definition in our rc file. I'll have to move it out and set it explicitly in ``plotting/mpl/__init__.py``. I'll try to get that done tonight.

**Comment by stonebig** [comment] 2015-10-23 16:39
Yes, I did experiment with a `default2.mplstyle` instead of a `default.mplstyle` when the Matplotlib version is 1.5, but then fell had on the nasty side effect described earlier.

**Comment by philippjfr** [comment] 2015-10-24 12:47
I'm running into some weird issues I can't even define this:

```
axes.prop_cycle: cycler('color', ['30A2DA', 'FC4F30', 'E5AE38', '6D904F', '8B8B8B'])
```

in the matplotlibrc without running into this:

```
/home/philippjfr/miniconda/envs/science/lib/python2.7/site-packages/matplotlib/__init__.py:1028: UserWarning: Illegal line #7
	"cycler('color', ['30A2DA', 'FC4F30', 'E5AE38', '6D904F', '8B8B8B'])
"
	in file "holoviews/plotting/mpl/./default>=1.5.mplstyle"
  warnings.warn('Illegal %s' % error_details)
```

Any idea what could be going on here? Using ``cycler('color', ['rgb'])`` does work but I still run into issues with the original error. Will have to do some more digging or ask for some guidance from the matplotlib guys.

**Comment by philippjfr** [comment] 2015-10-24 13:06
Okay I just solved it, defining separate mplstyles depending on the matplotlib version is the correct way to go. Handling the cycler objects in HoloViews  only has to be handled in one place, where we initialize our Cycle object with the default colors. One issue is that as long as you have a version of seaborn installed that's not patched with your fix, seaborn will define a ``color_cycle`` and a warning will be raised.

**Comment by stonebig** [comment] 2015-10-24 13:56
great !

**Comment by philippjfr** [comment] 2015-10-24 14:32
The thing is HoloViews doesn't use matplotlib color cycles directly, we handle cycling of various style properties ourselves so I didn't really have to do anything except defining a separate matplotlibrc for >=1.5 and then making sure that the one place where we do use it we handles both color_cycle and prop_cycle. I'll still have to think about handling any ``prop_cycle`` that's not just a color as currently you'll probably get weird interactions when you try to use them.

**Comment by stonebig** [comment] 2015-10-26 08:08
the official patch for seaborn just landed: https://github.com/mwaskom/seaborn/commit/b2e4b9f3f660158481327ba949f75e322bdcd76a

**Comment by philippjfr** [comment] 2015-10-26 12:52
Great thanks, sorry I haven't gotten around to this yet, was painting my living room over the weekend :) Looking at that patch it seems like that if no color ``prop_cycle`` is defined it'll still try to access the color_cycle, not sure if that is desired. I'll try to get my patch applied today as we'll be putting together an unofficial release for one of our projects today and this should probably be included.

**Comment by stonebig** [comment] 2015-10-26 13:09
Tom Augspurger is a regular pandas contributor. His taught is that if ever someone create a `prop_cycle` without color, we should fall back to `color_cycle` + shim warning.

**Comment by philippjfr** [comment] 2015-10-29 14:50
Pushed a fix in commit 18024db, following basically what seaborn did. Please let me know if that fix works for you, in which case I'll close this issue.

**Comment by stonebig** [comment] 2015-10-29 14:58
Well, I did apply exactly the seaborn fix 3 days ago, did my tests, published release candidates of Winpython.

Nobody complained. Issue is closed for me.

**Comment by philippjfr** [comment] 2015-10-29 15:00
Thanks!

**Closed** 2015-10-29 14:59 UTC

**Comment by psychemedia** [comment] 2015-11-04 15:28
Is the version of seaborn on pip with the matplotlib deprecation issues likely to be available sometime soon, or should I be installing seaborn from git for a bit?

Getting a report of the following on current seaborn installed from pip:

    import seaborn
    
    /usr/local/lib/python3.4/dist-packages/matplotlib/__init__.py:872: UserWarning: axes.color_cycle is deprecated and replaced with axes.prop_cycle; please use the latter.
      warnings.warn(self.msg_depr % (key, alt_key))

**Comment by philippjfr** [comment] 2015-11-04 15:30
Can't tell you about the seaborn release schedule but for now you'll have to install the dev version from git.

**Comment by stonebig** [comment] 2015-11-04 17:50
otherwise, download the zip file [here](http://sourceforge.net/projects/winpython/files/WinPython_Source/Do_It_Yourself/Winpython_2015-07/basedir34/packages.srcreq.zip/download), unpack it, and install the `seaborn-0.7.0.dev0-py2.py3-none-any.whl`wheel it contains:
