### ISSUE TITLE
Distance between rows when using .hist()

### ISSUE THREAD

**Issue by basnijholt** [ioam/holoviews#69] opened 2015-05-13 20:53 UTC
```python
(hv.Image(np.random.rand(25,25)).hist() + hv.Image(np.random.rand(25,25)).hist() + hv.Image(np.random.rand(25,25))).cols(2)
```

Gives me:
![download](https://cloud.githubusercontent.com/assets/6897215/7620846/c3a8c9b8-f9c2-11e4-8465-0f99fb64974b.png)

The second row is a bit too far from the first one.

**Comment by philippjfr** [comment] 2015-05-13 21:43
This one is a fairly major annoyance that stems from the figure size not being computed very accurately. We are planning a general overhaul of how aspects and plot sizes are computed to allow some more powerful ways to lay out your data. I don't think it's a huge job but it'll certainly require quite a bit of fiddling and testing. I may make a branch for this at some point soon, to explore how hard it'll be (I have a prototype somewhere).

For now all I can recommend is setting ``%%opts Layout [vspace=0]``.

**Comment by basnijholt** [comment] 2015-05-14 08:33
``%%opts Layout [vspace=0]`` helps, but not much.

I guess I'm stuck with editing the pictures by hand for now :)

**Comment by philippjfr** [comment] 2015-05-14 11:54
Oh no definitely don't want you to have to fiddle manually. I've finally fixed the bug which had caused errors when overriding the fig_inches plot option. While still fiddly you should now be able to adjust the space between plots like this:

```python
import holoviews as hv
import numpy as np

%load_ext holoviews.ipython
%opts Layout [fig_inches=(10,8)]
hv.Layout([hv.Image(np.random.rand(25,25)).hist() for i in range(4)]).cols(2)
```

Hopefully I'll still get around to implementing more robust sizing defaults soon though.

**Comment by basnijholt** [comment] 2015-05-14 12:28
This is great, thanks a lot for the fast work!

**Comment by philippjfr** [comment] 2015-05-19 02:57
I'm about to push my fix to this, which is a major change to how sizes and the layout of the Layout are computed. 

For the user here's a quick summary of what changed:

* ``fig_inches`` can now be a single value or a list/tuple. If it's the former it will provide the value the plotting code bases it's autocomputed plotting size on, which in turn depends on the container type, e.g. Layouts scale that value by the number and aspects of the Elements inside it. If the ``fig_inches`` is found to be a tuple or list, it will be assumed to have been explicitly set and applied as is (after scaling by fig_size).

* Layouts now support more elaborate arrangements. The arrangements can be specified via the aspect of each item in the Layout. The resulting Layouts are still in a Grid, i.e. you need to have the same number of subplots in each row or column, but are otherwise unrestricted. I've added an example of this in the [Containers Tutorial](ioam.github.io/holoviews/Tutorials/Containers.html), which should get updated by tomorrow around noon.

**Comment by jbednar** [comment] 2015-05-19 04:12
Sounds very promising.  Is there any hope of eventually allowing several small items to be grouped into a single grid cell of a Layout?  E.g. Jean-Luc is using some plots from Sit et. al that are very thin and wide, and it would be very useful to be able to stack 5 of them into a group, and put that group into a cell of a Layout along with other more square plots.  I guess maybe a GridSpace would work in that case, but in general one might want to group several plots that share only their aspect ratio, not arranged on a dimension.

**Comment by philippjfr** [comment] 2015-05-19 12:25
If I'm interpreting this correctly then no, there's currently no way to do that. I do have a plan for making arbitrary Layouts possible but that's no likely to see the light of day for a while. I do think the new Layouts are a considerable improvement over having a strictly uniformly sized cells in a Layout though.

**Comment by basnijholt** [comment] 2015-05-19 15:50
Now I'm getting this without any ``%%opts``
``(hv.Image(np.random.rand(25,25)).hist() + hv.Image(np.random.rand(25,25)).hist() + hv.Image(np.random.rand(25,25))).cols(2)``

```/usr/local/lib/python2.7/site-packages/matplotlib/font_manager.py:1282: UserWarning: findfont: Font family [u'DejaVu Sans'] not found. Falling back to Bitstream Vera Sans
  (prop.get_family(), self.defaultFamily[fontext]))
```
![download 16](https://cloud.githubusercontent.com/assets/6897215/7707311/70a8922a-fe4f-11e4-938d-ed46022f6e8a.png)

**Comment by philippjfr** [comment] 2015-05-19 16:00
Seems unrelated to this issue. Probably something to do with Jean-Lucs changes to font sizes in https://github.com/ioam/holoviews/issues/72.

**Comment by philippjfr** [comment] 2015-05-19 16:54
Just noticed there is a bug in the sizing code. Will push the fix soon. Still can't replicate the wrongly sized histograms though. Could you send me the output of?

```
import matplotlib
matplotlib.get_backend()
```

**Comment by basnijholt** [comment] 2015-05-19 17:31
I get: ``u'MacOSX'``

**Comment by basnijholt** [comment] 2015-05-19 17:38
When I try this on the hpc that I usually work on, it works fine though.

![download 17](https://cloud.githubusercontent.com/assets/6897215/7709606/90c63d82-fe5e-11e4-940b-d69180d27dd2.png)

Although the panel labels (A., B., etc.) are a bit close to the ticks.

**Comment by philippjfr** [comment] 2015-05-19 17:41
Could you pull the latest version of HoloViews and try again on both machines?

**Comment by jbednar** [comment] 2015-05-19 17:55
Sorry to hijack this issue! Here's an example of what I meant above:

![aspect](https://cloud.githubusercontent.com/assets/1695496/7709496/1634cf38-fe23-11e4-9a6a-b5177cd61247.png)

The example in C is model output, and I'd like to put the corresponding experimental data (which looks just like it), just above or below what's in C, without changing the overall size or layout of the figure.  A mockup: 

![aspect2](https://cloud.githubusercontent.com/assets/1695496/7709648/3583c654-fe24-11e4-9bc7-737313010e71.png)

I can imagine creating some dummy dimension "Model" vs. "Experiment", then putting C and D's Elements into it, and creating a GridSpace to show that dimension as the new C, but (a) I don't know if that would work, and (b) it seems like a big pain.  

What I *don't* want to do is to end up with an overall 3x2 grid, as in this mockup:

![aspect3](https://cloud.githubusercontent.com/assets/1695496/7709762/d92708ca-fe24-11e4-8286-60803a66e1f1.png)

Apart from making the figure larger and more unwieldy, this approach (which is what I assume Layout will do normally), doesn't let me line up C and D on the same timebase.  Stacking vertically emphasizes comparisons at each time, which is what's appropriate in this particular case.  Swapping plots D and E would line up C and D, but I think they'd be very far apart from each other and there would be lots of wasted space.  So I  don't see how to get the appropriate organization from a Layout in this case (or in many similar cases where different plots have different sizes or aspect ratios).

**Comment by philippjfr** [comment] 2015-05-19 18:07
Thanks for the more detailed description. As I said, what you want in that example is not currently possible. The second example with the 3x2 grid now finally is possible. I think that is a reasonable step forward even if, as I keep emphasizing, it doesn't yet allow for arbitrary Layouts. The current grid based approach was a simple extension of our existing implementation, what you're proposing is a complete redesign of LayoutPlot, which we might target for the next minor (1.2) or major release (2.0), depending how initial prototyping goes.

If you have any concrete proposals or requests on how it should work or particular features it should support please, or simply want a place to gather our thoughts on the problem please open a new issue as this one is assigned as a milestone for 1.1.1, and it certainly won't be implemented for this release.

**Comment by basnijholt** [comment] 2015-05-19 18:18
I've updated both and the behaviour is still the same.

**Comment by philippjfr** [comment] 2015-05-19 18:24
That's very odd. The first issue (large histograms) is backend related, which should have been adddressed by sticking ``backend: agg`` in our matplotlibrc. The second issue (large space) was a bug in the sizing code which I also fixed.

Here's what it looks like on my end:

![image](https://cloud.githubusercontent.com/assets/1550771/7710514/5b392d48-fe5c-11e4-8eb9-80f7873245be.png)

Could you print the HoloViews version and matplotlib backend for me again?

```
import holoviews as hv
import matplotlib
print matplotlib.get_backend()
print hv.__version__

**Comment by basnijholt** [comment] 2015-05-19 18:29
```python
In [2]:
import matplotlib 
matplotlib.get_backend()

Out[2]:
u'MacOSX'

In [6]:
import holoviews as hv
import matplotlib
print matplotlib.get_backend()
print hv.__version__ 
agg
1.1.0
```

**Comment by basnijholt** [comment] 2015-05-19 19:09
One other thing that actually belonged in https://github.com/ioam/holoviews/issues/75 but which is closed.


```python
hv.HoloMap(bands_tilt, key_dimensions=[hv.Dimension('$B_y$', unit='T')]).select(Energy=(-3, 3), Momentum=(-0.6, 0.6)) + orb['sphere'][0.5, 0.5]
```
![Uploading Screen Shot 2015-05-19 at 21.06.28.png…]()
but with 
```python
%%opts Layout [fig_inches=(10,5)]
```
it gives: 
![screen shot 2015-05-19 at 21 09 02](https://cloud.githubusercontent.com/assets/6897215/7711492/4d925cc8-fe6b-11e4-89f4-8660285810ee.png)

**Comment by philippjfr** [comment] 2015-05-19 19:20
Can't reproduce that problem anymore either. Please make entirely sure it's using the absolutely latest dev version of HoloViews. What's your ``git log`` output and have you definitely restarted your kernel?

**Comment by basnijholt** [comment] 2015-05-19 19:25
I deleted my post 2 minutes after I posted it, sorry. Saw that I had some other setting somewhere.

And for the histograms, I have definitely restarted the kernel and IPython notebook completely, also the latest update for sure.

**Comment by philippjfr** [comment] 2015-05-19 19:27
This output:

```python
import holoviews as hv
import matplotlib
print matplotlib.get_backend()
print hv.__version__ 
```

```
agg
1.1.0
```

indicates you're using the PyPI version of 1.1.0.  Is it possible that it's somehow using the wrong HoloViews installation?

**Comment by basnijholt** [comment] 2015-05-19 19:30
Installed holoviews again,.

This is what I do:
```
pip uninstall holoviews
cd /path/to/holoviews
git pull
pip install .
```

**Comment by philippjfr** [comment] 2015-05-19 19:33
If you do:

```python
import holoviews
holoviews??
```

in a notebook cell, does it point to the correct directory?

**Comment by basnijholt** [comment] 2015-05-19 19:34
```python
Type:        module
String form: <module 'holoviews' from '/usr/local/lib/python2.7/site-packages/holoviews/__init__.pyc'>
File:        /usr/local/lib/python2.7/site-packages/holoviews/__init__.py
```

**Comment by philippjfr** [comment] 2015-05-19 19:37
Sorry for all this. Could you now do:

```python
!less /usr/local/lib/python2.7/site-packages/holoviews/holoviews/plotting/plot.py
```

Then search for ``def _compute_gridspec`` and reproduce that method here.

**Comment by basnijholt** [comment] 2015-05-19 19:40
That directory doesn't exist, ``/usr/local/lib/python2.7/site-packages/holoviews/plotting`` does.

And this is ``def _compute_gridspec``:

```python 
def _compute_gridspec(self, layout):
        """
        Computes the tallest and widest cell for each row and column
        by examining the Layouts in the GridSpace. The GridSpec is then
        instantiated and the LayoutPlots are configured with the
        appropriate embedded layout_types. The first element of the
        returned tuple is a dictionary of all the LayoutPlots indexed
        by row and column. The second dictionary in the tuple supplies
        the grid indicies needed to instantiate the axes for each
        LayoutPlot.
        """
        layout_items = layout.grid_items()
        layout_dimensions = layout.key_dimensions if isinstance(layout, NdLayout) else None

        layouts = {}
        row_heightratios, col_widthratios, col_aspects = {}, {}, defaultdict(lambda: [0, 0])
        for (r, c) in self.coords:
            # Get view at layout position and wrap in AdjointLayout
            _, view = layout_items.get((r, c), (None, None))
            layout_view = view if isinstance(view, AdjointLayout) else AdjointLayout([view])
            layouts[(r, c)] = layout_view

            main = layout_view.main
            main = main.last if isinstance(main, HoloMap) else main
            if main and self.apply_aspects:
                main_aspect = Store.lookup_options(main, 'plot').options.get('aspect', 1)
            else:
                main_aspect = 1

            # Compute shape of AdjointLayout element
            layout_lens = {1:'Single', 2:'Dual', 3:'Triple'}
            layout_type = layout_lens[len(layout_view)]
            if layout_type in ['Dual', 'Triple']:
                aspect = [main_aspect, 0.25]
            else:
                aspect = [main_aspect, 0]
            width_ratios = AdjointLayoutPlot.layout_dict[layout_type]['width_ratios'][:]
            height_ratios = AdjointLayoutPlot.layout_dict[layout_type]['height_ratios'][:]
            if not isinstance(main_aspect, (basestring, type(None))):
                width_ratios[0] = (width_ratios[0] * main_aspect)
                height_ratios[0] = (height_ratios[0] * 1./main_aspect)
            layout_shape = (len(width_ratios), len(height_ratios))

            # For each row and column record the width and height ratios
            # of the LayoutPlot with the most horizontal or vertical splits
            # and largest aspect
            if layout_shape[1] > row_heightratios.get(r, (0, None))[0]:
                row_heightratios[r] = [layout_shape[1], height_ratios]
            if layout_type == 'Triple':
                if height_ratios[1] > row_heightratios[r][1][1]:
                    row_heightratios[r][1][1] = height_ratios[1]
            elif height_ratios[0] > row_heightratios[r][1][0]:
                row_heightratios[r][1][0] = height_ratios[0]

            if layout_shape[0] > col_widthratios.get(c, (0, None))[0]:
                col_widthratios[c] = (layout_shape[0], width_ratios)
            if width_ratios[0] > col_widthratios[c][1][0]:
                col_widthratios[c][1][0] = width_ratios[0]

            if aspect[0] > col_aspects.get(c, [0])[0]:
                col_aspects[c][0] = aspect[0]
            if aspect[1] > col_aspects.get(c, [0, 0])[1]:
                col_aspects[c][1] = aspect[1]

        # In order of row/column collect the largest width and height ratios
        height_ratios = [v[1] for k, v in sorted(row_heightratios.items())]
        width_ratios = [v[1] for k, v in sorted(col_widthratios.items())]
        aspect_ratios = [v for k, v in sorted(col_aspects.items())]
        # Compute the number of rows and cols
        cols = np.sum([len(wr) for wr in width_ratios])
        rows = np.sum([len(hr) for hr in height_ratios])
        # Flatten the width and height ratio lists
        wr_list = [wr for wrs in width_ratios for wr in wrs]
        hr_list = [hr for hrs in height_ratios for hr in hrs]
        if not isinstance(self.fig_inches, (tuple, list)):
            aspect_list = [ar for ars in aspect_ratios for ar in ars]
            xinches = self.fig_inches * sum(aspect_list)
            yinches = xinches/(sum(aspect_list)/sum([min(hr_list)/float(h) for h in hr_list]))
            self.handles['fig'].set_size_inches([xinches, yinches])

        self.gs = gridspec.GridSpec(rows, cols,
                                    width_ratios=wr_list,
                                    height_ratios=hr_list,
                                    wspace=self.hspace,
                                    hspace=self.vspace)

        # Situate all the Layouts in the grid and compute the gridspec
        # indices for all the axes required by each LayoutPlot.
        gidx = 0
        collapsed_layout = layout.clone(shared_data=False, id=layout.id)
        frame_ranges = self.compute_ranges(layout, None, None)
        frame_ranges = OrderedDict([(key, self.compute_ranges(layout, key, frame_ranges))
                                    for key in self.keys])
        layout_subplots, layout_axes = {}, {}
        for num, (r, c) in enumerate(self.coords):
            # Compute the layout type from shape
            wsplits = len(width_ratios[c])
            hsplits = len(height_ratios[r])
            if (wsplits, hsplits) == (1,1):
                layout_type = 'Single'
            elif (wsplits, hsplits) == (2,1):
                layout_type = 'Dual'
            elif (wsplits, hsplits) == (1,2):
                layout_type = 'Embedded Dual'
            elif (wsplits, hsplits) == (2,2):
                layout_type = 'Triple'

            # Get the AdjoinLayout at the specified coordinate
            view = layouts[(r, c)]
            positions = AdjointLayoutPlot.layout_dict[layout_type]['positions']

            # Create temporary subplots to get projections types
            # to create the correct subaxes for all plots in the layout
            _, _, projs = self._create_subplots(layouts[(r, c)], positions,
                                                None, frame_ranges, create=False)
            gidx, gsinds = self.grid_situate(gidx, layout_type, cols)

            layout_key, _ = layout_items.get((r, c), (None, None))
            if isinstance(layout, NdLayout) and layout_key:
                layout_dimensions = OrderedDict(zip(layout_dimensions, layout_key))

            # Generate the axes and create the subplots with the appropriate
            # axis objects
            with matplotlib.rc_context(rc=self.fig_rcparams):
                subaxes = [plt.subplot(self.gs[ind], projection=proj)
                           for ind, proj in zip(gsinds, projs)]
                subplots, adjoint_layout, _ = self._create_subplots(layouts[(r, c)], positions,
                                                                layout_dimensions, frame_ranges,
                                                                dict(zip(positions, subaxes)),
                                                                num=num+1)
            layout_axes[(r, c)] = subaxes

            # Generate the AdjointLayoutsPlot which will coordinate
            # plotting of AdjointLayouts in the larger grid
            plotopts = Store.lookup_options(view, 'plot').options
            layout_plot = AdjointLayoutPlot(adjoint_layout, layout_type, subaxes, subplots,
                                            figure=self.handles['fig'], **plotopts)
            layout_subplots[(r, c)] = layout_plot
            if layout_key:
                collapsed_layout[layout_key] = adjoint_layout

        if self.show_title and len(self.coords) > 1:
            title = self.handles['fig'].suptitle('', **self._fontsize('title'))
            self.handles['title'] = title

        return layout_subplots, layout_axes, collapsed_layout
```

**Comment by philippjfr** [comment] 2015-05-19 19:54
Thanks, that's definitely the correct version and I get why ``holoviews.__version__`` is wrong now too but I still can't reproduce the two bugs you reported, very strange.

**Comment by philippjfr** [comment] 2015-05-19 20:01
Just to summarize, you're seeing two bugs.

1. Large histograms on your laptop, which are usually caused by the backend.
2. Too much vertical space between plots with SideHistograms on your hpc, which I (and @jlstevens) cannot reproduce. 

Is that correct?

**Comment by basnijholt** [comment] 2015-05-19 20:06
No only the first one.

hpc:
![download 18](https://cloud.githubusercontent.com/assets/6897215/7712698/42826758-fe73-11e4-91bb-1fc6f1d330b1.png)

laptop:
![download 19](https://cloud.githubusercontent.com/assets/6897215/7712704/476857f0-fe73-11e4-8a75-e46b00edf722.png)

**Comment by philippjfr** [comment] 2015-05-19 20:22
Ah, okay good. Does the issue on your laptop persist if you run:

```python
import matplotlib.pyplot as plt
plt.switch_backend('agg')
```

**Comment by basnijholt** [comment] 2015-05-19 20:28
That worked!

I do have 
```
cat ~/.matplotlibrc
backend: agg
```

**Comment by jlstevens** [comment] 2015-05-19 20:59
I'm not *entirely* in favour of this idea but this might be an argument for a ``holoviews.rc`` file. 

I don't trust matplotlib *at all* when it comes to switching backends. Instead of a matplotlib rc, I might prefer a general rc file which by default just has:

```python
import matplotlib.pyplot as plt
plt.switch_backend('agg')
```

This would also be a good place for people to put their global preferences, e.g ``rc_params`` on the ``Plot`` class. Thoughts?

**Comment by basnijholt** [comment] 2015-05-19 21:30
For me personally that would be great.

I was on a Microsoft numerics conference the last couple of days and heard a lot of people complaining about the absence of plotting templates in any language except for LaTeX (which is horrible to work with).

This would be something in that direction.

**Comment by philippjfr** [comment] 2015-05-20 03:14
Great, hopefully we'll be adding that in the next couple of days. The subject of this issue seems resolved so I'll close it again.

**Closed by philippjfr** 2015-05-20 03:14 UTC

**Comment by jbednar** [comment] 2015-05-20 04:19
It would be good to explain the reasons for not chaining the rc files, so that there is a record here.

**Comment by jlstevens** [comment] 2015-05-21 17:33
> It would be good to explain the reasons for not chaining the rc files, so that there is a record here.

In short, because avoiding chaining simplifies things for us and the user can achieve chaining themselves if they want to. The ``holoviews.rc`` is run with ``execfile`` and the user can easily use that as entry point to execute more code in other files (either via imports or probably more consistently,  additional calls to ``execfile``).

**Comment by basnijholt** [comment] 2015-05-21 17:35
Is this ``holoviews.rc`` file going to make sure that ``agg`` is always selected as a backend?

And thus I don't have to set:
```python
import matplotlib.pyplot as plt
plt.switch_backend('agg')
```
?

**Comment by jlstevens** [comment] 2015-05-21 17:39
Well, the way I am implementing it, that will be the default behavior *without* an rc file, so yes, you'll be able to get rid of that.

You will be able to use the ``holoviews.rc`` file to switch the backend to something *other* than 'agg' if desired, although that is  not really recommended for the reasons you discovered!
