### ISSUE TITLE
TypeError: 'odict_values' object does not support indexing

### ISSUE THREAD

**Issue by brianmingus** [ioam/holoviews#1032] opened 2016-12-31 00:35 UTC
When running this example: http://philippjfr.com/work/work-in-progress/t-sne-tutorial/

We get this error: https://gist.github.com/brianmingus/ce9ca41f684d41ec53579381f61a6b24

Which appears to be code that can't work in Python 3.

**Comment by philippjfr** [comment] 2016-12-31 13:11
I believe this has been fixed on master. You can either get it straight from GitHub or install the latest dev release using:

```
conda install -c ioam/label/dev holoviews
```

Hopefully we'll have a new release soon.

**Comment by philippjfr** [comment] 2017-01-04 13:16
Please report back if that worked for you. I'll close since the issue is already fixed in master. Please reopen if you encounter further issues.

**Closed by philippjfr** 2017-01-04 13:16 UTC
