### ISSUE TITLE
Issue with groupby and conversion interface

### ISSUE THREAD

**Issue by bjlittle** [ioam/holoviews#647] opened 2016-04-27 13:18 UTC
Using this cube, there are issues using groupby and conversion:

```
air_temperature / (K)               (time: 2; model_level_number: 70; grid_latitude: 810; grid_longitude: 621)
     Dimension coordinates:
          time                           x                      -                  -                    -
          model_level_number             -                      x                  -                    -
          grid_latitude                  -                      -                  x                    -
          grid_longitude                 -                      -                  -                    x
     Auxiliary coordinates:
          forecast_period                x                      -                  -                    -
          level_height                   -                      x                  -                    -
          sigma                          -                      x                  -                    -
     Scalar coordinates:
          forecast_reference_time: 2016-02-07 21:00:00
     Attributes:
          Conventions: CF-1.5
          STASH: m01s16i004
          source: Data from Met Office Unified Model
          um_version: 10.1
```

Trying this:

```python
cube = hv.Dataset(air_temperature_cube)
cube.to.curve('model_level_number', dynamic=True)
```

Shows the first frame correctly but afterwards matplotlib complains because the two input arrays have very different lengths. Looking at the sliced cube, all the dimensions are still there.

The same issue exists when using groupby:

```
cube = hv.Dataset(air_temperature_cube)
cube.groupby(['time', 'grid_longitude', 'grid_latitude'], group_type=hv.Curve, dynamic=True)
```

Or the explicit conversion syntax:

```
cube = hv.Dataset(air_temperature_cube)
cube.to(hv.Curve, ['model_level_number'], dynamic=True)
```
What is really weird is how the first frame looks right but then it breaks!

**Comment by philippjfr** [comment] 2016-04-27 14:02
I don't have access to the same cube here so I can't reproduce it. Could you print the summary of one of the cubes that are extracted using the groupby?

**Comment by bjlittle** [comment] 2016-04-27 15:06
Here is an example of a Curve generated by the groupby for one of the keys that fails:

```
air_temperature / (K)               (time: 2; model_level_number: 70; grid_latitude: 810; grid_longitude: 621)
     Dimension coordinates:
          time                           x                      -                  -                    -
          model_level_number             -                      x                  -                    -
          grid_latitude                  -                      -                  x                    -
          grid_longitude                 -                      -                  -                    x
     Auxiliary coordinates:
          forecast_period                x                      -                  -                    -
          level_height                   -                      x                  -                    -
          sigma                          -                      x                  -                    -
     Scalar coordinates:
          forecast_reference_time: 2016-02-07 21:00:00
     Attributes:
          Conventions: CF-1.5
          STASH: m01s16i004
          source: Data from Met Office Unified Model
          um_version: 10.1
```

**Comment by philippjfr** [comment] 2016-04-27 15:09
That is indeed very odd, that looks like the extract call completely failed. This is the function that applies the dynamic groupby:

```python
def load_subset(*args):
    constraint = iris.Constraint(**dict(zip(constraints, args)))
    return dataset.clone(dataset.data.extract(constraint),
                          new_type=group_type,
                          **dict(kwargs, kdims=slice_dims))
```

I'd suggest placing a print statement on line 165 of ``holoviews.core.data.iris`` to see if the constraint is malformed in some way.

**Comment by bjlittle** [comment] 2016-04-27 15:21
```python
{u'grid_latitude': -3.7707, u'grid_longitude': 354.92898559570312, u'time': 404168.0}
```

Hmm I wonder if the constraint is failing due to floating point equivalence issues ...

**Comment by marqh** [comment] 2016-04-27 15:22
```
import iris
import holoviews as hv
import geoviews as gv
import cartopy
cubes = iris.load(['/data/local/itmh/ukvTigge7Feb16/prodm_op_ukv_20160207_21_000.pp', '/data/local/itmh/ukvTigge7Feb16/prodm_op_ukv_20160207_21_002.pp'])
airp = hv.Dataset(cubes[4])
airp.to.image(['grid_longitude', 'model_level_number'], dynamic=True)
```

seems to exhibit the same behaviour.  The first frame is loaded and rendered, but subsequent frames do not update

web console has numerous errors

e.g.
```
"Could not call widget save state callback." " -- " Exception { message: "", result: 2152857611, name: "NS_ERROR_FILE_CORRUPTED", filename: 
```

**Comment by philippjfr** [comment] 2016-04-27 15:23
>Hmm I wonder if the constraint is failing due to floating point equivalence issues ...

It definitely shouldn't since it's using the exact values held by the Cube coordinates, which is presumably what the extraction is comparing against.

**Comment by philippjfr** [comment] 2016-04-27 15:25
>web console has numerous errors

"Could not call widget save state callback." " -- " Exception { message: "", result: 2152857611, name: "NS_ERROR_FILE_CORRUPTED", filename: 

That looks to be a ipywidgets error, so shouldn't be related.

**Comment by marqh** [comment] 2016-04-27 15:27
```
airp.to.image(['grid_longitude', 'time'], dynamic=True)
```

also exhibits the same problem, when looking for model level numbers, which are integers, so i don't think this is just a floating point issue

**Comment by marqh** [comment] 2016-04-27 15:28
we get errors such as
```
"Warning: HoloViews callback returned unexpected data for key: (" "[36,-3.7706999779]" ") with the following content:" Object { ename: "ValueError", evalue: "Cube must be 2-dimensional. Got 4 d…", traceback: Array[14] }
```

**Comment by philippjfr** [comment] 2016-04-27 15:28
I'm not sure what to suggest really, the constraint seems to be formed correctly. So from my perspective it's something going wrong in the iris extract call.

**Comment by philippjfr** [comment] 2016-04-27 15:32
>"Warning: HoloViews callback returned unexpected data for key: (" "[36,-3.7706999779]" ") with the following content:" Object { ename: "ValueError", evalue: "Cube must be 2-dimensional. Got 4 d…", traceback: Array[14] }

That again looks like the extract call failed for some reason and the cube was not correctly sliced down to a 2D view.

**Comment by bjlittle** [comment] 2016-04-27 15:33
```python
air_temperature / (K)               (model_level_number: 70)
     Dimension coordinates:
          model_level_number                           x
     Auxiliary coordinates:
          level_height                                 x
          sigma                                        x
     Scalar coordinates:
          forecast_period: 35.0 hours
          forecast_reference_time: 2016-02-07 21:00:00
          grid_latitude: -3.7707 degrees
          grid_longitude: 354.928985596 degrees
          time: 2016-02-09 08:00:00.000006
     Attributes:
          Conventions: CF-1.5
          STASH: m01s16i004
          source: Data from Met Office Unified Model
          um_version: 10.1
```

Okay, the first constraint on the cube works, so it's **not** fp accuracy ... certainly not for the first call to groupby.

But then moving the sliders doesn't update the notebook output with the print statement for the **next** constraint ... it's not getting that far in groupby.

**Comment by jbednar** [comment] 2016-04-27 15:34
How would one debug that?  Is there a way to figure out what the groupby is requesting from Iris?

**Comment by philippjfr** [comment] 2016-04-27 15:34
>But then moving the sliders doesn't update the notebook output with the print statement for the next constraint ... it's not getting that far in groupby.

The prints for subsequent call will never end in the notebook since Javascript swallows them. They will show up as error messages in the JS console (as those shown above).

**Comment by jbednar** [comment] 2016-04-27 15:35
cu

**Comment by philippjfr** [comment] 2016-04-27 15:37
The easiest thing to do is simply to explicitly request values from the DynamicMap by constructing the keys manually, rather than querying them via the widgets.

**Comment by philippjfr** [comment] 2016-04-27 15:43
Could you prepare a small-(ish) cube that reproduces this issue which I could download somewhere?

**Comment by bjlittle** [comment] 2016-04-27 15:44
Yeah, best move really. You need to be able to reproduce this ...

**Comment by philippjfr** [comment] 2016-04-27 15:45
Just tried with ``prodm_op_ukv_20160207_21_022.pp`` (which is the only file I have locally) and couldn't reproduce the problem.

**Comment by philippjfr** [comment] 2016-04-27 15:54
>Just curious; is there a way to grab messages to the Javascript console and display them in a notebook? Seems like a common thing to want to do.

Could write a little bit of JS to grab messages from the console and display them somehow, but for our widgets it might be more appropriate of finding a different, less hidden way to display the error messages.

**Comment by jbednar** [comment] 2016-04-27 16:01
I was thinking some easy-to-enable way to turn a "debug mode" on.  I know
how to find the messages deep in the JS console now, but certainly didn't
always...

Jim

**Comment by bjlittle** [comment] 2016-04-27 16:23
@philippjfr Okay, took a little bit of grubbing around, but I've found a dataset that reproduces this problem.

It's in our SciTools test-data https://github.com/SciTools/iris-test-data/blob/master/test_data/NetCDF/rotated/xyt/small_rotPole_precipitation.nc

```python
import os
fname = os.path.join(iris.config.TEST_DATA_DIR, 'NetCDF', 'rotated', 'xyt', 'small_rotPole_precipitation.nc')
cube = iris.load(fname)[0]
tcube = hv.Dataset(cube)
tcube.to.curve(['time'], dynamic=True)
```

Good luck!

I don't know if this is relevant, but this cube is also `grid_latitude` and `grid_longitude`. I've seen other datasets working, but they're `latitude', 'longitude` ... might be a thing, might not :smile:

**Comment by philippjfr** [comment] 2016-04-27 16:27
Thanks @bjlittle I can reproduce it now.

**Comment by philippjfr** [comment] 2016-04-27 16:30
I've figured it out now, the extract method returns ``None`` for pretty much all conditions I could find. Since the groupby uses ``clone`` and supplying None to clone just leaves the existing data in place the data is wrong whenever an extract fails.

**Comment by bjlittle** [comment] 2016-04-27 16:32
If `cube.extract` is returning `None` then the constraint has failed. Iris can't find data that matches.

Hmmm kinda going back to my original thoughts on floating point accuracy :scream:

**Comment by philippjfr** [comment] 2016-04-27 16:35
>Hmmm kinda going back to my original thoughts on floating point accuracy

Yes, that seems to be it. The widgets are truncating the precision and then the lookup fails. I'll have to think about what we can do about it. You think a fuzzy match at about 8 decimal places is safe?

**Comment by marqh** [comment] 2016-04-27 16:40
we have a comment about inequalities in our user guide for floating points:
http://scitools.org.uk/iris/docs/latest/userguide/subsetting_a_cube.html#cube-extraction

**Comment by philippjfr** [comment] 2016-04-27 16:43
Thanks, I was aware of that. The widgets truncate precision to 10 decimal places, beyond that Python and JS do not have matching precision. I'm just wondering if it's safe to apply fuzzy matching in general.

**Comment by philippjfr** [comment] 2016-04-27 17:41
I've created a PR using which will match values with a precision of 5 decimal places, which is pretty poor. You can use it as a temporary workaround but I'll investigate how hard it would be to work with indices instead.

**Comment by philippjfr** [comment] 2016-04-27 18:47
I've now implemented a fix that makes it work by index bypassing the issue entirely. @jlstevens Please review.

**Comment by jlstevens** [comment] 2016-04-27 19:00
Looks good and I'll be happy to merge it shortly. Working by index is definitely the right approach here and I'm glad it only takes a very lines to fix.

**Comment by philippjfr** [comment] 2016-04-28 09:03
The PR with the fix has been merged now. Please reopen if you encounter any more issues.

**Closed by philippjfr** 2016-04-28 09:03 UTC
