### ISSUE TITLE
Line charts using bokeh backend has white bar overlaid in corner

### ISSUE THREAD

**Issue by canavandl** [ioam/holoviews#299] opened 2015-11-23 19:34 UTC
Using the bokeh backend for line charts (other types not investigated), there is a white bar in the upper right corner (presumably an empty legend) that is overlaid on the lines/grid.

<img width="265" alt="screen shot 2015-11-23 at 1 31 32 pm" src="https://cloud.githubusercontent.com/assets/2198981/11347378/c8c2881e-91e6-11e5-974c-a813ddd4beaf.png">

holoviews 1.4.1a1
python 2.7

**Comment by philippjfr** [comment] 2015-11-23 19:37
Yes that's one of my to do items. The problem is with legends not being appropriately hidden. I'll have a look tonight.

**Comment by philippjfr** [comment] 2015-11-24 03:59
Fixed in a08952195f59658cf19d4295a2334fa88f169dbf. Closing.

**Closed by philippjfr** 2015-11-24 03:59 UTC
