### ISSUE TITLE
Improve CSS for quoted code blocks on website

### ISSUE THREAD

**Issue by jlstevens** [ioam/holoviews#618] opened 2016-04-19 08:21 UTC
Currently this line of the [introduction tutorial](holoviews.org/Tutorials/Introduction.html) is actually in a markdown cell in the actual notebook but looks like a code cell:

``` python
import holoviews as hv
e = hv.Element()
```

This is very confusing as anyone following the tutorial online will execute a cell that isn't tested, can break and isn't needed for the rest of the tutorial.

**Comment by philippjfr** [comment] 2017-06-23 02:19
Our new website design has the same issue. Is it really a problem? Certainly not a bug.

**Comment by jlstevens** [comment] 2017-06-23 02:21
I think it is a bug. You should be able to tell quoted code from code.

Thankfully we don't need to quote code that often.

**Comment by philippjfr** [comment] 2017-09-03 20:45
The Introduction tutorial is no longer rendered on the website, closing.

**Closed by philippjfr** 2017-09-03 20:45 UTC
Labels: docs
