### ISSUE TITLE
DynamicMap issues at the edge of the slider ranges

### ISSUE THREAD

**Issue by jlstevens** [ioam/holoviews#720] opened 2016-06-13 20:40 UTC
Both Philipp and I are aware of this issue but it is worth assigning to the next milestone to make sure we don't forget to fix it!

<img width="1264" alt="screen shot 2016-06-13 at 9 30 38 pm" src="https://cloud.githubusercontent.com/assets/890576/16022328/36cc9620-31af-11e6-9a99-789ac403b24b.png">

In the JavaScript console:

```
Warning: HoloViews callback returned unexpected data for key: ( [3.1415926536,2.587] ) with the following content: Objectename: "AttributeError"evalue: "'DynamicMap' object has no attribute 'depth'"traceback: Array[11]__proto__: Object
```

Note that the ``args`` attribute is part of this PR #719

**Comment by philippjfr** [comment] 2016-06-16 14:23
Duplicate of https://github.com/ioam/holoviews/issues/601. Closing.

**Closed by philippjfr** 2016-06-16 14:23 UTC
Labels: bug

**Comment by jlstevens** [comment] 2016-06-16 15:19
Ok. I thought this issue might be a duplicate.
