### ISSUE TITLE
Support for twin Y-axes in bokeh 

### ISSUE THREAD

**Issue by iweey** [ioam/holoviews#1860] opened 2017-09-10 15:57 UTC
how to set  twin Y-axes in bokeh  
the two  Y-axes range harmonious

```
%%opts Curve  [width=800 height=400 tools=['hover','box_select', 'lasso_select' ] toolbar='above'] 
from bokeh.models import LinearAxis, Range1d

def twinx(plot, element):
    # Setting the second y axis range name and range
    start, end = (element.range(1))
    label = element.dimensions()[1].pprint_label
    plot.state.extra_y_ranges = {"foo": Range1d(start=start, end=end)}
    # Adding the second axis to the plot. 
    linaxis = LinearAxis(axis_label=label, y_range_name='foo')
    plot.state.add_layout(linaxis, 'right')


curve_all = hv.Scatter(ot.drive_pbdf, kdims=['date'], vdims=['speed_kmph'] ) 
curve_all_a = hv.Curve(ot.drive_pbdf, kdims=['date'], vdims=['speed_kmph'] ) 
cc = curve_all*curve_all_a
curve_acc = hv.Scatter(ot.drive_pbdf, kdims=['date'], vdims=['speed_kmph_acc']) (plot=dict(finalize_hooks=[twinx]), style=dict(color='red'))
h =cc * curve_acc
h


```

this is bad 
![image](https://user-images.githubusercontent.com/2853214/30250621-2822c66c-9617-11e7-842e-3d08268d8d89.png)

**Comment by philippjfr** [comment] 2017-10-27 17:53
This is a duplicate of #1594, I'll try to answer your question there. Sorry I haven't responded sooner.

**Closed by philippjfr** 2017-10-27 17:53 UTC
Labels: feature
