### ISSUE TITLE
Simplify (and semi-automate) testing process

### ISSUE THREAD

**Issue by maxalbert** [ioam/holoviews#341] opened 2015-12-07 21:02 UTC
Currently the reference data for test outputs is kept in a separate repository (`holoviews-data`). This has multiple disadvantages: (i) the reference data is huge, which makes the repo very bulky, (ii) the reference data needs manual updating whenever a commit to Holoviews changes the visual output, and (iii) the process for submitting PRs requires changing both the `holoviews` and the `holoviews-data` repositories in sync(!) via multiple non-trivial steps.

Instead of storing the entire reference data I suggest to only store the commit ID of a known "good" revision in Holoviews (let's call it `rev_GOOD`) which we know generates the correct reference data. This revision is just a string, so it can easily be stored in the Holoviews repo itself.

Upon each push the tests would then do the following:

- Check out the older revision `rev_GOOD` and generate the reference test data from it.

- Check out HEAD and generate the test output data from it. (Ideally this step would run concurrently with the previous one to save time.)

- Compare the output data and the reference data. If both are identical then all is good and the PR can be merged.

- Otherwise FAIL and make the differences in the outputs available somewhere on a build server so that someone can inspect them manually.

- If these differences are expected (for example due to a typo fix as in my recent PR), simply add another commit which updates `rev_GOOD` to the latest HEAD. Then next time the test are run they will pass (trivially) and the PR can be merged.

- On the other hand, if the differences are unexpected then the PR can be rejected.

I don't think Travis allows making build artifacts available, but there are other similar services (such as CircleCI) which definitely allow this, so using one of these could be an easy way to make the visual differences available without having to set up and run a dedicated build server.

**Comment by maxalbert** [comment] 2015-12-07 21:10
Tools such as `perceptualdiff` or matplotlib's `@image_comparison` decorator could be useful to generate images for the visual differences in the outputs. There was also a recent announcement on the Jupyter mailing list for a new tool called nbdime (https://github.com/martinal/nbdime) for diffing and merging of notebooks, and they said that they plan to support diffing of images in notebooks. Currently the project is highly experimental, but it's co-initiated by some of the core Jupyter devs so I expect it to be fairly usable reasonably soon.

**Comment by jbednar** [comment] 2015-12-07 21:11
That's an interesting suggestion.  But I don't think I would trust the results -- the output can change in all sorts of ways even if the HoloViews code doesn't change, because we depend on various libraries installed on the system.  We could easily get tests that pass because both the new and the reference code both generated the same garbage!

**Comment by philippjfr** [comment] 2015-12-07 21:15
The idea would be that the CI service would make the build artifacts and any differences available so we can review them before merging. For changing pickled data I'd probably still want a separate set of more permanent tests.

**Comment by jlstevens** [comment] 2015-12-07 21:17
There is also something @maxalbert pointed out, the possibility of [caching directories on Travis](https://docs.travis-ci.com/user/caching/#Arbitrary-directories). Definitely something to look into...

**Comment by maxalbert** [comment] 2015-12-07 21:17
@jbednar Changing dependencies is a good point. However, you could easily hard-code explicit versions of the dependencies and require those to be updated manually in a separate commit. This introduces a slight overhead in maintenance, but it has the extra advantage that it allows you to check whether an upgraded version of a dependency changes the build output.

**Comment by maxalbert** [comment] 2015-12-07 21:18
I just saw that CircleCI also allows caching: https://circleci.com/docs/how-cache-works

**Comment by jbednar** [comment] 2015-12-07 21:20
I still don't see how that would help -- how would you ever know if you had all the dependencies included?  Surely any system library anywhere could affect the results of HoloViews or any nontrivial program.  How could you ever be sure that your output was still actually ok, short of manual inspection (which is the same as not testing at all)?  I don't see how one could avoid storing and comparing against the actual output, if what you want to ensure is that the output hasn't changed.

**Comment by jlstevens** [comment] 2015-12-07 21:23
> ... how would you ever know if you had all the dependencies included?

I guess one of the fancier environments (e.g docker) could help with this in theory but I'm not sure whether we could easily use something like this in practice.

**Comment by jbednar** [comment] 2015-12-07 21:58
If we used a VM that we cloned from a fixed master file, we could be pretty sure that nothing in the environment changed, and if we used Docker then we would be somewhat less sure, but still reasonably sure.  But then we'd need to archive VMs and Docker environments and make sure *they* didn't change, and I'm not sure that's an improvement.  

One obvious point is that one could *also* store the MD5 hash of the results, and then if the reference data and the new data both match each other and have the same hash that was stored, you'd be very confident the results have not changed, even without storing them.  The problem then becomes what to do when you discover the MD5 hash doesn't match even though both the reference implementation and the new commit match each other -- then I don't think there is any way to debug what might have caused the hash difference, which will leave us quite worried and perplexed.

Another issue is that just running the notebook tests is actually a very expensive operation, which would then double if we have to do it for both reference and new data.

One approach could be:

1. Store the MD5 sums of the entire set of output from every passing test
2. For each new commit, build the new set of output data, and test the MD5 sum.
3. If the MD5 sum matches, the commit is known good; done.
4. If the MD5 sum does not match, re-run the reference data, and do a detailed diff to show what has changed.
5. If the detailed diff shows no differences, yet the MD5 sum differs, we're out of luck.

**Comment by maxalbert** [comment] 2015-12-07 22:01
You certainly have a point that output of Holoviews might change if one of the system libraries is updated. (One would hope that this is fairly unlikely but it is certainly a possibility.)

However, I do not think that this is actually a problem. Let me explain what I mean. Ultimately it boils down to the question what the tests in Holoviews are trying to achieve. In particular, which of the following do you want to guarantee to the user?

(i) That Holoviews produces a certain **fixed output** when using a particular plotting backend.

(ii) That Holoviews **interfaces correctly** with a given plotting backend.

These are two very different things. In the first case there is indeed no way around storing the fixed reference output. However, it introduces a huge additional dependency and burden because your tests are effectively not just tests for Holoviews itself but also implicitly test all your backends at the same time. (For example they ensure that matplotlib's bar plots looks exactly the same in future versions as they do now.)

The testing procedure which I outlined above cannot guarantee (i), but it is appropriate for ensuring (ii). Once you have manually investigated and approved the output produced by a certain Holoviews version you can be certain that Holoviews interfaces correctly with your backends (to the extent covered by the tests). Thus in order to test _Holoview itself_ it is enough to make sure that future Holoviews versions generate the same output as the present version. If this output suddenly looks different then this is not an issue in Holoviews (so long as the auto-generated reference output also looks different in the same way) but rather an upstream bug (or bug fix for that matter) in one of the backends. In my opinion it should not be Holoviews' responsibility to test this. For example, why would you care whether matplotlib suddenly changes a styling detail in its barplots, so long as Holoviews calls the correct bar plot commands on matplotlib (which you know it does because you explicitly approved a previous version of Holoview's output)? With the existing testing prodedure you are forced to test this because your reference data intrinsically contains this information. But I don't think you should have to test it because it falls outside the responsibility of Holoviews. But that's of course just my own view and you may disagree.

**Comment by philippjfr** [comment] 2015-12-07 22:07
Note also that our current tests also give us no idea if the output stay consistent across versions. Currently we're locked into matplotlib 1.4.3 because the latest numpy and matplotlib don't seem to play nicely on Travis. They also don't work on my Macbook due to various issues I can't solve. So we are already locked into a situation where we rely on a specific OS and library versions to keep the tests passing.

**Comment by maxalbert** [comment] 2015-12-07 22:13
Of course, there is still the option of using a hybrid approach where most of the time you rely on auto-generated reference output (using a procedure similar to what I outlined above, either in combination with caching to avoid expensive re-computations, or using MD5 sums as suggested by @jbednar), but where you also periodically (e.g. once a week) compare the output to fixed reference data in the same way that you do now. I personally still think the latter part would test "too much" (i.e., test things outside Holoview's responsibility), but again I'm not a Holoviews developer so it's up to you guys to decide what you want to achieve. :)

**Comment by jbednar** [comment] 2015-12-07 22:14
I think there are multiple levels of matching, and that all of them are useful:

1. Having the same MD5 sum total of all the output is one level, and is the strongest assurance of no change (though not currently a level we ensure).
2. Having the various cell outputs match stored reference data, according to our custom criteria, makes it clear nothing has changed that requires manual inspection and ok (this is our only currently supported level)
3. Getting the same output for the same environment as a reference HoloViews version is a weaker criterion, which will catch most things that are our own fault, but *not* everything we need to deal with.

E.g. if matplotlib changes in a way that makes plots turn out subtly or obviously different, we need to know about it -- it could be a new bug in mpl (which we need to report and get fixed), it could be an old bug in mpl that was corrupting our output until now (which we need to investigate and maybe freak out about), it could be something undocumented in mpl that we never should have been using and was legitimately changed in a safe way but it still causes our results to change (which we need to fix in our own code), or it could be a change in styling which we simply need to verify and then declare ok.

What I would like is for there to be an extremely simple way to say 'ok, these changes are expected and fine'.  Unfortunately, it's not at all straightforward to do that with our testing setup. :-/  

It would be great if we would automatically fall back when reporting differences -- report 1 when it's true, else 2, then 3 (but with 3 require hitting one of the devs to indicate (easily!) that it's ok, moving the status back to 2.

**Comment by jbednar** [comment] 2015-12-07 22:16
> Note also that our current tests also give us no idea if the output stay consistent across versions. Currently we're locked into matplotlib 1.4.3 because the latest numpy and matplotlib don't seem to play nicely on Travis. They also don't work on my Macbook due to various issues I can't solve. So we are already locked into a situation where we rely on a specific OS and library versions to keep the tests passing.

We can still run the tests on whatever platform we're using, outside of Travis, so it's not as dire as all that.  The problems on Macbook sound like something to address, though.

**Comment by maxalbert** [comment] 2015-12-07 22:51
@jbednar Good points. I like the idea of using MD5 sums as an easy way to ensure the output hasn't changed. In which way do you think this is actually stronger than 2? Do you currently allow any tolerances that are a weaker criterion than exact reproducibility?

Regarding your scenarios which might cause 3. to pass but 2. to fail, I personally think that the only one which legimtiately falls into the realm of what Holoviews should be testing is the "undocumented internal feature" scenario, because this is the only one that requires a change in Holoview's code base.  It would certainly be nice if Holoviews could catch legitimate bugs in matplotlib, but IMHO it's not its responsibility to do so.

Anyway, I agree that it would be great to have a testing setup that allows 1.-3., but 3. should be enough for 99% of the situations because it catches everything except the "undocumented feature" scenario. Given that it would hugely simplify the process of submitting PRs, I think it could be worth making this the default testing procedure within the Holoviews repo. Alternatively, or in addition, you could use 1. if you only store the MD5 sums and not the reference data, because it is equally cheap or even cheaper than 3.

I guess 2. would still be nice to have because it is the only way to easily figure out what actually changed if there is a difference in output. However, it could be worth keeping the known reference data, as wellas  the associated tests which match new Holoviews output against this data, in a separate repo which only "observes" the Holoviews repo but doesn't require cross-linking back to it when submitting a PR.

**Comment by jbednar** [comment] 2015-12-08 20:32
I'm not sure what we're doing in HoloViews itself, but we developed this testing infrastructure in the context of the full set of packages maintained at http://ioam.github.io.  In at least some of these projects, we have reference data that we have been maintaining for about a decade, with results that are consistent over that entire period except for floating-point differences in the fifth or sixth decimal place that are dependent on system software versions, platform differences, and so on.  Getting correct output in these cases means matching this looser criterion; we're not worried about whether the MD5 sums changed, but about whether our results changed.  In HoloViews notebook testing, I don't know which level of matching has been specified; that was up to Jean-Luc.

**Comment by jbednar** [comment] 2015-12-08 20:33
In any case, something clearly does need to be changed about the testing infrastructure; it's far too unwieldy at the moment!  E.g. I myself can't make any changes to the notebooks without subjecting Philipp to the onerous task of updating the reference data. Ack!

**Comment by jlstevens** [comment] 2016-02-07 00:56
A lot of this has greatly improved now:

* No more submodule for reference data (there is still a repository though).
* Hosting the website on S3. ``gh-pages`` which was really bloating the repository is gone!
* [travis.holoviews.org](http://travis.holoviews.org/) to view the test data generated by Travis.
* [buildbot.holoviews.org:8010](http://buildbot.holoviews.org:8010/) hosted on an EC2 instance including nightly builds.
* [dev.holoviews.org](http://dev.holoviews.org/) to preview documentation based on master.
* [build.holoviews.org](http://build.holoviews.org/) to preview how PRs update the website and notebooks.
* A cached status alongside the Travis build reports in PRs which supplies a link that allows very easy updating of reference data for the PR.
* Automatic merging of reference data into master when the 'Merge' button is clicked on GitHub. No more annoying 'Updated reference data submodule reference' commits!
* All this infrastructure is based on either docker (i.e easily transported) or a few small Python scripts on AWS Lambda.
* The code for this infrastructure can be found on the ``buildbot`` branch of [ioam-builder](https://github.com/ioam/ioam-builder/tree/buildbot).

This system has already been exercised a lot in the past few days since it has been up and running and I am very happy with it. I realize it doesn't follow @maxalbert suggestion which is much better than our old system but probably not as convenient as what we have now. :-)

One thing mentioned above that I need to think about is the proposed MD5 hashing system. I believe this could be related to a proposal to run tests in a more general fashion (see this PR #318 which suggests a promising future direction).

The other thing I *do* want to see is visual diffing to go on  [travis.holoviews.org](http://travis.holoviews.org/). This could be done on AWS in the Lambda that generates that particular page but it is probably better to simply use imagemagick as it is installed on Travis. 

The best place to implement it is probably using  [concat_html.py](https://github.com/ioam/ioam-builder/blob/nbpublisher/concat_html.py). It would need to script the html, base64 decode the reference and test images, save them out, use imagemagick ``compare`` before packaging the output back into HTML. All feasible and although  PIL could be used,  I think using ``compare`` is the simplest, standard option.

Based on all this, I would like to close this issue as only a few clicks are now needed to update the  testing process on PRs. I've opened #465 regarding visual diffs and please do open a specific issue if we want to consider using MD5 hashing in some way as part of an improved testing process (once again, PR #318 might be worth a look).

**Comment by philippjfr** [comment] 2016-02-07 01:04
Great summary and great work on setting up the docker images and buildbot! We can continue to improve and tweak the system as you suggest, in particular visual diffing on travis.holoviews.org will be helpful and hopefully I'll get around to it soon. For now though I think we can be very happy with what we have now and I'll close the issue.

**Closed by philippjfr** 2016-02-07 01:04 UTC

**Comment by jlstevens** [comment] 2016-02-07 01:19
I've read through this thread again to make sure I haven't missed anything. I've not said much about the different levels of testing so I'll make a quick comment about that and what the new system does.

* I believe that we should improve our nosetests to check the integration of HoloViews with the backend without testing the backend itself. We always want more unit tests!
* The new system is more flexible than before. Even though we do diffs on the output (which tests the backend) with travis.holoviews.org, we can inspect any changes (e.g if matplotlib fixes something) and very easily agree that the changes are good and update the reference data.
* Regarding the issue of the testing environment I suggest we use docker in issue #440. That will help enable local testing on Mac OS.
* We plan to keep reference data per release in one of our S3 buckets. There the files have been automatically zipped and are easily manageable.
* We are using the test data from Travis which means that our travis.yml defines at least part of the environment used for testing (which a docker image for testing would need to mirror). One great thing about the new approach is that we don't waste time recomputing notebooks when updating test data. Instead we simply decide if the test data generated on Travis is correct and should become the new reference data.
* Because of this, I don't really think MD5 hashing would add much. Pickle comparisons tell us what about a HoloViews object has changed and diffing the HTML lets us detect differences as well as see the change visually. A hash in contrast is small but completely opaque.

Anyway, we can continue discussion here if we want (even though the issue is now closed) although any concrete ideas should be posted as new issues.
