### ISSUE TITLE
Rendering HoloMap as GIF with matplotlib/pillow fails under Windows

### ISSUE THREAD

**Issue by smillies** [ioam/holoviews#3151] opened 2018-11-07 07:33 UTC
I am trying to create an animated gif image from a series of heat maps with HoloViews. I need to do this in a Python script, i. e. specifically not in a Jupyter notebook. I am using Python 3.7 under Windows 10.

When saving the image, Python throws a PermissionError originating from PIL\Image.py line 1966 while manipulating a temporary file. However, it doesn't seem like a user permission problem, as it happens also for users with unrestricted rights. At the point the exception happens, the temporary file has already been created on the file system.

The same code runs as expected under CentOS 7. Here's [an SSCE](https://gist.github.com/smillies/2575831ddfa5731b8d04d08d0f1bdad1)

Here's [another minimal example](https://gist.github.com/ImportanceOfBeingErnest/f44d5137fa44fa9f5e1833bb022d3eee) by [ImportanceOfBeingErnest](https://stackoverflow.com/users/4124317/importanceofbeingernest) that removes holoviews from the picture by making a direct call to matplotlib's `FuncAnimation.save("fname", writer="pillow", fps=5)`. That works OK under Windows. So it looks like the holoviews save function might be broken.  

ImportanceOfBeingErnest also played around a bit in the source code of holoviews and it also fails to save via imagemagick or imagemagick_file. (Although fixing this part of the issue is probably not a priority in view of #2460) 

The source of this issue is [this discussion](https://stackoverflow.com/questions/53163438/permissionerror-errno-13-permission-denied-when-saving-holomap-to-gif) on StackOverflow.

**Comment by philippjfr** [comment] 2018-11-07 19:18
Thanks @smillies, this detailed investigation is very helpful. None of the core developers use windows, which is probably why this hasn't been caught. Let's aim to get a fix for this into holoviews 1.11.0 due to be released next week.

**Comment by jbednar** [comment] 2018-11-07 19:43
I think the [hv code in question](https://github.com/ioam/holoviews/blob/master/holoviews/plotting/mpl/renderer.py#L234) is:

```
with NamedTemporaryFile(suffix='.%s' % fmt) as f:
                anim.save(f.name, writer=writer, **anim_kwargs)
                video = f.read()
```

According to the [Python docs](https://docs.python.org/2/library/tempfile.html), NamedTemporaryFile has different behavior in Windows:

> Whether the name can be used to open the file a second time, while the named temporary file is still open, varies across platforms (it can be so used on Unix; it cannot on Windows NT or later). 

I'm not sure what anim.save is in this case, but from that description, maybe @smillies could see if the file could be closed before anim.save and opened after for the reading step?  Otherwise it would seem that anim.save would need to be rewritten to take a file handle instead of a file name, and in that case it's hard to see what the point of NamedTemporaryFile is on Windows...

**Comment by smillies** [comment] 2018-11-08 07:30
I don't think that the suggestion by @jbednar is an option, because the Python docs also state that a temporary file will be destroyed as soon as it is close.

**Comment by xavArtley** [comment] 2018-11-08 16:34
On Bokeh a small hack is performed to make NamedTemporaryFile works on windows

[test_themes.py](https://github.com/bokeh/bokeh/blob/7714f96511ab0496f666fa87fc0de1c74c3879f1/bokeh/tests/test_themes.py)
  ```
class TestThemes(object):

  def test_construct_empty_theme_from_file(self):
        # windows will throw permissions error with auto-delete
        with (tempfile.NamedTemporaryFile(delete=False)) as file:
            # create and apply empty theme with no exception thrown
            file.file.write("".encode('utf-8'))
            file.file.flush()
            theme = Theme(filename=file.name)
            theme.apply_to_model(ThemedModel())
        file.close()
        os.remove(file.name)
```

**Comment by smillies** [comment] 2018-11-08 17:39
Thanks for the hint, @xavArtley . Importing `os` and doing the same in [renderer.py](https://github.com/ioam/holoviews/blob/master/holoviews/plotting/mpl/renderer.py#L245) seems to do the trick.

    # Windows will throw PermissionError with auto-delete
    with NamedTemporaryFile(suffix='.%s' % fmt, delete=False) as f:
        anim.save(f.name, writer=writer, **anim_kwargs)
        video = f.read()
    f.close()
    os.remove(f.name)

I do not feel up to testing such a change and submitting a pull request for it. Would be grateful if someone could investigate the viability of this fix.

**Comment by philippjfr** [comment] 2018-11-08 18:02
Thank you both, I can confirm that this change works for me. I'll submit a PR.

**Comment by philippjfr** [comment] 2018-11-08 21:42
Tentatively closing, please reopen if it doesn't work for you.

**Closed by philippjfr** 2018-11-08 21:42 UTC
Labels: bug, mpl

**Comment by Vikkiechauhan** [comment] 2019-07-17 15:14
hello, i want to use render the holoviews output as gif on windows. I am facing this issue as below and now i waited a long time for the output but nothing is showing up :

WARNING:root:Points05279: Setting non-parameter attribute width=500 using a mechanism intended only for parameters
WARNING:root:Points05279: Setting non-parameter attribute height=475 using a mechanism intended only for parameters
WARNING:root:Points05279: Setting non-parameter attribute size=12 using a mechanism intended only for parameters
WARNING:root:Points05279: Setting non-parameter attribute color=black using a mechanism intended only for parameters
INFO:matplotlib.animation:Animation.save using <class 'matplotlib.animation.PillowWriter'>
​
