### ISSUE TITLE
Implement alerts for exceptions in DynamicMaps

### ISSUE THREAD

**Issue by jlstevens** [ioam/holoviews#946] opened 2016-10-21 14:32 UTC
Currently when using DynamicMaps with the Bokeh backend, exceptions get logged to the web console. Unfortunately, such errors are hard to discover - you will only find them if you remember to check the web console after noticing some strange behaviour. 

The current behavior might be good in some situations but the risk is that users will think HoloViews is not working properly as they won't see the exceptions raised by their own code (the DynamicMap callbacks). For this reason, we should consider issuing alerts containing the relevant tracebacks that won't be so easily ignored.

**Comment by philippjfr** [comment] 2017-03-15 18:38
As an alternative document good patterns to debug DynamicMap callbacks, e.g. update stream directly.

**Comment by philippjfr** [comment] 2018-03-02 15:31
Duplicate of https://github.com/ioam/holoviews/issues/372.

**Closed by philippjfr** 2018-03-02 15:31 UTC
