### ISSUE TITLE
Axis extents in HoloMaps containing hv.Distributions

### ISSUE THREAD

**Issue by vascotenner** [ioam/holoviews#690] opened 2016-05-25 07:49 UTC
By default, all frames in a holomap should have the same extends on all axis.

Bug: When creating a HoloMap containing hv.Distributions, the axis extents are different for every frame. This behaviour cannot be altered by the {} options.

One way of fixing the axis is to manually supply extents:

``` python
%%output holomap='gif' fps=5
d1 = 25 * np.random.randn(500) + 450
d2 = 45 * np.random.randn(500) + 540
d3 = 55 * np.random.randn(500) + 590
hv.HoloMap({'d1': hv.Distribution(d1, label='Blue', extents=(0,0,900,0.02)),
'd2': hv.Distribution(d2, label='Red'),
'd3': hv.Distribution(d3, label='Yellow')}
```

**Comment by philippjfr** [comment] 2016-05-25 09:42
This is a general problem for some plot types, when it's not possible to pre-compute the extents of a plot element ahead of time. In the case of the Distribution the problem is that the actual Distribution does not get computed until seaborn actually renders the plot and it's dependent on things like the kernel width, which is an option on the plot. I can't really suggest how to get around it, except to introduce dynamically computed Elements like this sparingly and rarely. That said I use ``Distribution`` all the time despite this shortcoming and wouldn't want to abandon it just because it's lacking this feature.

**Comment by vascotenner** [comment] 2016-05-25 09:58
Should we add this somewhere in the documentation? Or is this issue tracker indexed well enough such that possible desperate users will find it via a search engine?

**Comment by jjtapia** [comment] 2016-05-25 18:06
It seems that combining a set of distributions into a holomap or combining holomaps through the '*' operator or using an ndoverlay object resets the extent setting, and goes back to where each frame has its own axis limits while displaying the animation. this code reproduces this issue:

`
`%%output holomap='gif' fps=5

def myRandom(mult, offset):
    return (mult) * np.random.randn(500) + offset

hm1 = hv.HoloMap(kdims=['Seconds'])
hm2 = hv.HoloMap(kdims=['Seconds'])
hm3 = hv.HoloMap(kdims=['Seconds'])

final1 = hv.HoloMap(kdims=['Seconds'])
final2 = hv.HoloMap(kdims=['Seconds'])
final3 = hv.HoloMap(kdims=['Seconds'])
for t in range(1,20):
    d1 = hv.Distribution(myRandom(25,t*10+450), label='Blue', extents=(0,0,900,0.02))
    d2 = hv.Distribution(myRandom(45,t*10+540), label='Red', extents=(0,0,900,0.02))                           
    d3 = hv.Distribution(myRandom(55,t*10+590), label='Green', extents=(0,0,900,0.02))
    ndov = hv.NdOverlay({'blue':d1, 'red':d2, 'green':d3})
    hm1[t] = d1
    hm2[t] = d2
    hm3[t] = d3
    final1[t] = d1*d2*d3
    final3[t] = ndov
final2 = hm1*hm2 *hm3

hm1 + final1 + final2 + final3`

**Comment by philippjfr** [comment] 2016-05-25 18:10
Thanks @jjtapia!

**Comment by philippjfr** [comment] 2017-12-08 17:35
Since we merged real support for Distribution types this issue has been resolved, closing.

**Closed by philippjfr** 2017-12-08 17:35 UTC
Labels: bug, docs, mpl
