### ISSUE TITLE
Styling individual elements in a GridMatrix is ignored by datashade operation

### ISSUE THREAD

**Issue by suyang-nju** [ioam/holoviews#2698] opened 2018-05-19 04:08 UTC
The following code tries to set the background and frame colors of one plot in a GridMatrix:

    def modify_frame(plot, element):
        print('modify_frame')
        plot.state.outline_line_color = 'blue'

    some_dataset = hv.Dataset(np.random.normal(size=(10000, 3)), [chr(65+i)+'_dimension' for i in range(3)])
    gd = gridmatrix(some_dataset)
    gd['A_dimension', 'B_dimension'].options(finalize_hooks=[modify_frame], bgcolor='lightyellow', clone=False)
    gd.map(datashade, hv.Scatter)

but there's no color changes, and no output from the `print()` in `modify_frame`. It seemed that `modify_frame` was not called. If the last line was `gd` or `gd.map(decimate, hv.Scatter)`, the code worked as expected. Somehow `datashade` 'eats' the options?

**Comment by jbednar** [comment] 2018-05-19 13:45
I think this is a specific case of the issue in https://github.com/ioam/holoviews/issues/2637 .  I agree it's confusing, and I'd really like to find a solution.

**Comment by philippjfr** [comment] 2018-05-22 13:46
As @jbednar points out this is a duplicate of #2637, so I'll close. For now the correct thing to do is to apply the plot options **after** datashading.

**Closed by philippjfr** 2018-05-22 13:46 UTC

**Comment by suyang-nju** [comment] 2018-05-22 19:10
@philippjfr Applying the plot options after datashading still has no effect:
```
gd = hv.operation.gridmatrix(some_dataset).map(hd.datashade, hv.Scatter)
gd['A_dimension', 'B_dimension'].options(finalize_hooks=[modify_frame], bgcolor='lightyellow', clone=False)
gd
```

Interestingly, the plot options are set and can be seen if only that plot is shown:
```
gd['A_dimension', 'B_dimension'].options(finalize_hooks=[modify_frame], bgcolor='lightyellow', clone=False)
```
will show a plot with lightyellow background and blue frame. But when the plot is shown together with other plots in a GridMatrix with `gd`, the plot options are lost.

![bokeh_plot](https://user-images.githubusercontent.com/35547836/40384639-27fe9aac-5dd2-11e8-9e95-dcc6f6924317.png)

**Comment by jbednar** [comment] 2018-05-22 19:26
It's possible to use these tools without having to think deeply about how it all works, and we try to facilitate that where practical, but sometimes you have to appreciate all of the details, especially if you want to control them.  Here., Datashader returns transparent images, which will reveal the background color of the plot the same as if you hadn't used datashader.  But `datashade()` controls the foreground color, so you have to pass that to the `datashade()` operation if you want to change that.  And `datashade()` also changes the plot from being a point plot to an RBG plot, so options that apply to points aren't relevant after `datashade()`.  You can use more of the usual styling mechanisms if you use `rasterize()` instead of `datashade()`, where Bokeh controls the assignment of colors and Datashader is only responsible for the rasterizing/aggregating step. If you do use `rasterize()`, and are aware that it turns the data into an `hv.Image()` and apply options suitable for an Image, you'll probably be able to achieve what you want.

**Comment by suyang-nju** [comment] 2018-05-22 21:42
Thanks @jbednar. The same issue happens when I use `rasterize()`. I played with the code a bit more and the result is even more puzzling.

I understand I'm dealing with RGB elements after datashade(), and should apply options for RGB. RGB elements have the `bgcolor` and `finalize_hooks` options, and those options are indeed applied (see picture in my last comment) if I only show that RGB element by 
```
gd['A_dimension', 'B_dimension'].options(..., clone=False) # works
```
The plot options are _not_ set when I try to set the options of one plot and then show the whole gridmatrix in one cell:
```
gd['A_dimension', 'B_dimension'].options(..., clone=False) # doesn't work
gd # doesn't work
```
The `modify_frame` function I passed to `finalize_hooks` is not even called in this situation (because no output from the `print()` in the function).

More puzzling is if I put the following three lines in three separate cells, everything is fine, the plot options are applied
1) `gd['A_dimension', 'B_dimension'].options(..., clone=False)`
2) `gd['A_dimension', 'B_dimension']`
3) `gd`
![bokeh_plot5](https://user-images.githubusercontent.com/35547836/40391580-c1ddf8de-5de6-11e8-81db-eec33ce4970f.png)

But if I put 1) and 2) in the same cell, and 3) in a separate cell, then the plot options are not applied at all
![bokeh_plot6](https://user-images.githubusercontent.com/35547836/40391691-30c61a88-5de7-11e8-9b4b-5da8ec9cdec3.png)

**Comment by jbednar** [comment] 2018-05-22 21:50
Hmm.  That doesn't sound like it's behaving properly, to me.  @philippjfr?

**Comment by jbednar** [comment] 2018-05-22 21:50
Might be hard to test without a runnable reproducing example.

**Comment by suyang-nju** [comment] 2018-05-22 22:01
@jbednar This is the code I used in the screenshots, run in jupyter lab or notebook environment.
```
def modify_frame(plot, element):
    print(element)
    plot.state.outline_line_color = 'orange'
    plot.state.outline_line_width = 8

some_dataset = hv.Dataset(np.random.normal(size=(10000, 3)), [chr(65+i)+'_dimension' for i in range(3)])
gd = hv.operation.gridmatrix(some_dataset).map(hd.datashade, hv.Scatter).map(hd.dynspread, hv.RGB)

gd['A_dimension', 'B_dimension'].options(finalize_hooks=[modify_frame], bgcolor='lightyellow', clone=False)
gd['A_dimension', 'B_dimension']
gd
```

**Comment by philippjfr** [comment] 2018-05-22 22:38
Thanks, that makes it much easier. That is indeed strange behavior.
