### ISSUE TITLE
Live update Div content?

### ISSUE THREAD

**Issue by suyang-nju** [ioam/holoviews#2656] opened 2018-05-05 22:34 UTC
Is there a way to update the content of a Div element in response to user interaction? The use case is to display data of a PolyDraw stream in the Div element, so the user can copy/paste those coordinates.
Div does not appear to work with streams?

**Comment by philippjfr** [comment] 2018-05-06 01:53
Could you provide a reproducible example where it isn't responding. At least in simple examples it works fine for me.

```python
test_stream = hv.streams.Pipe(data='<h1>New</h1>', rename={'data': 'html'})
hv.DynamicMap(hv.Div, streams=[test_stream]).options(height=50)
```

and then:

```python
test_stream.event(data='<h1>Updated</h1>')
```

**Comment by suyang-nju** [comment] 2018-05-06 02:13
Ah, I see. I was doing `hv.streams.Pipe(html=...)`. Now it works following your example. Thanks!

**Comment by philippjfr** [comment] 2018-05-06 02:27
>Ah, I see. I was doing hv.streams.Pipe(html=...). Now it works following your example. Thanks!

Was that not throwing an error or at least a warning?

**Comment by suyang-nju** [comment] 2018-05-06 02:35
Yes. There were warnings:

    WARNING:root:Pipe03397: Setting non-parameter attribute html=[] using a mechanism intended only for parameters
    WARNING:root:ParameterizedMetaclass: Exception raised in callable 'ParameterizedMetaclass' of type 'ParameterizedMetaclass'.
    Invoked as ParameterizedMetaclass(data=None)

**Comment by philippjfr** [comment] 2018-05-06 02:47
While the ``rename`` workaround works, I do think that what you expected to work should have and the Div constructor should be consistent in naming the argument ``data`` rather than ``html``. Not sure what the best migration path is to address this, since Div has only been around since 1.10 I'd consider doing the renaming now @jlstevens and @jbednar what do you think?

**Comment by jbednar** [comment] 2018-05-06 03:48
Seems ok to change it on div, as we have yet to make the big announcements.

**Comment by ea42gh** [comment] 2018-05-06 09:52
Re warning message: the first time I encountered
`Setting non-parameter attribute html=[] using a mechanism` it took me quite a while to parse it.

Even now, I do a double take: how about changing it to something like:
invalid argument 'html=[] passed to hv.Element', ....

While the code ignores the setting, it is likely a bug in the user's code

**Comment by philippjfr** [comment] 2018-05-06 10:57
>Re warning message: the first time I encountered Setting non-parameter attribute html=[] using a mechanism it took me quite a while to parse it.

I agree that could be clearer, it's a ``param`` level warning, worth raising an issue there.

**Comment by jlstevens** [comment] 2018-05-07 12:39
I agree the argument should also be called ``data``.

**Comment by jlstevens** [comment] 2018-05-07 12:40
I have merged the PR referenced above. Can this issue now be closed?

**Closed** 2018-05-07 13:04 UTC
