### ISSUE TITLE
Inconsistent behavior for edgecolor and edgecolors

### ISSUE THREAD

**Issue by jbednar** [ioam/holoviews#459] opened 2016-02-05 20:40 UTC
For Scatter3D, `edgecolor` and `edgecolors` give identical output. I would have thought that either both names would work for Points, or that one name would give an error, but `edgecolors` works for Points while `edgecolor` silently does not:

![image](https://cloud.githubusercontent.com/assets/1695496/12858500/21349a50-cc16-11e5-83b7-9bfae3783276.png)

![image](https://cloud.githubusercontent.com/assets/1695496/12858511/2ce8817c-cc16-11e5-9a52-e1882e8eafd4.png)

Is that intentional?

**Comment by philippjfr** [comment] 2016-02-05 20:52
This is an endless source of frustration for us, matplotlib various uses ``edgecolor``, ``edgecolors`` and ``ec`` and it's not very clear which takes precedence in each case, in particular in respect to the overall ``color`` or ``c`` setting. In some cases the resolution order is not even deterministic as it relies on dictionary ordering, which has been the cause of a bunch of transient errors. I suspect Points should be setting ``facecolors`` instead of ``c`` so you can always adjust the edgecolor.

**Comment by jlstevens** [comment] 2016-02-05 21:10
Agreed. The poor semantics and redundancy here is one of my least favorite aspects of the matplotlib API. Sadly, there is no simple, consistent fix that I know of, just an endless series of edge-cases where we can try to implement some sane behaviour.

**Comment by philippjfr** [comment] 2016-02-06 18:04
Tried fixing this in #461 but unfortunately it's not possible to do consistently with matplotlib 1.4.1 and we still can't upgrade to 1.5.1 on Travis. I'll push this issue to the 1.5 milestone.

**Comment by philippjfr** [comment] 2016-02-06 22:16
Fixed this in #461 afterall by handling it explicitly. Might not be needed once we switch to matplotlib 1.5, but will work in the meantime. Closing.

**Closed by philippjfr** 2016-02-06 22:16 UTC
Labels: mpl
