### ISSUE TITLE
Examples not work due to bokeh API change

### ISSUE THREAD

**Issue by fgoinai** [ioam/holoviews#2006] opened 2017-10-18 06:56 UTC
Some examples in gallery are not working due to bokeh API change

Traceback for ref:
```python
~\AppData\Local\Continuum\Anaconda3\envs\holoviews\lib\site-packages\IPython\core\formatters.py in __call__(self, obj)
    330                 pass
    331             else:
--> 332                 return printer(obj)
    333             # Finally look for special method names
    334             method = get_real_method(obj, self.print_method)

~\AppData\Local\Continuum\Anaconda3\envs\holoviews\lib\site-packages\holoviews\ipython\display_hooks.py in pprint_display(obj)
    257     if not ip.display_formatter.formatters['text/plain'].pprint:
    258         return None
--> 259     return display(obj, raw=True)
    260 
    261 

~\AppData\Local\Continuum\Anaconda3\envs\holoviews\lib\site-packages\holoviews\ipython\display_hooks.py in display(obj, raw, **kwargs)
    243     elif isinstance(obj, (HoloMap, DynamicMap)):
    244         with option_state(obj):
--> 245             html = map_display(obj)
    246     else:
    247         return repr(obj) if raw else IPython.display.display(obj, **kwargs)

~\AppData\Local\Continuum\Anaconda3\envs\holoviews\lib\site-packages\holoviews\ipython\display_hooks.py in wrapped(element)
    129         try:
    130             html = fn(element,
--> 131                       max_frames=OutputSettings.options['max_frames'])
    132 
    133             # Only want to add to the archive for one display hook...

~\AppData\Local\Continuum\Anaconda3\envs\holoviews\lib\site-packages\holoviews\ipython\display_hooks.py in map_display(vmap, max_frames)
    198         return None
    199 
--> 200     return render(vmap)
    201 
    202 

~\AppData\Local\Continuum\Anaconda3\envs\holoviews\lib\site-packages\holoviews\ipython\display_hooks.py in render(obj, **kwargs)
     59     if renderer.fig == 'pdf':
     60         renderer = renderer.instance(fig='png')
---> 61     return renderer.html(obj, **kwargs)
     62 
     63 

~\AppData\Local\Continuum\Anaconda3\envs\holoviews\lib\site-packages\holoviews\plotting\renderer.py in html(self, obj, fmt, css, comm, **kwargs)
    255         plot, fmt =  self._validate(obj, fmt)
--> 256         figdata, _ = self(plot, fmt, **kwargs)
    257         if css is None: css = self.css
    258 

~\AppData\Local\Continuum\Anaconda3\envs\holoviews\lib\site-packages\holoviews\plotting\bokeh\renderer.py in __call__(self, obj, fmt, doc)
     77             return self.server_doc(plot, doc), info
     78         elif isinstance(plot, tuple(self.widgets.values())):
---> 79             return plot(), info
     80         elif fmt == 'png':
     81             if bokeh_version < '0.12.6':

~\AppData\Local\Continuum\Anaconda3\envs\holoviews\lib\site-packages\holoviews\plotting\widgets\__init__.py in __call__(self)
    137 
    138     def __call__(self):
--> 139         return self.render_html(self._get_data())
    140 
    141 

~\AppData\Local\Continuum\Anaconda3\envs\holoviews\lib\site-packages\holoviews\plotting\bokeh\widgets.py in _get_data(self)
    239         # Get initial frame to draw immediately
    240         init_frame = self._plot_figure(0, fig_format='html')
--> 241         data = super(BokehWidget, self)._get_data()
    242         return dict(data, init_frame=init_frame)
    243 

~\AppData\Local\Continuum\Anaconda3\envs\holoviews\lib\site-packages\holoviews\plotting\widgets\__init__.py in _get_data(self)
    364 
    365     def _get_data(self):
--> 366         data = super(SelectionWidget, self)._get_data()
    367         widgets, dimensions, init_dim_vals = self.get_widgets()
    368         key_data = {} if self.plot.dynamic else self.get_key_data()

~\AppData\Local\Continuum\Anaconda3\envs\holoviews\lib\site-packages\holoviews\plotting\widgets\__init__.py in _get_data(self)
    153             json_path = json_path + '/'
    154         dynamic = json.dumps(self.plot.dynamic) if self.plot.dynamic else 'false'
--> 155         return dict(CDN=CDN, frames=self.get_frames(), delay=delay,
    156                     cached=cached, load_json=load_json, mode=mode, id=self.id,
    157                     Nframes=len(self.plot), widget_name=name, json_path=json_path,

~\AppData\Local\Continuum\Anaconda3\envs\holoviews\lib\site-packages\holoviews\plotting\widgets\__init__.py in get_frames(self)
    167         if self.embed:
    168             frames = OrderedDict([(idx, self._plot_figure(idx))
--> 169                                   for idx in range(len(self.plot))])
    170         else:
    171             frames = {}

~\AppData\Local\Continuum\Anaconda3\envs\holoviews\lib\site-packages\holoviews\plotting\widgets\__init__.py in <listcomp>(.0)
    167         if self.embed:
    168             frames = OrderedDict([(idx, self._plot_figure(idx))
--> 169                                   for idx in range(len(self.plot))])
    170         else:
    171             frames = {}

~\AppData\Local\Continuum\Anaconda3\envs\holoviews\lib\site-packages\holoviews\plotting\bokeh\widgets.py in _plot_figure(self, idx, fig_format)
    260                 msg = self.renderer.html(self.plot, fig_format)
    261             else:
--> 262                 json_patch = self.renderer.diff(self.plot, serialize=False)
    263                 msg = dict(patch=json_patch, root=self.plot.state._id)
    264                 msg = serialize_json(msg)

~\AppData\Local\Continuum\Anaconda3\envs\holoviews\lib\site-packages\holoviews\plotting\bokeh\renderer.py in diff(self, plot, serialize)
    231                        for h in handles]
    232         plot.traverse(lambda x: setattr(x, '_updated', False))
--> 233         patch = compute_static_patch(plot.document, plotobjects)
    234         processed = self._apply_post_render_hooks(patch, plot, 'json')
    235         return serialize_json(processed) if serialize else processed

~\AppData\Local\Continuum\Anaconda3\envs\holoviews\lib\site-packages\holoviews\plotting\bokeh\util.py in compute_static_patch(document, models)
    383             priority = float('inf')
    384         for key, val in obj['attributes'].items():
--> 385             event = Document._event_for_attribute_change(references,
    386                                                          obj, key, val,
    387                                                          value_refs)

AttributeError: type object 'Document' has no attribute '_event_for_attribute_change'
```

**Package**:
holoviews==1.8.3
bokeh==0.12.9

**Comment by nicolasterral** [comment] 2017-10-18 07:37
I have the same error with holoviews==1.8.4 and bokeh==0.12.10

**Comment by philippjfr** [comment] 2017-10-18 12:15
Yes, holoviews 1.8.4 and bokeh 0.12.10 are incompatible. We will be releasing a 1.8.5 hotfix release asap, in the meantime you can downgrade to bokeh 0.12.9 or upgrade to holoviews 1.9.0dev3. Closing as a duplicate of https://github.com/ioam/holoviews/issues/2005 because the necessary fixes have already been applied on master.

**Closed by philippjfr** 2017-10-18 12:15 UTC
