### ISSUE TITLE
Aspect ratio of Image and Raster

### ISSUE THREAD

**Issue by vascotenner** [ioam/holoviews#30] opened 2015-04-08 09:33 UTC
Currently, the Raster and Image function do not respect the aspect ratio of the data. 

Raster should have aspect='equal', such that pixels stay square, because almost everything samples with a square grid.

For Image, the optimal default behaviour is less clear. By default, the coordinates are transformed to continues coordinates. This means that equal and square are the same when no bounds are specified.
I propose that the aspect parameter of Image will be set by default to the aspect of the data.

**Comment by philippjfr** [comment] 2015-04-08 15:57
Aspect ratios are something we should handle more consistently in general as all our Layouts generally assume square aspects. I've got a prototype for more flexible Layouts, which do respect the aspect ratios of the Elements in them but it needs further testing. Until then I'd prefer to keep the aspects square by default, allowing the user to override them. Otherwise Layouts of non-square Elements are bound to start overlapping horrifically. Hopefully I can get my more flexible Layout system merged fairly soon.

**Comment by jlstevens** [comment] 2015-04-11 16:29
I've tagged this as being appropriate for out next minor (non-bugfix) version. Is this ok?

**Comment by jlstevens** [comment] 2015-05-19 08:32
@philippjfr Is this going to be fixed for 1.1.1? I thought you had some new code for aspects and sizing...

**Comment by philippjfr** [comment] 2015-05-19 11:35
I wouldn't consider this a bug, it's a deliberate choice on how aspects are to be handled due to limitations of our Layouts. The new aspect and sizing code is committed but does not currently have access to the aspect of the plot as determined by the data, i.e. the aspects you get when ``aspect='equal'``. This is something we could consider adding for the next release but for now we advise you to set the aspect to 'equal' yourself if you require it or to take advantage of the new more powerful Layouts by setting the aspect of your plots explicitly.

**Comment by jbednar** [comment] 2015-05-19 19:01
Even if it's not a bug, I too would vote for preserving aspect ratio by default, once there is suitable support to be able to handle that well.  Deliberately wanting non-square pixels does happen, but it is uncommon in my experience.

**Comment by philippjfr** [comment] 2015-05-19 19:32
> I too would vote for preserving aspect ratio by default, once there is suitable support to be able to handle that well.

That's also what I'm proposing, there is no suitable support to handle it well so I'd like to leave it as it is. Are you suggesting we should enable ``aspect='equal'`` and just put up with the whitespace issues that will cause for now?

**Comment by jbednar** [comment] 2015-05-19 19:42
Ok, we agree on the final goal; good.  Meanwhile, I don't know; I'd have to see examples of both options to know whether the bad whitespace or the non-square pixels is worse.

**Comment by philippjfr** [comment] 2015-05-19 20:16
Here's an example:

```python
%%opts Image [aspect='equal']
(hv.Image(np.random.rand(25,25), bounds=(0, 0, 1, 2)) +
 hv.Image(np.random.rand(25,25), bounds=(0, 0, 2, 1)) + 
 hv.Image(np.random.rand(25,25), bounds=(0, 0, 3, 1)) +
 hv.Image(np.random.rand(25,25))).cols(2)
```

![image](https://cloud.githubusercontent.com/assets/1550771/7712893/f923d9f4-fe6b-11e4-802e-406eae1cc519.png)

Not too terrible I guess. Do you think we should activate ``aspect='equal'`` for Image and Raster types based on this?

**Comment by jlstevens** [comment] 2015-05-19 21:24
I don't think I am in favour of changing this behaviour so close to a release. That isn't to say that this behaviour might not be better but I would want to try it out in the development branch for a while before making a pip release.

I should also probably mention that those pixels don't look square to me. ;-p

**Comment by philippjfr** [comment] 2015-05-19 21:32
Didn't think that through, the pixels are obviously not square because I didn't adjust the sampling. The pixels are the size they're supposed to be. Keeping the pixels square, i.e. respecting the sampling not the ranges, might be another useful option though. 

I don't mind much either way but agree trying this out in practice for a while might be nice.

**Comment by jbednar** [comment] 2015-05-20 14:25
On further thought based on your example, I think that by default Image and Raster should respect the ranges, not the sampling, because I think the most common data people want to visualize with such classes  corresponds to some underlying continuous space with no particular preferred axes, or at least with equal distances in all directions.  In such a case, uniform sampling will give square pixels, and non-uniform sampling will give rectangular pixels, but in both cases making the numerical ranges match will give the most spatially intuitive results.

People with data where the x and y axes are in different units, on the other hand, by default probably want square plots, since there's no meaning to having the plotted distances match between different units.  I think it makes sense for people in that situation to have to change some plotting option to get that behavior.

Note that if we had full support for units, the appropriate behavior could be deduced -- if dimension x and dimension y have the same units, by default we would want equal distances in the plot; if they have different units by default we would want square plots since we have no information about how the distances should relate to each other.  I would assume this type of deduction is not worth attempting until we had full and widely used unit support.

Meanwhile, whether to change the default to aspect='equal' is up to you.  True, it's very close to a release to change it now, but then again almost none of the tutorials use non-square aspects, so it will have minimal effect on the existing tested code, and it arguably improves the non-tested behavior.

**Comment by jbednar** [comment] 2015-05-20 14:31
At some point we do need to fix the sublabel positions, though.  It looks to me like our specified sublabel_position needs to be multiplied or divided by the aspect ratio before being used, so that it is independent of the aspect ratio.  Usually the position of items in the plot should respect the aspect ratio, but a sublabel's position should not, since it's relative to the axis labels and outer border normally, not the data, and I think this can easily be achieved by scaling the sublabel_position automatically by the aspect ratio.  That will fix the problems for the A, B, and C sublabels, right?

**Comment by basnijholt** [comment] 2015-05-22 10:34
I am absolutely in favour of setting the default ``aspect='equal'`` behaviour to the above plots of Philipp.

Now I'm plotting wavefunctions and need to set two options to make the aspects "equal".

```python
%%opts Image [aspect='equal']
hv.Image(np.rot90(img), bounds=((0,0)+img.shape)
```

![screen shot 2015-05-22 at 12 31 05](https://cloud.githubusercontent.com/assets/6897215/7768764/a1b24f38-007e-11e5-9e8b-683d602f32bc.png)

Instead I would expect this to give that behaviour:
```python
%%opts Image [aspect='equal']
hv.Image(np.rot90(img))
```
![screen shot 2015-05-22 at 12 33 51](https://cloud.githubusercontent.com/assets/6897215/7768787/d3f89f10-007e-11e5-9f75-b6d34baa9f55.png)

**Comment by jlstevens** [comment] 2015-05-22 12:15
Have you considered using a ``Raster`` instead of an image? Then you could avoid having to set the bounds.

**Comment by basnijholt** [comment] 2015-05-22 12:22
Thanks, that indeed works better :)

**Comment by philippjfr** [comment] 2015-06-24 18:53
In https://github.com/ioam/holoviews/commit/6d7b8a81278258f8aaf41cec6d48a7842051c9d1 I switched on equal aspects for all Raster type plots so I'll close the issue now.

**Closed by philippjfr** 2015-06-24 18:53 UTC
Labels: feature
