### ISSUE TITLE
Adjusting font size and label size

### ISSUE THREAD

**Issue by basnijholt** [ioam/holoviews#72] opened 2015-05-14 11:44 UTC
I can't figure out how to change the size of the fonts and label in a plot.

How is this possible?

**Comment by philippjfr** [comment] 2015-05-14 12:04
You should be able to do:

```
%opts Layout [fig_inches=(10,8) fig_rcparams={'axes.labelsize':20,'axes.titlesize':20}]
```

However the magic parser seems to complain if the rcparams dict contains more than on entry. I'd therefore recommend either setting the rcparams directly via matplotlib or using the ``hv.Store`` object (which holds all the options) directly like this:

```
hv.Store.options.Layout = hv.Options('plot', fig_rcparams={'axes.labelsize':20,'axes.titlesize':20})
```

**Comment by philippjfr** [comment] 2015-05-14 12:17
Maybe we should provide a slightly better interface to these options. I could imagine having title_kwargs, label_kwargs and tick_kwargs plot options allowing you to directly override the font options for each. Can anyone suggest any better names for these plot options?

**Comment by basnijholt** [comment] 2015-05-14 12:20
For me, the most obvious would be:
```python
%%opts Image [title_size=10 label_size=8]
```

or setting both the same

```python
%%opts Image [font_size=10]
```

**Comment by philippjfr** [comment] 2015-05-14 12:25
Seems reasonable, the kwargs thing would have let you set the font weight (i.e. bold, italic etc.) too but I think I think I agree with you, size is a far more common option and we want the name for that option to be clear. Should be fairly straightforward to implement these, will see maybe I'll add them today.

**Comment by jlstevens** [comment] 2015-05-14 13:13
Having an easy way to control font sizes makes sense to me but I would like to avoid the proliferation of size parameters. How about:

```python
%%opts Image [font_sizes={'title':10, 'xlabel':20, 'ylabel':25, 'ticks':7}]
```

What I prefer about this suggestions is that:

1. One parameter for all the fontsizes instead of many.
2. Actually shorter if you want to specify multiple font sizes at once.

If we declared ``font_sizes`` as a ``param.Parameter`` (less type checking unfortunately), you could even set all the font sizes at once by supplying a simple integer instead of a dictionary. This would be a fairly intuitive and simple default behaviour that could then easily be overridden using the more specific dictionary specification.

Thoughts?

**Comment by basnijholt** [comment] 2015-05-14 16:05
Sounds like an intuitive solution. Will autocomplete work with it though?

Also an easy way to turn of the ticks in the axes would be nice.

**Comment by jlstevens** [comment] 2015-05-14 16:11
The key ``font_sizes`` will still auto-complete but the possible dictionary keys (i.e ``'title', 'xlabel', 'ylabel', 'ticks'``) won't autocomplete unless someone does a *lot* of work on the completer. 

At least the easy case (i.e a single integer) is trivial but for finer control, users may have to  consult the documentation to see what options are possible. That said, I still think this is probably the cleanest solution!

**Comment by basnijholt** [comment] 2015-05-16 11:42
A font related issue, not all fontsizes of a HoloMap change:

```
hv.Store.options.Layout = hv.Options('plot', fig_rcparams={'axes.labelsize':40,
                                                           'axes.titlesize':40}) 
a = lambda: hv.Image(np.random.randn(10,10), bounds=(0, 0, 10, 10)).relabel('test1')
hv.HoloMap({1: a(), 2: a()})
```

![download 4](https://cloud.githubusercontent.com/assets/6897215/7665986/6c353ee4-fbd1-11e4-9457-c8e6910150c0.png)

**Comment by philippjfr** [comment] 2015-05-16 12:51
That example is due to a non-applying options definition. A single HoloMap is not a Layout, you'd have to set the figure_rcparams on the Image for it to apply:

```python
hv.Store.options.Image = hv.Options('plot', fig_rcparams={'axes.labelsize':40, 'axes.titlesize':40}) 
```

This is kind a counter-intuitive but expected behavior of the options system. If you want to set some options globally you could set them on the plotting baseclass, where they are first introduced, e.g. in this case you:

```python
from holoviews.plotting import Plot
Plot.fig_rcparams={'axes.labelsize':40, 'axes.titlesize':40}
```

We could consider providing a few branches to the Options tree are globally applied, e.g. ``Store.options.Global`` could apply to all plots and support all plot options that implemented on Plot, ``Store.options.Element`` could apply to all ElementPlots and support all of its plot options.

**Comment by jlstevens** [comment] 2015-05-16 13:43
> We could consider providing a few branches to the Options tree that are globally applied, e.g. Store.options.Global could apply to all plots and support all plot options that are implemented on Plot, Store.options.Element could apply to all ElementPlots and support all of its plot options.

Although I agree with the idea of such shortcuts, doing it this way would result in 'Element' and 'Global' appearing in the opts magic completions. 

While this does make *does* sense it may also complicate the magic further and confuse new users - I would favour only setting opts on concrete classes that can be used directly.

**Comment by jbednar** [comment] 2015-05-16 16:22
I would call Global "Plot" if that's the class it applies to (can't seem to find it easily in the source code), but it does seem useful to have them available.  I'm not sure why you argue that having them in the opts magic completions would be confusing -- seems like that's exactly where you want to have them, so that people realize that they can set things overall this way.

**Comment by jlstevens** [comment] 2015-05-16 19:25
I think for this problem, Philipp's suggestion of setting the defaults on ``Plot`` is the cleanest and safest approach which already works fine.

**Comment by jlstevens** [comment] 2015-05-18 23:33
I have implemented the fontsize parameter in the block of commits from 0f54bea to b598acc.

You can now use something simple like this:

```python
%opts Image [font_size=15]
```

or  something more involved like this:

```python
%opts Image [font_size={'title':10, 'xlabel':20, 'ylabel':25, 'ticks':7}]
```

The default of ``fontsize=None`` lets matplotlib decide via the rcparams. Note that in Layouts you can set the title size but the other options will be ignored (they need to be set at the appropriate level).

I think I can close this issue now. The only other suggestion was about setting parameters globally but I would say this is solved very nicely by Philipp's suggestion of setting ``fig_rcparams`` on ``Plot`` (or alternatively change the rcParams in ``default.mplstyle``.)

**Closed by jlstevens** 2015-05-18 23:33 UTC

**Comment by basnijholt** [comment] 2015-05-19 20:13
I'm a bit lost maybe, I'm trying to set the global fontsize and I don't want to do the following:

```python
%%opts Image [fontsize=13] Contours  [fontsize=13] Scatter [fontsize=13] Layout [fontsize=13]
```

for obvious reasons.

Then I tried Phillips 
```python
hv.Store.options.Image = hv.Options('plot',  fig_rcparams={'axes.labelsize':40,
                                                           'axes.titlesize':40})
```

and

```python 
from holoviews.plotting import Plot
Plot.fig_rcparams={'axes.labelsize':40, 'axes.titlesize':40}
```

and both give me:
![download 20](https://cloud.githubusercontent.com/assets/6897215/7712866/3358d2a2-fe74-11e4-9bb5-77e251a33239.png)

**Comment by basnijholt** [comment] 2015-05-19 20:17
**EDIT!**
I tried it again, but now it did change the labels for no apparent reason.
```python
from holoviews.plotting import Plot
Plot.fig_rcparams={'axes.labelsize':40, 'axes.titlesize':40}
```

![download 23](https://cloud.githubusercontent.com/assets/6897215/7712975/d35c9220-fe74-11e4-86d9-25adabc83ed7.png)

Although this doesn't change the label fontsize of the ``HoloMap``.

**Comment by basnijholt** [comment] 2015-06-15 10:14
The above doesn't work anymore, should change it into: 
```python
from holoviews.plotting import MPLPlot
MPLPlot.fig_rcparams={'axes.labelsize':14, 'axes.titlesize':14}
```

**Comment by vascotenner** [comment] 2015-10-08 10:33
How can I set these style options now? I'm already trying this for 20min, quite frustrating.

**Comment by philippjfr** [comment] 2015-10-08 14:10
What's exactly is the issue? This works for me:

```python
%%opts Image [fontsize={'title':20, 'xlabel':20, 'ylabel':25, 'ticks':7}]
hv.Image(np.random.rand(10,10), group='A')
```

and so does this:

```python
%%opts Image [fontsize=10]
hv.Image(np.random.rand(10,10), group='A')
```
