### ISSUE TITLE
Different sized grid columns with `shared_yaxis=True`

### ISSUE THREAD

**Issue by toddrjen** [ioam/holoviews#2569] opened 2018-04-16 23:58 UTC
By default, a `GridSpace` has no axis labels in its plots.  The method I found to fix this is to use `shared_yaxis=True` and `shared_xaxis=True` options.  The problem is that `shared_yaxis=True` results in the two grid columns with different widths.

Here is an example:

```Python
%%output size=300
%%opts GridSpace [shared_yaxis=True]

var1 = ['Arthur', 'Galahad']
var2 = ['duck', 'newt']
var1, var2 = zip(*product(var1, var2))
vals = np.random.random(len(var1))

ds = hv.Dataset(zip(var1, var2, vals, err), ['var1', 'var2'], ['vals'])

mybars = ds.to(hv.Bars, ['var1'], ['vals'], groupby=['var2'])
mybars.grid('var2')
```

The result:

![grid_space](https://user-images.githubusercontent.com/2272878/38841032-59caaabe-41b0-11e8-896f-ca01463a21f8.png)

Note the left grid item is much wider than the right one.

**Comment by philippjfr** [comment] 2018-05-04 18:31
Thanks for reporting this, this is a duplicate of https://github.com/ioam/holoviews/issues/1025. It's caused by the fact that sizing in bokeh includes the axes, and since it is impossible to know ahead of time how wide an axis is it is currently not possible to set the sizes appropriately.

**Closed by philippjfr** 2018-05-04 18:31 UTC
