### ISSUE TITLE
Documentation: function arguments ill-documented throughout

### ISSUE THREAD

**Issue by TomBugnon** [ioam/holoviews#2985] opened 2018-09-04 17:47 UTC
Hi,

I find that throughout the documentation, function arguments are not explicited, or at best very sparsely. 

One example among others could be the `hv.DynamicMap.groupby` function, the docstring of which reads:

```python
    def groupby(self, dimensions=None, container_type=None, group_type=None, **kwargs):
        """
        Implements a dynamic version of a groupby, which will
        intelligently expand either the inner or outer dimensions
        depending on whether the container_type or group_type is dynamic.

        To apply a groupby to a DynamicMap the dimensions, which are
        expanded into a non-dynamic type must define a fixed sampling
        via the values attribute.

        Using the dynamic groupby makes it incredibly easy to generate
        dynamic views into a high-dimensional space while taking
        advantage of the capabilities of NdOverlay, GridSpace and
        NdLayout types to visualize more than one Element at a time.
        """
```
What are the functions of each argument? What types are expected? What are the allowed values, eg for `group_type` (the online doc only gives `hv.NdOverlay` as an example)? What are the default values ? What do the `kwargs` become? The only way to know seems to be digging through the code, or trial and error...

This project is great but because of the poor documentation I find it so far extremely hard to use it in a flexible way, beyond the examples given in the tutorials. I am aware this project is a fairly young endeavor and is still growing, but wouldn't it be time for a major refurbishment of the docstrings according to the [Google Style](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html)?

This is a significant effort but I think it would be tremendously helpful for the users.

Cheers, T

**Comment by philippjfr** [comment] 2018-09-04 18:04
>This project is great but because of the poor documentation I find it so far extremely hard to use it in a flexible way, beyond the examples given in the tutorials. I am aware this project is a fairly young endeavor and is still growing, but wouldn't it be time for a major refurbishment of the docstrings according to the Google Style?

Yes, I think this is one of the most important and helpful things we could do for users and I've been planning exactly that. The main issue is of course the amount of effort and time required. I'll close this issue as a duplicate of https://github.com/ioam/holoviews/issues/2322 but please chime in there if you have any ideas or would be happy to contribute.

**Closed by philippjfr** 2018-09-04 18:04 UTC

**Comment by TomBugnon** [comment] 2018-09-04 18:33
Thank you !
