### ISSUE TITLE
.sample incorrect key_dimension values

### ISSUE THREAD

**Issue by basnijholt** [ioam/holoviews#65] opened 2015-05-12 15:15 UTC
```python
d={x: (z1 * hv.VLine(x) + z1.sample(B=x) )
     for x in np.linspace(0.2, 0.8, 10)}
hv.Overlay.collate(d, key_dimensions=['B']).cols(2)
```

gives me:
![screen shot 2015-05-12 at 17 13 23](https://cloud.githubusercontent.com/assets/6897215/7590754/57995a74-f8ca-11e4-976e-fc053b9704e0.png)

In the left graph the ticks on the x-axis are incorrect. These are the values that I gave in with: ``hv.Dimension('Chemical potential', unit='meV', range=(0, 35))``.

**Comment by philippjfr** [comment] 2015-05-12 15:20
Good catch will have a look.

**Comment by philippjfr** [comment] 2015-05-12 15:24
As far as I can tell this was fixed by acd6e4529f989. Try pulling the latest version and let me know if you can still reproduce this bug.

**Comment by philippjfr** [comment] 2015-05-12 15:29
That was only concerning the sampling issue. The issue with the axes we addressed previously in https://github.com/ioam/holoviews/issues/42, but I haven't yet acted on it. Will hopefully get around to that today.

**Comment by basnijholt** [comment] 2015-05-12 15:32
Yes, that fixed it. I had already installed the latest master but forgot to reload...

Is it possible to plot the same in the same range as the graph that you're sampling? The axis are still from 0 to 35.

**Comment by philippjfr** [comment] 2015-05-12 15:36
As I said the ``situate_axes`` plot option on Image should do it. The issue is that our entire normalization system currently doesn't allow you to independently control whether the axes ranges or just the Raster luminance values are shared and since it's often pretty annoying for Images to embed in a much larger space we added the ``situate_axes`` plot option to make that behavior optional. After the discussions in https://github.com/ioam/holoviews/issues/49 and https://github.com/ioam/holoviews/issues/52, we no longer think that is a good idea but have yet to act on the conclusions we've come up with.

**Comment by basnijholt** [comment] 2015-05-12 15:44
Yes that is a possible solution, but is there no other way?

My understanding was that in ``Dimension(nane, range(min, max)`` I put the outer values of that dimension, or am I mistaken?

**Comment by philippjfr** [comment] 2015-05-12 15:48
The Dimension range is basically the space that the values along that Dimension lives in. So yes your understanding is correct and as I keep saying Image currently has special treatment in the way it handles those ranges, ignoring them unless ``situate_axes`` is enabled. We will get rid of this special handling but for now your options are either not to supply the Dimension.range or to enable ``situate_axes`` on Image.

**Closed** 2015-05-14 22:40 UTC
