### ISSUE TITLE
ErrorBars not compatible with muiti-level Bars axis

### ISSUE THREAD

**Issue by toddrjen** [ioam/holoviews#2564] opened 2018-04-16 12:55 UTC
With `Bars`, you can create a two-level X-axis with the Bokeh backend:

```Python
var1 = ['Arthur', 'Galahad']
var2 = ['duck', 'newt']
var1, var2 = zip(*product(var1, var2))
vals = np.random.random(len(var1))
err = np.random.random(len(var1))

mybars = hv.Bars(zip(var1,var2, vals), ['var1', 'var2'], 'vals')
mybars
```
And you can use you can use `Bars` with `ErrorBars`:

```Python
myerr = hv.Bars(zip(var1, vals), 'var1', 'vals') * hv.ErrorBars(zip(var1, vals, err), 'var1', ['vals', 'err'])
myerr
```

But trying to use an `ErrorBars` with a two-level `Bars` returns an error:

```Python
my2err = hv.Bars(zip(var1, var2, vals), ['var1', 'var2'], 'vals') * hv.ErrorBars(zip(var1, var2, vals, err), ['var1', 'var2'], ['vals', 'err'])
my2err
```

```
TypeError                                 Traceback (most recent call last)
~/bin/anaconda3/envs/dataproc/lib/python3.6/site-packages/IPython/core/formatters.py in __call__(self, obj, include, exclude)
    968 
    969             if method is not None:
--> 970                 return method(include=include, exclude=exclude)
    971             return None
    972         else:

~/bin/anaconda3/envs/dataproc/lib/python3.6/site-packages/holoviews/core/dimension.py in _repr_mimebundle_(self, include, exclude)
   1226         combined and returned.
   1227         """
-> 1228         return Store.render(self)
   1229 
   1230 

~/bin/anaconda3/envs/dataproc/lib/python3.6/site-packages/holoviews/core/options.py in render(cls, obj)
   1287         data, metadata = {}, {}
   1288         for hook in hooks:
-> 1289             d, md = hook(obj)
   1290             data.update(d)
   1291             metadata.update(md)

~/bin/anaconda3/envs/dataproc/lib/python3.6/site-packages/holoviews/ipython/display_hooks.py in pprint_display(obj)
    273     if not ip.display_formatter.formatters['text/plain'].pprint:
    274         return None
--> 275     return display(obj, raw=True)
    276 
    277 

~/bin/anaconda3/envs/dataproc/lib/python3.6/site-packages/holoviews/ipython/display_hooks.py in display(obj, raw, **kwargs)
    246     elif isinstance(obj, (CompositeOverlay, ViewableElement)):
    247         with option_state(obj):
--> 248             output = element_display(obj)
    249     elif isinstance(obj, (Layout, NdLayout, AdjointLayout)):
    250         with option_state(obj):

~/bin/anaconda3/envs/dataproc/lib/python3.6/site-packages/holoviews/ipython/display_hooks.py in wrapped(element)
    139         try:
    140             max_frames = OutputSettings.options['max_frames']
--> 141             mimebundle = fn(element, max_frames=max_frames)
    142             if mimebundle is None:
    143                 return {}, {}

~/bin/anaconda3/envs/dataproc/lib/python3.6/site-packages/holoviews/ipython/display_hooks.py in element_display(element, max_frames)
    185         return None
    186 
--> 187     return render(element)
    188 
    189 

~/bin/anaconda3/envs/dataproc/lib/python3.6/site-packages/holoviews/ipython/display_hooks.py in render(obj, **kwargs)
     62         renderer = renderer.instance(fig='png')
     63 
---> 64     return renderer.components(obj, **kwargs)
     65 
     66 

~/bin/anaconda3/envs/dataproc/lib/python3.6/site-packages/holoviews/plotting/bokeh/renderer.py in components(self, obj, fmt, comm, **kwargs)
    243         # Bokeh has to handle comms directly in <0.12.15
    244         comm = False if bokeh_version < '0.12.15' else comm
--> 245         return super(BokehRenderer, self).components(obj,fmt, comm, **kwargs)
    246 
    247 

~/bin/anaconda3/envs/dataproc/lib/python3.6/site-packages/holoviews/plotting/renderer.py in components(self, obj, fmt, comm, **kwargs)
    306             plot = obj
    307         else:
--> 308             plot, fmt = self._validate(obj, fmt)
    309 
    310         data, metadata = {}, {}

~/bin/anaconda3/envs/dataproc/lib/python3.6/site-packages/holoviews/plotting/renderer.py in _validate(self, obj, fmt, **kwargs)
    205         if isinstance(obj, tuple(self.widgets.values())):
    206             return obj, 'html'
--> 207         plot = self.get_plot(obj, renderer=self, **kwargs)
    208 
    209         fig_formats = self.mode_formats['fig'][self.mode]

~/bin/anaconda3/envs/dataproc/lib/python3.6/site-packages/holoviews/plotting/bokeh/renderer.py in get_plot(self_or_cls, obj, doc, renderer)
    144             doc = Document() if self_or_cls.notebook_context else curdoc()
    145         doc.theme = self_or_cls.theme
--> 146         plot = super(BokehRenderer, self_or_cls).get_plot(obj, renderer)
    147         plot.document = doc
    148         return plot

~/bin/anaconda3/envs/dataproc/lib/python3.6/site-packages/holoviews/plotting/renderer.py in get_plot(self_or_cls, obj, renderer)
    188             plot_opts = self_or_cls.plot_options(obj, self_or_cls.size)
    189             plot = self_or_cls.plotting_class(obj)(obj, renderer=renderer,
--> 190                                                    **plot_opts)
    191             defaults = [kd.default for kd in plot.dimensions]
    192             init_key = tuple(v if d is None else d for v, d in

~/bin/anaconda3/envs/dataproc/lib/python3.6/site-packages/holoviews/plotting/plot.py in __init__(self, overlay, ranges, batched, keys, **params)
    883 
    884         # Apply data collapse
--> 885         self.hmap = self._apply_compositor(self.hmap, ranges, self.keys)
    886         self.map_lengths = Counter()
    887         self.group_counter = Counter()

~/bin/anaconda3/envs/dataproc/lib/python3.6/site-packages/holoviews/plotting/plot.py in _apply_compositor(self, holomap, ranges, keys, dimensions)
    912                                         for key, slckey in zip(keys, sliced_keys) if slckey in holomap.data.keys()])
    913         else:
--> 914             mapwise_ranges = self.compute_ranges(holomap, None, None)
    915             frame_ranges = OrderedDict([(key, self.compute_ranges(holomap, key, mapwise_ranges))
    916                                         for key in holomap.data.keys()])

~/bin/anaconda3/envs/dataproc/lib/python3.6/site-packages/holoviews/plotting/plot.py in compute_ranges(self, obj, key, ranges)
    373             if (not (axiswise and not isinstance(obj, HoloMap)) or
    374                 (not framewise and isinstance(obj, HoloMap))):
--> 375                 self._compute_group_range(group, elements, ranges)
    376         self.ranges.update(ranges)
    377         return ranges

~/bin/anaconda3/envs/dataproc/lib/python3.6/site-packages/holoviews/plotting/plot.py in _compute_group_range(group, elements, ranges)
    433             if isinstance(el, (Empty, Table)): continue
    434             for dim in el.dimensions('ranges', label=True):
--> 435                 dim_range = el.range(dim)
    436                 if dim not in group_ranges:
    437                     group_ranges[dim] = []

~/bin/anaconda3/envs/dataproc/lib/python3.6/site-packages/holoviews/element/chart.py in range(self, dim, data_range)
    102             else:
    103                 pos_error = neg_error
--> 104             lower = np.nanmin(mean-neg_error)
    105             upper = np.nanmax(mean+pos_error)
    106             return util.dimension_range(lower, upper, dim)

TypeError: unsupported operand type(s) for -: 'str' and 'float'
```

**Comment by jlstevens** [comment] 2018-04-16 16:50
Marking this as a bug. Ideally ``ErrorBars`` should work here but if there *is* a good reason it can't (which I don't think there is), there would need to be a better exception than that to explain why.

**Comment by philippjfr** [comment] 2018-04-16 17:28
This is very much not a bug although the error is indeed problematic. In order for this to work we will have to implement my suggestion in https://github.com/ioam/holoviews/issues/1668, which I think is quite sensible and should be straightforward to implement. However it will require a little bit of discussion and further documentation as it is a change in behavior which has the potential to confuse users.

**Comment by philippjfr** [comment] 2018-11-08 03:47
I'll close since #1688 covers the issue.

**Closed by philippjfr** 2018-11-08 03:47 UTC
Labels: enhancement
