### ISSUE TITLE
When groupby a mix of numbers and letters, it doesn't work, but doesn't error

### ISSUE THREAD

**Issue by ahuang11** [ioam/holoviews#2820] opened 2018-06-22 17:01 UTC
Two issues here: 

1. mix letters and numbers and the one with the number fails to show anything in holoplot with and without `.layout()`
![image](https://user-images.githubusercontent.com/15331990/41789030-a4f100a2-7602-11e8-9bc5-015d2944b865.png)

If you do it thru the `hv.Dataset.to.curve().layout()` method, it works
![image](https://user-images.githubusercontent.com/15331990/41789141-1933af0a-7603-11e8-8029-bd67d096b4a0.png)

2.  But if you remove the `.layout` the third item in the drop down doesn't respond.
![image](https://user-images.githubusercontent.com/15331990/41789166-36c4f308-7603-11e8-8a97-90f5e280a7e3.png)

```
df1 = pd.DataFrame(index=[1, 2, 3, 4])
df1['id'] = 'A'
df1['x'] = [1, 2, 3, 4]
df1['y'] = [1, 2, 3, 4]

df2 = df1.copy()
df2['id'] = 'B'
df2['y'] *= -1

df3 = df2.copy()
df3['id'] = 3
df3['x'] *= -1

df = pd.concat([df1, df2, df3])
df.holoplot('x', 'y', groupby='id', width=350).layout('id')
hv.Dataset(df).to.curve('x', 'y', 'id')
```

**Comment by ahuang11** [comment] 2018-06-22 17:05
Oh I guess if I do `df['id'] = df.id.astype(str)` it works as expected, but maybe the example above should raise an error by somehow detecting this?
![image](https://user-images.githubusercontent.com/15331990/41789293-a5964430-7603-11e8-97b7-221638f56943.png)

**Comment by philippjfr** [comment] 2018-06-22 17:11
The groupby works just fine, the issue is in the dropdown widget, so this is a duplicate of https://github.com/ioam/holoviews/issues/1059

**Closed by philippjfr** 2018-06-22 17:11 UTC
