### ISSUE TITLE
Bokeh backend not loading on MacOSX (for v1.6)

### ISSUE THREAD

**Issue by chrisjsewell** [ioam/holoviews#809] opened 2016-08-09 20:25 UTC
I have just tried installing holoviews via conda on OSX (Yosemite, 10.10.5);

`conda create -n holotest -c ioam holoviews bokeh`

but when I try loading in the notebook, I get:

```
import holoviews as hv
hv.notebook_extension('bokeh')

Warning: Unrecognized resources bokeh
```
If I downgrade holoviews to v1.5.0 and bokeh to v0.11.1 though, everything works fine. 

Here's the full install list it it helps, ta

```
    appnope:            0.1.0-py27_0          
    backports:          1.0-py27_0            
    backports_abc:      0.4-py27_0            
    bokeh:              0.12.1-py27_0         
    configparser:       3.5.0-py27_0          
    cycler:             0.10.0-py27_0         
    decorator:          4.0.10-py27_0         
    entrypoints:        0.2.2-py27_0          
    freetype:           2.5.5-1               
    functools32:        3.2.3.2-py27_0        
    futures:            3.0.5-py27_0          
    get_terminal_size:  1.0.0-py27_0          
    holoviews:          1.6.1-py27_0      ioam
    ipykernel:          4.3.1-py27_0          
    ipython:            5.0.0-py27_0          
    ipython_genutils:   0.1.0-py27_0          
    ipywidgets:         4.1.1-py27_0          
    jinja2:             2.8-py27_1            
    jsonschema:         2.5.1-py27_0          
    jupyter:            1.0.0-py27_3          
    jupyter_client:     4.3.0-py27_0          
    jupyter_console:    5.0.0-py27_0          
    jupyter_core:       4.1.0-py27_0          
    libpng:             1.6.22-0              
    markupsafe:         0.23-py27_2           
    matplotlib:         1.5.1-np111py27_0     
    mistune:            0.7.2-py27_1          
    mkl:                11.3.3-0              
    nbconvert:          4.2.0-py27_0          
    nbformat:           4.0.1-py27_0          
    notebook:           4.2.2-py27_0          
    numpy:              1.11.1-py27_0         
    openssl:            1.0.2h-1              
    param:              1.4.1-py27_0      ioam
    path.py:            8.2.1-py27_0          
    pathlib2:           2.1.0-py27_0          
    pexpect:            4.0.1-py27_0          
    pickleshare:        0.7.3-py27_0          
    pip:                8.1.2-py27_0          
    prompt_toolkit:     1.0.3-py27_0          
    ptyprocess:         0.5.1-py27_0          
    pygments:           2.1.3-py27_0          
    pyparsing:          2.1.4-py27_0          
    pyqt:               4.11.4-py27_4         
    python:             2.7.12-1              
    python-dateutil:    2.5.3-py27_0          
    python.app:         1.2-py27_4            
    pytz:               2016.6.1-py27_0       
    pyyaml:             3.11-py27_4           
    pyzmq:              15.3.0-py27_0         
    qt:                 4.8.7-4               
    qtconsole:          4.2.1-py27_0          
    readline:           6.2-2                 
    requests:           2.10.0-py27_0         
    setuptools:         25.1.6-py27_0         
    simplegeneric:      0.8.1-py27_1          
    singledispatch:     3.4.0.3-py27_0        
    sip:                4.18-py27_0           
    six:                1.10.0-py27_0         
    sqlite:             3.13.0-0              
    ssl_match_hostname: 3.4.0.2-py27_1        
    terminado:          0.6-py27_0            
    tk:                 8.5.18-0              
    tornado:            4.4.1-py27_0          
    traitlets:          4.2.2-py27_0          
    wcwidth:            0.1.7-py27_0          
    wheel:              0.29.0-py27_0         
    yaml:               0.1.6-0               
    zlib:               1.2.8-3               

```

**Comment by jlstevens** [comment] 2016-08-10 11:24
I'm working on Mac OSX (10.11.6) using HoloViews 1.6 and the latest bokeh (0.12.1) and it seems to be working correctly. Have you tried updating bokeh and then using 1.6?

If that still doesn't work, I think there will probably be a more useful exception if you try:

```python
from holoviews.plotting import bokeh
```

Hope that helps!

**Comment by jlstevens** [comment] 2016-09-16 20:42
@chrisjsewell Have you had any luck?

This is an important issue to address if it is still unresolved, otherwise I hope I can close it!

**Comment by philippjfr** [comment] 2016-10-21 11:28
Closing since we haven't heard back in a long time. Please reopen if necessary.

**Closed by philippjfr** 2016-10-21 11:28 UTC

**Comment by jakevdp** [comment] 2017-04-11 18:32
I just ran into this with a fresh install off of conda-forge. I'm unable to get the Bokeh backend working.

I'm on OSX 10.12; to reproduce this:

```
$ conda create -n holoviews python=3.5 jupyter notebook numpy bokeh
$ source activate holoviews
$ conda install -c conda-forge holoviews
```
In the notebook now
```python
In [1]: import holoviews
        print(holoviews.__version__)
1.6.2

In [2]: import bokeh
        print(bokeh.__version__)
0.12.5

In [3]: holoviews.notebook_extension('bokeh')
/Users/jakevdp/anaconda/envs/holoviews/lib/python3.5/site-packages/bokeh/util/deprecation.py:34: BokehDeprecationWarning: MPL compatibility can no longer be successfully maintained, and is now deprecated. All MPL compat functions will be removed completely on the release of Bokeh 1.0. See http://bokeh.pydata.org/en/latest/docs/releases/0.12.5.html for more information
  warn(message)
WARNING:root:notebook_extension: HoloViews bokeh backend could not be imported, ensure bokeh is installed.

**Warning:** Unrecognized resources bokeh

HoloViewsJS successfully loaded in this cell.
```

Any help would be appreciated – I'm giving a talk tomorrow evening at Facebook Seattle comparing various vis libraries in Python, and I'd like to show Holoviews' full capabilities :smile:

**Comment by philippjfr** [comment] 2017-04-11 18:42
>I just ran into this with a fresh install off of conda-forge. I'm unable to get the Bokeh backend working.

We're a bit behind with a release and got caught out by various changes in bokeh. We're planning to release tomorrow or Thursday but until then I can only recommend a dev install with ``conda install -c ioam/label/dev holoviews`` or installing from current master.

**Comment by philippjfr** [comment] 2017-04-11 18:46
>Any help would be appreciated – I'm giving a talk tomorrow evening at Facebook Seattle comparing various vis libraries in Python, and I'd like to show Holoviews' full capabilities 

Awesome, maybe to see the full capabilities of HoloViews you could demo a small dashboard using datashader and holoviews, these two would make good candidates:

https://anaconda.org/philippjfr/stockexplorer/notebook
https://anaconda.org/jbednar/nyc_taxi-paramnb/notebook
