### ISSUE TITLE
Making interactive matplotlib figures without Jupyter

### ISSUE THREAD

**Issue by jbednar** [ioam/holoviews#1126] opened 2017-02-11 15:16 UTC
Nearly all of our examples use Jupyter notebooks for convenience, but the core machinery of HoloViews does not depend on Jupyter at all.  At some point I think we had an example of using HoloViews with a GUI-based Matplotlib backend, popping up an interactive Matplotlib window outside of the browser, but I can't find it now.  We should add one and link to it prominently, to make it clear that we don't depend on Jupyter or a web browser.

That said, @philippjfr notes that a fix we put in to avoid issues with mpl's default qt backend causing problems in the browser (we now force the backend to 'agg'), is currently preventing this usage of HoloViews.  It _should_ be a matter of moving that fix into the renderer so that it is run only in the notebook, but we'll have to investigate that.

**Comment by thoth291** [comment] 2017-02-11 16:43
Thank you, @jbednar for opening this. We had a battle around my colleagues about what plotting tool to make a default in my company.
There were some for using bokeh, but it was too low level for some people. 
We also had plotly proposed and it had more success cause it has 3D out of the box. 
And there were people who develop standalone scripts and for them only matplotlib is an option. 
I tried to jump in with holoviews - but to them it seems to look more like a 4th option rather than a generalization of all above. Situation also got worse cause developers of standalone scripts can't use holoviews for their work.

Not surprisingly, but precisely those developers were the ones who were the most enthusiastic about the holoviews, but this ability to be independent of Jupyter made it no go option. 

I personally think that holoviews is on the right track. Just a nice matplotlib-like gallery is missing.

P. S. 
That would be great to separate back-end from matplotlib core package. 
Here is the link how mayavi used X3D format to render their elements in 3D in the browser: http://docs.enthought.com/mayavi/mayavi/tips.html

**Comment by thoth291** [comment] 2017-02-11 16:48
> but this **disability** to be independent of Jupyter made it no go option.

**Comment by jlstevens** [comment] 2017-02-12 18:01
Just to say there is an example of using matplotlib+holoviews without Jupyter [here](https://github.com/ioam/holoviews-contrib/blob/master/scripts/matplotlib_export.py). We might have once had an example that also pops up a matplotlib window but I suspect that was a very long time ago! 

I'm not sure what would be necessary to pop up a window, but it probably isn't too hard. If nothing else, you can always grab a figure object from holoviews which should should just be able to ``show``.

**Comment by philippjfr** [comment] 2017-02-12 18:23
>I'm not sure what would be necessary to pop up a window, but it probably isn't too hard. If nothing else, you can always grab a figure object from holoviews which should should just be able to show.

Not currently because we're forcing the backend to agg. I also don't think it'll be too hard but it's currently not possible as far as I can tell.

**Comment by jlstevens** [comment] 2017-02-12 18:25
If there a way to disable the backend switch to agg? I certainly would want it to remain the default but there ought to be a way to disable it as well.

**Comment by philippjfr** [comment] 2017-02-12 18:26
We really should only be setting it when loading a backend with the notebook extension.

**Comment by jlstevens** [comment] 2017-02-12 18:48
What about unit tests, especially the SHA based tests?

**Comment by philippjfr** [comment] 2017-02-12 18:50
They'll have to do the same before importing from ``holoviews.plotting.mpl``.

**Comment by thoth291** [comment] 2017-02-24 20:33
Is there any update on this issue? How can I get an example of something to work without Jupyter?

**Comment by philippjfr** [comment] 2017-02-24 20:34
@thoth291 I'm going to have a look at this over the weekend. I'll report back asap.

**Comment by thoth291** [comment] 2017-02-24 20:43
Let me know if there is anything will be ready to test - I'm willing to help!

**Comment by philippjfr** [comment] 2017-02-24 23:11
Okay I've had a go at it now and found out what the problem is. HoloViews plots always close figures to avoid accumulating them, I'd suggest we simply add a ``MPLRenderer.show`` method, which displays any holoviews object without closing the figure.

Here's what that might look like (I hacked it for now):

<img width="1421" alt="screen shot 2017-02-24 at 11 10 19 pm" src="https://cloud.githubusercontent.com/assets/1550771/23324578/7dafab1c-fae6-11e6-8548-448893a71e6b.png">

**Comment by philippjfr** [comment] 2017-02-24 23:15
``BokehRenderer.show`` could create the plot and try to open it in a browser.

**Comment by jlstevens** [comment] 2017-02-24 23:39
A renderer ``show`` method seems like a fairly general concept for pure Python users. I'm happy to see it supported - for ``bokeh`` opening a browser tab would make sense.

**Comment by thoth291** [comment] 2017-02-25 20:30
Thank you @philippjfr ! Is it already available anywhere? Or should I wait for it to be more stable?
Can I open multiple plot windows simultaneously?
And what will happen with bokeh if I'll ask to show few of them simultaneously? Few browsers will open? I guess it's OK.

BTW, will renderer.save() to work for bokeh and save the resulted plot? Is there any way to save it into a object so that I could dump it to a file and then bring it back when needed without re-rendering?

P.S. I'm sorry for so many detailed questions - trying to be specific - but may accidentally become annoying.

**Comment by jlstevens** [comment] 2017-04-27 15:21
@philippjfr The PR was merged so think this issue can be closed now.

**Closed** 2017-06-27 00:46 UTC
Labels: feature, mpl
