### ISSUE TITLE
Suppress redundant legends by default?

### ISSUE THREAD

**Issue by jbednar** [ioam/holoviews#2632] opened 2018-04-27 17:07 UTC
I'm not sure how feasible it is to detect when a legend would be redundant, but it would be nice if I didn't have to explicitly turn off the legend with `show_legend=False` in plots like:

![image](https://user-images.githubusercontent.com/1695496/39375290-6f77bc4c-4a13-11e8-96f6-faa95414fa2f.png)

where the category for each color is already labeled along the *x* axis.

**Comment by philippjfr** [comment] 2018-11-05 00:09
Duplicate of https://github.com/ioam/holoviews/issues/2565

**Closed by philippjfr** 2018-11-05 00:09 UTC
Labels: feature
