### ISSUE TITLE
Bokeh plot with tool instances cannot be redisplayed

### ISSUE THREAD

**Issue by thoth291** [ioam/holoviews#1590] opened 2017-06-21 12:21 UTC
This [notebook](https://anaconda.org/thoth/hv_export_and_tools) illustrates issues like:
1. Order of multiple `hv.notebook_extension` matters
2. Loosing style, size and other information during switching backends
3. Replotting the same figure within the notebook causes HoverTool error with failure of the figure display
4. Cannot export holomap as GIF file.

Point number 2 is expected I guess.

Could you please advise?

**Comment by jlstevens** [comment] 2017-06-21 12:26
This is something to look into but my first comment is that you can do:

```python
hv.notebook_extension('matplotlib', 'bokeh')
```

Which I would highly recommend over using ``hv.notebook_extension('matplotlib')`` and ``hv.notebook_extension('bokeh')`` in separate calls to ``notebook_extension``.

Hopefully that helps and if it does, we need to add a section about this to the user guide.

**Comment by jlstevens** [comment] 2017-06-21 12:29
> Cannot export holomap as GIF file.

I believe you need imagemagick to do this - GIFs are only supported by the matplotlib backend and that in turn relies on ImageMagick to generate gifs. Matplotlib uses [this animation writer](https://matplotlib.org/api/_as_gen/matplotlib.animation.ImageMagickWriter.html) when generating GIF and it won't work unless imagemagick is available on your system.

**Comment by jlstevens** [comment] 2017-06-21 12:34
Lastly I should note that ``hv.notebook_extension('matplotlib', 'bokeh')`` will activate matplotlib and enable bokeh (so you can switch to it) whereas ``hv.notebook_extension( 'bokeh', 'matplotlib')`` activates bokeh and enables matplotlib (so you can switch to it using ``%output`` or ``%%output``). The order used is supposed to matter in this case. 

If you are on master/a recent dev release you can also use ``hv.extension`` which is just the same thing as ``hv.notebook_extension`` (but shorter).

**Comment by thoth291** [comment] 2017-06-21 13:31
Thanks, @jlstevens .
This call doesn't work right:
hv.notebook_extension('matplotlib','bokeh')

But this call does the right thing with the plot:
hv.notebook_extension('bokeh','matplotlib')

So I think that the bug is still there.

I also installed imagemagic:
```
convert --version
Version: ImageMagick 7.0.3-6 Q16 x86_64 2017-01-11 http://www.imagemagick.org
Copyright: Copyright (C) 1999-2016 ImageMagick Studio LLC
License: http://www.imagemagick.org/script/license.php
Features: Cipher DPC HDRI 
Delegates (built-in): x 
```
But still don't get any GIF files generated.

Any more advises?

**Comment by jlstevens** [comment] 2017-06-21 14:07
Does this do the right thing?

```python
hv.notebook_extension('matplotlib','bokeh')
%output backend='bokeh'
```

**Comment by thoth291** [comment] 2017-06-21 15:06
No - it doesn't. If you'll look at the notebook - this is exactly what I'm doing.

**Comment by jlstevens** [comment] 2017-06-21 15:52
The  notebook you linked to above still doesn't combine the strings 'matplotlib' and 'bokeh' into a single ``hv.notebook_extension`` call. Perhaps you have a more recent version and need to update the online one?

**Comment by thoth291** [comment] 2017-06-21 17:10
As I commented above - combining doesn't change things, that's why I never pushed it out.

**Comment by jlstevens** [comment] 2017-06-21 17:27
> As I commented above - combining doesn't change things, that's why I never pushed it out.

That isn't what I observe [after running it](https://anaconda.org/jlstevens/hv_export_and_tools/notebook). It works correctly when combined but not when run multiple times (which isn't recommended).

**Comment by thoth291** [comment] 2017-06-22 01:13
I probably wasn't clear enough.
Combining doesn't remove the issue of the order.
As I wrote [here above](https://github.com/ioam/holoviews/issues/1590#issuecomment-310079154):
>This call doesn't work right:
>
>     hv.notebook_extension('matplotlib','bokeh')
>
>But this call does the right thing with the plot:
>
>     hv.notebook_extension('bokeh','matplotlib')

So the order still matters - and that's what I believe is real issue.
To me - order of the extensions should not matter if you do

    %%output backend='bokeh'

explicitly.

**Comment by philippjfr** [comment] 2017-06-22 01:22
It would be very helpful if you could include your holoviews version with every issue.

**Comment by jlstevens** [comment] 2017-06-22 01:38
@philippjfr I think the version is shown in the notebook link above.

**Comment by philippjfr** [comment] 2017-06-22 01:40
Oops my apologies @thoth291, I had looked at that earlier but it somehow slipped my mind.

**Comment by thoth291** [comment] 2017-06-22 02:45
Yes. The version is this one: 1.7.0-x-g0c9133718
I'm always trying to get the latest master from the github repo.

Essentially issues 1) and 3) are weird. And the issue 4) is suspicious a bit, cause it might be something to do with dependencies, but I reinstalled everything relevant twice and still getting the same issue of GIF not being created.

Thank you!

**Comment by philippjfr** [comment] 2017-10-27 22:56
Sorry looking back at this I think I was just confused. The order of ``hv.extension`` does matter, deliberately so since first extension provided will be set as active and if you call hv.extension a second time it will switch. We also can't auto-translate options between backends atm, and discussion on that would have to be it's own issue. The gif issue is also separate but the answer is that you need to specify gif as the format.

The HoverTool issue I'm going to be dealing with shortly.

**Comment by philippjfr** [comment] 2017-10-27 22:59
Actually that last issue is a duplicate of https://github.com/ioam/holoviews/issues/1851 so I'll close this.

**Closed by philippjfr** 2017-10-27 22:59 UTC
Labels: bug

**Comment by thoth291** [comment] 2017-10-28 04:36
@philippjfr, thank you for your reply! Could you please point to the issues you are mentioned [here](https://github.com/ioam/holoviews/issues/1590#issuecomment-340116263):
>auto-translate options between backends

and

>The gif issue is also separate but the answer is that you need to specify gif as the format.

**Comment by philippjfr** [comment] 2017-10-28 12:57
>auto-translate options between backends

If you want you can open a separate issue for this, but we have in the past very deliberately decided this is not feasible.

>The gif issue is also separate but the answer is that you need to specify gif as the format.

In your example simply specify the format like this:

```python
hmap=hv.HoloMap({k:show_peaks(data,xs,[k],extents) for k in range(75,86)})
rendererDynamicMpl.save(hmap,'hmapDynamicMpl', 'gif')
```

In future it would be great if you could separate issues into atomic chunks that can be dealt with separately with a code sample to isolate just the particular issue that is described. Issues that describe a bunch of different issues cannot be appropriately prioritized and I'll end up closing them.
