### ISSUE TITLE
DynamicMap frozen

### ISSUE THREAD

**Issue by vascotenner** [ioam/holoviews#706] opened 2016-06-03 09:34 UTC
Move slider, plot does not respond. Some error message is printed in the javascript console.

Here a minimal example to reproduce the bug. Overlaying a DMap comprising a NdOverlay over an Image does not work:

``` python
def curve(N): # Positional keyword arguments are fine
    xs = np.linspace(-10,10)
    return hv.Curve((xs,xs**(N)/(xs**(N)).max()))

def curves(N, radius=0.5): # Positional keyword arguments are fine
    return hv.HoloMap({n: curve(n+N)
             for n in range(0,3)}, kdims=['n']).overlay()

dmap = hv.DynamicMap(curve, kdims=[hv.Dimension('N', range=(0,10))])
dmap2 = hv.DynamicMap(curves, kdims=[hv.Dimension('N', range=(0,10))])
bg = hv.Image(np.random.random((10,10)))
```
# Works:

```
bg * dmap #single curve
```
# Does not work

```
bg * dmap2 #NdOverlay of curves
```

**Comment by vascotenner** [comment] 2016-06-03 10:02
It seems to be somewhat related with rational numbers. I cannot reproduce this issue with:
```
def shapes(N, radius=0.5): # Positional keyword arguments are fine
    paths = [hv.Path([[(N*50.+radius*np.sin(a), radius*np.cos(a)) 
                        for a in np.linspace(-np.pi, np.pi, n+2)]], 
                     extents=(-1,-1,10,10)) 
             for n in range(3,4)]
    return hv.Overlay(paths)
dmap = hv.DynamicMap(shapes, kdims=[hv.Dimension('N', range=(0.00001*np.round(np.pi,5),0.01)), hv.Dimension('radius', range=(0.5,1))])
```

But I can with
```
dmap = hv.DynamicMap(shapes, kdims=[hv.Dimension('N', range=(0.00001*np.round(np.pi,6),0.01)), hv.Dimension('radius', range=(0.5,1))])
```

Strangly, I also encounter this problem with:
```
dmap = hv.DynamicMap(band_image, kdims=[hv.Dimension('gamma',range=(0.00, 0.05)),
                                        #hv.Dimension('kappa', range=(-0.1,0.1)),
                                        #hv.Dimension('ma', range=(-0.1,0.1)),
                                        hv.Dimension('kappa', range=(-0.,0.1)),
                                        hv.Dimension('ma', range=(-0.,0.1)),
                                        hv.Dimension('neff', range=(3.20,3.30)),
                                        hv.Dimension('a0', range=(515,516)),
                                        hv.Dimension('da', range=(-0.0,0.05)),
                                       ])
```

Where all the ranges are "normal" numbers

**Comment by jlstevens** [comment] 2016-06-13 13:55
Thanks for reporting this!

I'll have a go investigating this later today.

**Comment by philippjfr** [comment] 2016-06-17 14:09
Sounds like the same issue described in https://github.com/ioam/holoviews/issues/601, once confirmed we can close this issue as a duplicate.

**Comment by vascotenner** [comment] 2016-06-29 15:10
I agree that one of the bugs is a duplicate of #601, but the second problem persists:
I create a dmap consisting of an overlay of 6 curves. Such dmap is overlayed over an Image. Two of such combinations are shown in a layout. When moving sliders to fast, it sometimes does not respond:

````python
Warning: HoloViews callback returned unexpected data for key: ( [0,0,0.00549,3.2989] ) with the following trace in the javascript console:

"Exception                                 Traceback (most recent call last)"
2
:
"<ipython-input-28-fd65378ed8d8> in <module>()
----> 1 import holoviews;holoviews.plotting.widgets.NdWidget.widgets['d9d1b42e1348429ab581cb4223aed7b6'].update([0,0,0.00549,3.2989])
"
3
:
"/home/tenner/src/holoviews/holoviews/plotting/mpl/widgets.pyc in update(self, key)
     85             fig.canvas.draw_idle()
     86             return ''
---> 87         frame = self._plot_figure(key)
     88         if self.renderer.mode == 'mpld3':
     89             frame = self.encode_frames({0: frame})
"
4
:
"/home/tenner/src/holoviews/holoviews/plotting/mpl/widgets.pyc in _plot_figure(self, idx)
     62     def _plot_figure(self, idx):
     63         with self.renderer.state():
---> 64             self.plot.update(idx)
     65             if self.renderer.mode == 'mpld3':
     66                 figure_format = 'json'
"
5
:
"/home/tenner/src/holoviews/holoviews/plotting/mpl/plot.pyc in update(self, key)
    213         if len(self) == 1 and key == 0 and not self.drawn:
    214             return self.initialize_plot()
--> 215         return self.__getitem__(key)
    216 
    217 
"
6
:
"/home/tenner/src/holoviews/holoviews/plotting/plot.pyc in __getitem__(self, frame)
    200         if not self.dynamic == 'open' and not isinstance(frame, tuple):
    201             frame = self.keys[frame]
--> 202         self.update_frame(frame)
    203         return self.state
    204 
"
7
:
"/home/tenner/src/holoviews/holoviews/plotting/mpl/plot.pyc in update_frame(self, key, ranges)
    226         ranges = self.compute_ranges(self.layout, key, ranges)
    227         for subplot in self.subplots.values():
--> 228             subplot.update_frame(key, ranges=ranges)
    229 
    230         title = self._format_title(key) if self.show_title else ''
"
8
:
"/home/tenner/src/holoviews/holoviews/plotting/mpl/plot.pyc in update_frame(self, key, ranges)
    671             subplot = self.subplots.get(pos)
    672             if subplot is not None:
--> 673                 subplot.update_frame(key, ranges)
    674 
    675 
"
9
:
"/home/tenner/src/holoviews/holoviews/plotting/mpl/element.pyc in update_frame(self, key, ranges, element)
    774 
    775         if isinstance(self.hmap, DynamicMap) and items:
--> 776             raise Exception("Some Elements returned by the dynamic callback "
    777                             "were not initialized correctly and could not be "
    778                             "rendered.")
"
10
:
"Exception: Some Elements returned by the dynamic callback were not initialized correctly and could not be rendered."
```

**Comment by vascotenner** [comment] 2016-06-29 15:17
With the current master, it doesnt work at all. After moving a slider the first time, a frame is updated. Furthermode, an " is outputted.

**Comment by philippjfr** [comment] 2016-06-29 15:22
>With the current master, it doesnt work at all. After moving a slider the first time, a frame is updated. Furthermode, an " is outputted.

I do see the ", which appears to be a bug, but it's working fine for me.

**Comment by philippjfr** [comment] 2016-06-29 15:24
I will try to address the out of bounds issue, which causes things to break today. Once that's resolved it would be helpful if you could test it and see which bugs persist.

**Comment by vascotenner** [comment] 2016-06-29 15:27
With a slightly older version (564d747), at least the quote does not show up. The dmap works fine when I do not overlay it on an Image.

**Comment by philippjfr** [comment] 2016-06-29 15:29
>With a slightly older version (564d747), at least the quote does not show up. The dmap works fine when I do not overlay it on an Image.

Could you paste exactly what you're trying because everything I've tried works okay apart from the out-of-bounds error when you hit pi and the stray quote.

**Comment by vascotenner** [comment] 2016-07-29 10:21
Snippets as post in the gitter channel on 20160629:
```python
%%opts Overlay [aspect=.5,, invert_yaxis=True]
%%opts Layout [aspect_weight=0.9]
%%output size=200

kdims_ranges = [hv.Dimension('gamma',range=(0.00, 0.03)),
                hv.Dimension('kappa', range=(0,0.01)),
                hv.Dimension('ma', range=(0,0.01)),
                hv.Dimension('neff', range=(3.28,3.35))
                ]

c0 = 299792458. # m/s
neff = 3.21
a0 = 535

def w0(a0=a0, neff=neff): return 2*np.pi*c0/(neff*a0*1e-9) # rad
w0func = w0


class Bandstruct():
    def __init__(self, thetarange=0.4, num=41, orientation=None):
        self.thetas = np.linspace(-thetarange, thetarange, num=num)
        self.orientation = orientation

    def mat_extended(self, theta,y,k,m,y_rad=0,g=0,neff=neff, a0=a0, da=0, orientation=0, **kwargs):
        """Generate a matrix that descibed the coupling between the modes.
        All the parameters are not scaled by w0.

        Params:
        theta   --  The angle of the observed light in radians
        y       --  Backward scattering rate
        k       --  120 angle scattering rate
        m       --  60 angle scattering rate
        y_0     --  NOT USED, Forward scattering rate. This can be partialy be absorbed 
                    in n_eff, see logbook page 237
        y_rad   --  Radiative losses
        g       --  Reduced ohmic losses: ohmic_losses-effective_gain
        y2      --  Scattering rate in x direction
        da      --  Relative elongation along the a direction
        """
        if self.orientation:
            orientation = self.orientation
        a = (np.sqrt(3)/2*a0*1e-9)    
        G_angles = np.array([0,180,60,240,120,300])/180*np.pi
        k_spp = 2*np.pi*np.sqrt(
            np.sum((1/a*np.array([np.cos(G_angles),np.sin(G_angles)])+
                    np.sin(theta)/(neff*a)*np.array([np.cos(orientation),np.sin(orientation)])[:,np.newaxis]
                   )**2, axis=0))

        #including angle
        w0s = c0*k_spp/neff
        #w02 = w0*(1+da/4)#np.sqrt(3)/2*np.sqrt(1+(1+da)**2/4)

        return (np.diagflat(w0s)
                # coupling
                +np.array([[0, y, m, k, k, m],
                           [y, 0, k, m, m, k],
                           [m, k, 0, y, m, k],
                           [k, m, y, 0, k, m],
                           [k, m, m, k, 0, y],
                           [m, k, k, m, y, 0]])
                #losses
                #+1.j*np.array([[(g-y_rad), y_rad,               0,       0],
                #           [y_rad,                  (g-y_rad),  0,       0],
                #           [0,       0,                         (g-y_rad),    y_rad],
                #           [0,       0,                         y_rad,       (g-y_rad)],
                #           ])
                )
    def calculate_peaks_numeric_omega_single(self, theta=0, gamma=0,kappa=0,ma=0,
        neff=neff, a0=a0, da=0, orientation=0, *args, **kwargs):
        " Calulates the resconance frequencies at theta, orientation "
        w0 = w0func(a0, neff)
        return np.sort(np.linalg.eigvals(self.mat_extended(theta=theta, y=gamma*w0,
                        k=kappa*w0,neff=neff, a0=a0, da=da, m=ma*w0, orientation=orientation,
                                                           *args, **kwargs)))

    def calculate_peaks_numeric_omega(self, *args, **kwargs):
        " Calulates the resconance frequencies at different theta"
        omegas = [self.calculate_peaks_numeric_omega_single(theta, *args, **kwargs) for theta in self.thetas]
        return np.array(omegas)

    def calculate_peaks_numeric(self, *args, **kwargs):                                 
        return 2*np.pi*c0*1e9/self.calculate_peaks_numeric_omega(*args,**kwargs)

    def image(self, gamma=0,kappa=0,ma=0,
                neff=neff, a0=a0, da=0, *args, **kwargs):
        #for d in self.calculate_peaks_numeric().T:
        #    print (zip(self.thetas, d))
        names = ['E12','E11','B1','E22','E21','A1']
        return hv.NdOverlay({names[i]: hv.Curve((self.thetas,d), kdims=['Angle'], vdims=['Energy'])
                           for i,d in enumerate(abs(self.calculate_peaks_numeric(gamma,kappa,ma,
                                                                neff, a0, da, *args, **kwargs).T))},
                            kdims=[hv.Dimension('Mode',values=['A1','E21','E22','B1','E11','E12'])]
                            )

bandstruct = Bandstruct()

dmap = hv.DynamicMap(lambda *args: bandstruct.image(*args)[:,:,slice(*overlayed['Hex',0].bounds.lbrt()[1::2])], kdims=kdims_ranges)

overlayed['Hex',90]*dmap
```

Where
```python
> slice(*overlayed['Hex',0].bounds.lbrt()[1::2]) 
slice(1387.8000000000002, 1643.3000000000002, None)
```

And where overlayed[a,b] returns a hv.RGB image

**Comment by vascotenner** [comment] 2016-10-07 12:56
Here a minimal example to reproduce the bug. Overlaying a DMap comprising a NdOverlay over an Image does not work:
```
def curve(N): # Positional keyword arguments are fine
    xs = np.linspace(-10,10)
    return hv.Curve((xs,xs**(N)/(xs**(N)).max()))

def curves(N, radius=0.5): # Positional keyword arguments are fine
    return hv.HoloMap({n: curve(n+N)
             for n in range(0,3)}, kdims=['n']).overlay()

dmap = hv.DynamicMap(curve, kdims=[hv.Dimension('N', range=(0,10))])
dmap2 = hv.DynamicMap(curves, kdims=[hv.Dimension('N', range=(0,10))])
bg = hv.Image(np.random.random((10,10)))
```

# Works:
```
bg * dmap #single curve
```

# Does not work
```
bg * dmap2 #NdOverlay of curves
```

**Comment by philippjfr** [comment] 2016-10-07 12:57
Perfect, thanks a lot @vascotenner. I'll have a look today.

**Comment by philippjfr** [comment] 2016-11-21 15:37
As far as I can tell this was fixed by https://github.com/ioam/holoviews/pull/967. Reopen if it's still not working for you.

**Closed** 2017-02-13 01:16 UTC
Labels: bug
