### ISSUE TITLE
magic parser doesn't process dictionaries with spaces after ":"

### ISSUE THREAD

**Issue by RafalSkolasinski** [ioam/holoviews#874] opened 2016-09-19 15:07 UTC
When setting options via magic parser contains dictionary it fails to process whenever there is space after a colon. Please see following code.

Cell 1 (imports)
```python
import numpy as np
import holoviews as hv
hv.notebook_extension()
```

Cell 2 (doesn't respect fontsize)
```python
%%opts Image [fontsize={'ticks': 50}]
hv.Image(np.random.rand(10, 10))
```

Cell 3 (does respect fontsize)
```python
%%opts Image [fontsize={'ticks':50}]
hv.Image(np.random.rand(10, 10))
```

---
Note:
when working locally with the notebook I got a warning message 
```
WARNING:root:Warning: Ignoring keyword pair that fails to evaluate: 'fontsize={'ticks':,50}'
```
but when working via ``jupyterhub`` there is no warning.

**Comment by philippjfr** [comment] 2016-10-21 11:20
Yes, this a duplicate of #270. Closing.

**Closed by philippjfr** 2016-10-21 11:20 UTC
Labels: duplicate
