### ISSUE TITLE
Text input with slider

### ISSUE THREAD

**Issue by jakirkham** [ioam/holoviews#2178] opened 2017-12-06 06:10 UTC
Would be nice if the slider allowed text input. Thinking of the example in [Gridded Datasets]( http://holoviews.org/getting_started/Gridded_Datasets.html ), would be useful to be able to enter a specific frame in the text box.

**Comment by philippjfr** [comment] 2017-12-08 17:34
I believe this is a duplicate of https://github.com/ioam/holoviews/issues/673.

**Closed by philippjfr** 2017-12-08 17:34 UTC

**Comment by jakirkham** [comment] 2017-12-08 17:42
Ah ok. Thanks for the info. Sorry to dup. Didn't see that one when searching the issue tracker. Will following with that discussion.

**Comment by philippjfr** [comment] 2017-12-08 17:44
No worries, it's buried rather deep. This has stalled for so long, because we have long decided that our widgets should be rewritten properly from scratch, but it's never been much of a priority. It is however one of the blockers for a 2.0 release so it is definitely on the roadmap.

**Comment by jakirkham** [comment] 2017-12-08 17:46
Interesting. Is there an issue describing the sort of changes proposed for widgets somewhere?

**Comment by philippjfr** [comment] 2017-12-08 18:10
Here's a **very** old first draft of a design document: https://github.com/ioam/holoviews/wiki/_Dev-Plan:-Widget-refactor

@jlstevens and I have since discussed this on at least five separate occasions but haven't made notes. @jlstevens Do you think you'll have time at some point to make an updated (and much more detailed) design proposal based on our discussions?

**Comment by jlstevens** [comment] 2017-12-11 20:33
>  Do you think you'll have time at some point to make an updated (and much more detailed) design proposal based on our discussions?

Yes although that isn't the same as saying we have time to implement those plans! :-S
