### ISSUE TITLE
Styles going missing when slicing NdOverlays

### ISSUE THREAD

**Issue by jlstevens** [ioam/holoviews#221] opened 2015-07-18 22:22 UTC
In my work, I am generating an `NdOverlay` where the individual curves are customized by color:

``` python
traces = NdOverlay({float(c):Curve(d)(style={'color':col}) 
                    for c,(d, col) in data.items() }, kdims=['Contrast'])
```

The result has the colors I would expect but it seems the color settings are lost if I slice the NdOverlay. For instance, if I do `traces[3.1:,:]` to eliminate the 3% contrast trace, the `NdOverlay` seems to revert back to the default color cycle.

**Edit:** Fixed example.

**Comment by philippjfr** [comment] 2015-07-19 21:12
Wait I'm assuming that was a mistake but isn't the call in your example, i.e. ``traces()`` doing the clearing? Did you mean to do that or is there an actual bug if you get rid of the call?

**Comment by jlstevens** [comment] 2015-07-19 21:50
Yes sorry! Ignore the call (fixed above in an edit)

**Comment by philippjfr** [comment] 2015-07-25 16:52
Hmm, this is a more general problem to do with inheritance of the ``id`` attributes. By default the id is currently **not** inherited when performing a ``clone`` operation and since the ``__getitem__`` just uses ``clone`` internally that is what happens. Should all ``clone`` operations inherit the id? If so this is an easy fix.

**Comment by philippjfr** [comment] 2015-09-16 13:07
As I said above this is not actually a bug, it's expected behavior. The question is do we want to change it? You could have avoided this issue altogether if you sliced only the NdOverlay not the Curves themselves, i.e. this ``traces[3.1:]`` instead of this ``traces[3.1:,:]``.

**Comment by jlstevens** [comment] 2015-09-17 13:24
I see what you mean now and I do think it is fairly confusing behavior. As a result, I think copying the ids across might be a good idea though I'll need time to think through all the possible consequences of this...

**Comment by philippjfr** [comment] 2017-06-23 02:02
This now works as you expected:

```python
traces = hv.NdOverlay({col:hv.Curve(np.random.rand(10,2))(style={'color':col}) 
                       for i, col in enumerate(['red', 'green', 'blue']) }, kdims=['Contrast'])
traces[['red', 'green'], :]
```

Closing.

**Closed by philippjfr** 2017-06-23 02:02 UTC
