### ISSUE TITLE
Allow sampling of RGB and Image outside of bounds?

### ISSUE THREAD

**Issue by jbednar** [ioam/holoviews#1956] opened 2017-10-03 02:31 UTC
Right now, if we call sample on an RGB or Image object, it works fine inside the bound, but raises an exception outside:

```
x,y = np.mgrid[-50:51, -50:51] * 0.1

r = 0.5*np.sin(np.pi  +3*x**2+y**2)+0.5
g = 0.5*np.sin(x**2+2*y**2)+0.5
b = 0.5*np.sin(np.pi/2+x**2+y**2)+0.5

hv.RGB(np.dstack([r,g,b])).sample(x=10,y=10)
```

```
IndexError: index 1060 is out of bounds for axis 1 with size 101
```

This is clearly the right default behavior, because outside the bounds the value is not defined.  However, in certain settings, it would be nice to be able to explicitly define what the value outside of the image area is.  For instance,  when the image is embedded in a larger plot and we have hover or click enabling a connection to a different plot, we probably want to be able to sample anywhere in the space and return a reasonable value, not raise an exception.  

So, maybe Image and RGB could accept a value that determines the result of sample() outside the bounds?  For consistency with the visual representation that might also need to be the value actually shown in a plot when looking outside the bounds, which can be useful in its own right. E.g. one could define the background color for an image that way, and have it surrounded by that color...

**Comment by philippjfr** [comment] 2017-10-04 13:03
For now I've added an explicit ``IndexError`` when sampling out-of-bounds that shows the sampled coordinates and the actual bounds rather than letting it error on array indexing (https://github.com/ioam/holoviews/pull/1961).

**Comment by philippjfr** [comment] 2017-12-21 13:31
>So, maybe Image and RGB could accept a value that determines the result of sample() outside the bounds?

I don't see any possible way to achieve this as I do not want to shove random metadata onto elements, so I think I want to close this as out-of-scope. The current behavior is correct imo and anything else would be too much special handling imo.

**Comment by jlstevens** [comment] 2017-12-21 14:05
I think I agree with @philippjfr here.

**Comment by philippjfr** [comment] 2017-12-21 14:08
Okay that's 2:1, sorry @jbednar, closing as out-of-scope.

**Closed by philippjfr** 2017-12-21 14:08 UTC
Labels: feature, wontfix

**Comment by jbednar** [comment] 2017-12-22 21:50
> I don't see any possible way to achieve this as I do not want to shove random metadata onto elements, so I think I want to close this as out-of-scope. The current behavior is correct and anything else would be too much special handling imo.

I won't try to argue you out of it, but I don't think this information would qualify as "metadata". The main intended usage of an Image is as a discrete approximation of a continuous function of two variables, and the proposed behavior merely allows specification of such a function with an infinite extent.  E.g. imagine having a 2D Gaussian with an offset in the z direction, such that the value of the function approaches 1.0 near the borders of the image, and is truly 1.0 for all distant locations outside the boundary of the array.  The proposed behavior simply allows a user to specify that the value is not zero outside the boundary, but that it is 1.0, which is the correct declaration for the *data* in this case, not the metadata.  It's not simply a hint or some arbitrary bonus information, in such a case it's a concise specification for the entire function that the element represents.

A similar capability would be valid for a Curve or other finite approximations of functions of potentially infinite extent, defining what values should be used outside the bounds of the data points provided when sampled or rendered onscreen.  Again, I'm not arguing that we have to provide this functionality, just that it's very well defined, interpretable, and completely in the scope of *data*, not metadata.

In terms of implementation, if we're already raising an exception in such cases, it seems trivial to return an explicitly declared value for out-of-bounds areas instead.  But there are probably other tricky aspects.

**Comment by philippjfr** [comment] 2017-12-27 22:01
The problem is with finding a general way to store this data. It clearly can't be declared as part of a NumPy array and only through special conventions could it be stored on ``.data`` for other formats like xarray and dictionaries. That leaves a special parameter on Dimension or directly on the Element, which I'm fairly strongly against since I agree that it's not technically metadata and should therefore be stored on the ``.data``.

**Comment by jbednar** [comment] 2018-01-04 16:05
If you want to ensure that everything to do with the data is in ``.data``, ``.data`` could be a tuple of this value plus the array data, but that just seems like it would add work for us without a clear benefit.  I guess I don't really see why it's important for every last bit of the .data values to be in .data, as long as any special data values like these are accessible *somewhere* on the Element.  Having to track those down seems better than not being able to express a reasonable concept like this at all...
