### ISSUE TITLE
Colorbars don't display correctly as SVG

### ISSUE THREAD

**Issue by vascotenner** [ioam/holoviews#111] opened 2015-05-25 12:00 UTC
Is it possible to export directly to pdf? Matplotlib can do this.

**Comment by jlstevens** [comment] 2015-05-25 12:11
We haven't been supporting pdf as it doesn't display inline in the browser, i.e in our HTML tags. Generally, we would recommend SVG over PDF export for a couple of reasons:

* Open XML standard (as opposed to a binary file)
* Vector format supported natively in browsers.
* Excellent tools for editing SVG (namely [Inkscape](https://inkscape.org/en/))
* There are packages adding SVG support to LaTex (e.g [the svg package](https://www.ctan.org/tex-archive/graphics/svg?lang=en))
* Easily converted to PDF later.

For these reasons, I doubt we will support PDF output in general unless all browsers start supporting it properly. That said, we could consider PDF support using the explicit, pure-python interface for saving output, [described here](https://github.com/ioam/holoviews/wiki/HoloViews-without-IPython). In particular I *think* we could support something like:

```python
renderer = Store.renderer.instance(fig='pdf', holomap='gif')
renderer.save(obj, 'example')
```

This would only be available through this explicit interface though...

**Comment by vascotenner** [comment] 2015-05-25 12:20
Now I discovered my real question: Colorbars are exported uggly to svg, the steps are to big. The png backend is fine. Exporting from matplotlib to pdf also results in nice colorbars.

**Comment by philippjfr** [comment] 2015-05-25 13:11
So I came across [this Stackoverflow post](http://stackoverflow.com/questions/15003353/why-does-my-colorbar-have-lines-in-it), which explains what's  going on here. matplotlib doesn't draws colorbars as a bunch of individual segments instead one image with smooth shading. In some SVG renderers this seems to cause issues. I can implement the fix they advise but if the colorbar has any alpha in it this will cause other issues, so I'll at least make it conditional on the alpha style option being disabled.

**Comment by philippjfr** [comment] 2015-05-25 13:30
I've now implemented the fix suggested in the Stackoverflow post, so let me know if that fixes it for you. This issue is related to https://github.com/matplotlib/matplotlib/issues/1188 in matplotlib. So hopefully we can remove our workaround if anyone ever gets around to fixing that.

**Comment by philippjfr** [comment] 2015-05-25 14:29
Should be fixed now so I'll close the issue. If you find any problems please reopen.

**Closed by philippjfr** 2015-05-25 14:29 UTC
Labels: feature

**Comment by jbednar** [comment] 2015-05-26 00:52
For people who care about reproducible modelling, not supporting easy export to PDF is problematic, since PDF is what can be easily imported directly into document preparation systems.  E.g. in LaTeX, the svg package simply uses Inkscape to convert SVG to PDF on the fly, which seems inefficient and likely to cause problems (e.g. just yesterday I had to give up getting a good PDF out of an Inkscape SVG file I was working with; I had to use PNG!).  It's certainly true that SVG has big advantages, but I don't think it's true that PDF would be bad to support.  That said, if it's *difficult* to support, that's a different matter.  If it's easy to support, I think it would help people have a clean reproducible workflow without requiring Inkscape trickery behind the scenes.

**Comment by jlstevens** [comment] 2015-05-26 09:48
I think PDF support in the notebook itself (i.e for display) is out of the questions unless browsers support it better. Honestly, I can add even more reasons I think SVG is superior in all cases:

* XML can be easily parsed and manipulated by Python code in the standard library. For instance in the GCAL paper, my whole system of embedding figures into a larger figure worked because I could write code to automate such steps. This is much, much harder with PDF (even using report lab).

* You don't know what format journals accept and SVG is an excellent intermediate format. For instance, Journal of Neuroscience only accept PDFS in the *initial* submission and then only EPS or TIFF after that. Converting from SVG to either of those is something I trust much more than PDF to anything.

* Related to the point above, many journals aren't going to let you typeset anything with LaTex anyway - they will ask for separate figure files and not a PDF generate by LaTex.

* SVG is going to be better if you want to present and communicate your work on a webpage, whether you do so with IPython Notebook or not.

* I have a lot of experience with Inkscape exporting to PDF and in *general* it is excellent. The one issue I have noticed is that some versions of Inkscape apply unwanted interpolation to raster images. That said, if you *ever* let someone else rescale an image for you (including journals when typesetting!) you run this risk. The safest thing in *all* cases is to output the raster at a high resolution because scaling down rarely causes the same bad artifacts as scaling up.

* Different renderers will be used for SVG and PDF which means the output might not always be consistent due to issues in the renderer implementations. I would much rather treat SVG as the 'gold-standard' for our vector output than try to support PDF and have to keep trying to iron out inconsistencies between the two (if this is even possible!). 

So I agree that for some people working with LaTeX and publishing on arXiv for instance might benefit from PDF output. There are possible conversion issues as you mentioned and I can imagine supporting PDF in the explicit save interface on ``MPLRenderer``. Even if we can support it like this, I just don't want to encourage PDF output for the many reasons listed above!

**Comment by jbednar** [comment] 2015-05-27 02:30
Those are all good reasons for using SVG, and for recommending and endorsing SVG as our suggested best practice.  But the thing about a reproducible pipeline is that all the bits need to connect up for any of it to work, and SVG may or may not connect up to the other parts of the pipeline for other users.  Not everyone on the planet has even heard of SVG, but everyone knows what PDF is, and I've not found many journals who don't accept it, while I don't recall ever seeing one who would accept SVG.

In case it's of interest, the figure I had problems with yesterday was part of one of yours:

![pinw](https://cloud.githubusercontent.com/assets/1695496/7827444/f9f529e2-03ec-11e5-8c22-04efe1a7a985.png)

No idea why Inkscape won't save it as PDF, but I ended up exporting as a huge PNG instead.

**Comment by vascotenner** [comment] 2015-05-27 09:56
For me a major drawback is the difference in color bar drawing. This is pixeled information, mostly next to a imshow object, which is pixeled.

When I make a presentation in inkscape, and import a svg-file with a colorbar, this adds 100kb of xml to my svg file, making inkscape slow (especially after importing multiple plot). When first exporting to PDF and then importing to inkscape, does not have this drawback, while all the *lines* are still lines, while the *pixeled* information is still pixeled. Export to PDF, or better colorbar support would help. Do I have to file an issue for matplotlib to imporve the svg output of colorbars?

**Comment by philippjfr** [comment] 2015-05-27 11:32
>Export to PDF, or better colorbar support would help. Do I have to file an issue for matplotlib to imporve the svg output of colorbars?

As I said there's an existing issue https://github.com/matplotlib/matplotlib/issues/1188 for this in matplotlib but it's almost three years old and I doubt anyone will reimplement colorbar as a smooth gradient rather than a bunch of individual segments at this point. If you look at the recent discussion, they've been suggesting implementing the fix I made manually in our code to avoid the white lines between individual segments but no one has proposed actually re-implementing the whole thing.

Overall I'd be happy if our ``MPLPlotRenderer`` could export to PDF, I'm also not sure if we should support it but I did just get inline rendering of pdf working but it'll be pretty browser dependent.

**Comment by jlstevens** [comment] 2015-05-27 11:43
@jbednar Please don't mangle my figures like this! It took me literally 30 seconds to do it right:

![image](https://cloud.githubusercontent.com/assets/890576/7834965/fe579e40-046c-11e5-9f5c-922368a1611c.png)

I put a lot of effort generating proper vector graphics for my paper and I *never* want to see such horrible output *ever*. If you need PDFs, it takes absolutely *no* time to get it right:

```python
Inkscape -> Export -> PDF
```

Whatever tools/versions/process you are using, something has gone horribly wrong and the output is *completely* unacceptable. Do *not* accept such bad output and please don't generate huge PNGs either! That screenshot is utterly hideous and revolting!

If you want to know where I got the figure, I just imported the paper at the appropriate page into Inkscape. Again, a 5 second process.

@vascotenner I think Philipp has had a look at color bars and has found some approaches that seem to work (not sure if it is committed yet though). I think filing an issue with matplotlib would be a very useful thing to do nonetheless! Thanks!

I don't mind allowing files to be saved PDF as long as we make it crystal clear that:

1. Any rendering or backend problems regarding PDF export need to be directed to matplotlib and not us! 
2. Our gold-standard for vector output remains SVG.

**Comment by jlstevens** [comment] 2015-05-27 13:20
Philipp and I have looked into getting PDF working properly in general, even for display in the browser. We've come up with a solution that is reasonable for modern browsers that integrates properly without having to make PDF a special case.

It is far from a perfect solution because browsers don't work that well with PDFs that well and we are making use of iframes! For this reason, we are adding a warning so that users know this is very experimental, may not work for them and may change in future.

**Comment by vascotenner** [comment] 2015-05-27 13:23
I hope that solving this issue also makes the PDF export not necessary to obtain good colorbars:
https://github.com/matplotlib/matplotlib/issues/4480

**Comment by jlstevens** [comment] 2015-05-27 13:24
@vascotenner Thanks for posting to matplotlib! Hopefully, they will fix it this time around. :-)

**Comment by jbednar** [comment] 2015-05-27 16:04
> If you need PDFs, it takes absolutely no time to get it right:
> Inkscape -> Export -> PDF

Actually, it's:

```
Inkscape->File->Save As->PDF
```

But in any case, that's precisely how I obtained that horrible and unusable output!  It usually does work, but I've had to do things like this at least 30 times more than you, and so I've encountered at least 30 times more problems.

In this particular case I started with the .eps file in your paper's source code, since the PDF was generated from the EPS, and it's nearly always better to start from the source figure, not the final generated PDF.  I'm glad that it works when starting from the final PDF, but that doesn't seem relevant to the point, which is that Inkscape isn't always able to generate decent PDF (it certainly didn't in the above example), and so it is *not* a no-brainer simply to assume that because you have some file readable by Inkscape, you can just assume you'll be able to have decent conversion to PDF.

**Comment by jlstevens** [comment] 2015-05-27 16:19
Sounds to me like the problem was EPS which doesn't surprise me at all. I only ever touched EPS because I was forced to by Journal of Neuroscience  and yes, exporting those files was a truly miserable process! EPS is an outdated format and doesn't support even simple things (such as alpha channels) soI would never use by choice.

As HoloViews outputs SVG and not EPS, I don't think this would be a problem and I will still work exclusively with SVG until a PDF is requested (and export from Inkscape). Anyhow, since commit 1e8a59b we now have experimental support for PDF so I the whole point is probably moot.

**Comment by kawairine** [comment] 2019-05-15 08:32
Hi,

I am not sure if my question is related to this thread, but I have been trying out to export to pdf format ( which works) but it has lost the alpha setting of my plot

`renderer = hv.plotting.mpl.MPLRenderer.instance(fig='pdf')
renderer.save(plt, "hist")`

And I also tried to use matplotlib backend but that didnt work as well.

`import holoviews.plotting.mpl
hv.Store.renderers['matplotlib'].save(plt, "hist_m", 'pdf')
`
Any help will be greatly appreciated. Thank you.

(Sorry if I have posted my question in a wrong thread, or formatted it wrongly)

**Comment by philippjfr** [comment] 2019-05-15 08:46
These days you can use the ``save`` function:

```python
hv.save(plt, 'hist.pdf', backend='matplotlib')
```

That said the disappearing alpha could be a limitation of matplotlib itself OR the fact that you specified the option for another backend (e.g. bokeh). When switching backends your options don't persist, so you have to apply them with ``.opts(..., backend='matplotlib')`` or switch to the matplotlib backend before you set the options.

**Comment by kawairine** [comment] 2019-05-15 12:47
> These days you can use the `save` function:
> 
> ```python
> hv.save(plt, 'hist.pdf', backend='matplotlib')
> ```
> 
> That said the disappearing alpha could be a limitation of matplotlib itself OR the fact that you specified the option for another backend (e.g. bokeh). When switching backends your options don't persist, so you have to apply them with `.opts(..., backend='matplotlib')` or switch to the matplotlib backend before you set the options.



Hi,

Thank you for your prompt response.
I have tried your suggestion, but it still doesn't work. Is it because I had plotted my graphs in bokeh?
