### ISSUE TITLE
Zooming in on datashaded curve with datetime axis removes image

### ISSUE THREAD

**Issue by gfluck** [ioam/holoviews#2484] opened 2018-03-27 08:57 UTC
This is probably related to #2299 

If you try to zoom in on a datashaded image with a datetime axis the image starts to disappear (from left to right). The lower the frequency of your time axis the faster it happens.

Taking the time_series function from the large data user guide:
```
def time_series(T = 1, N = 100, mu = 0.1, sigma = 0.1, S0 = 20):  
    """Parameterized noisy time series"""
    dt = float(T)/N
    t = np.linspace(0, T, N)
    W = np.random.standard_normal(size = N) 
    W = np.cumsum(W)*np.sqrt(dt) # standard brownian motion
    X = (mu-0.5*sigma**2)*t + sigma*W 
    S = S0*np.exp(X) # geometric brownian motion
    return S
```
and creating a new curve plot:
```
%%opts RGB [width=800]
dates = pd.date_range(start='1970-01-01', end='1970-01-01T01', freq='1ms')
series = time_series(N=len(dates), sigma = 1)
curve = hv.Curve((dates, series))
datashade(curve, cmap='blue')
``` 
you will see that the image disappears as soon as you try to zoom in.

If you take a lower frequency and larger time span you will be able to see the curve disappear the more you zoom in:
```
%%opts RGB [width=800]
dates = pd.date_range(start='1970-01-01', end='1970-01-02', freq='1s')
series = time_series(N=len(dates), sigma = 1)
curve = hv.Curve((dates, series))
datashade(curve, cmap='blue')
```

Note also that the `reset` button does not properly reset the plot anymore. Converting the time series to timestamps (with `np.array(dates, dtype=float)`) solves the problem but you loose the nicely formatted axis.

**Comment by philippjfr** [comment] 2018-03-27 11:02
I think this bug has been fixed on master but it's worth checking before we close the issue.

**Comment by philippjfr** [comment] 2018-03-30 14:46
Cannot reproduce on master, closing.

**Closed by philippjfr** 2018-03-30 14:46 UTC
