### ISSUE TITLE
Export archive

### ISSUE THREAD

**Issue by vascotenner** [ioam/holoviews#280] opened 2015-10-08 07:55 UTC
I cannot get export an archive. No files are exported:
```python
import holoviews as hv
%load_ext holoviews.ipython
import numpy as np
from holoviews.ipython import display_hooks
display_hooks.ABBREVIATE_TRACEBACKS=False
hv.archive.auto()
```
```Automatic capture is now enabled. [2015-10-08 09:47:07]```
```python
%%opts ErrorBars [yrotation=15, xrotation=45]
hv.ErrorBars((0,1,.5,3))
```
```
WARNING:root:ErrorBars01244: Could not pickle custom style information.
```
+image
```python
hv.archive.export()
```
```
Export name: '{notebook}'
Directory    '/media/data2/tenner/data/ipython-notebooks'

If no output appears, please check holoviews.archive.last_export_status()
```
```python
hv.archive.last_export_status()
```
```
Status of the last call to holoviews.archive.export is unknown.
(Re-execute this method once kernel status is idle.)
```
```python
hv.archive.contents()
```
```
ErrorBars.svg : image/svg+xml
ErrorBars.hvz : application/zip
```

**Comment by jlstevens** [comment] 2015-10-08 11:53
Thanks for reporting this! I'll have to look into it...

**Comment by philippjfr** [comment] 2015-10-08 14:25
Yes, thanks I meant to file an issue about problems with archiving myself but forgot about it. Here's a related issue: https://github.com/ioam/topographica/issues/631

**Comment by vascotenner** [comment] 2015-11-23 11:51
The export is not totally fixed in #284. When I run the Exporting tutorial, it does not export in cell 13. Also ```hv.archive.last_export_status()``` does not give usefull output. However, when I add the lines:
```
holoviews = hv
holoviews.archive.export()
```

It exports the data, but in the directory {notebook}, instead of Exporting.

```hv.archive.last_export_status()``` now gives the right output.

**Comment by philippjfr** [comment] 2015-11-23 14:25
Thanks, for looking into this. We're trying to get a release candidate out by the end of this week, so hopefully @jlstevens will get to this issue soon.

**Comment by jlstevens** [comment] 2015-11-30 10:55
I've finally had a chance to have a look...

I suspect the issue is that IPython/Jupyter have changed their JavaScript API needed for the fancier parts of the export (trying to get the notebook name and capturing the active notebook). If in the tutorial, you set the options like this instead:

```python
hv.archive.auto(skip_notebook_export=True, export_name='Exporting')
```

Then it works again. I feel we ought to document this in the tutorial - I don't like the Javascript code we are using and I don't trust it not to break between Jupyter releases.

Anyway, I've just found the issue - we used to do ``import holoviews`` but now we do ``import holoviews as hv``. This is up to the user but breaks the Python/Javascript link as the Javascript tries to set data on ``holoviews.archive`` which doesn't exist if you imported as ``hv`` (this is extremely fragile but I haven't found a more robust way!). This also works:

```python
hv.archive.auto(namespace='hv.archive')
```

We could:

1. Change the namespace default to ``hv.archive`` 
2. Document this issue in the tutorial 
3. Somehow try to use both common forms (i.e try testing ``holoviews`` or ``hv``). Or maybe you can do something fancy as I can use IPython to see what is defined in the notebook namespace - I could see if something called 'hv' or 'holoviews' is defined as assume it is actually holoviews!

I would recommend a combination of 1. and 2. - set the default to ``hv`` and state in the tutorial that if you import holoviews some other way, it won't work. What are your thoughts on this?

**Comment by philippjfr** [comment] 2015-11-30 12:25
I'd just consistently move to using ``hv`` as that is now our recommendation and document that in the Exporting Tutorial.

**Comment by jlstevens** [comment] 2015-11-30 14:25
Ok, the change to the default is implemented in 8037a29. The tutorial is updated in 2ca621e.

I am happy to hear any suggestions on how to make the tutorial clearer. I'll close the issue now, but if @vascotenner has any comments on further improvements, I'll reopen the issue and we can discuss them.

**Closed by jlstevens** 2015-11-30 14:25 UTC

**Comment by jbednar** [comment] 2015-11-30 14:43
This sounds very fragile.  Can the current module name be provided to Javascript from Python initially?  Otherwise, can Javascript at least try both holoviews and hv?

**Comment by vascotenner** [comment] 2015-11-30 14:49
Or maybe always print a "warning", that the hv modules should be imported or renamed to hv or holoviews.

The main problem here, is that the ipython kernel does not know it is run from a notebook or a shell or something else.

**Comment by jlstevens** [comment] 2015-11-30 15:21
I have this quick hack that might do the job:

```
import sys
def get_namespace():
    if 'holoviews' not in sys.modules:
        raise ImportError('HoloViews does not seem to be imported')
    matches = [k for k,v in globals().items()
       if not k.startswith('_') and v == sys.modules['holoviews']]
    return matches[0] if len(matches) > 0 else None
```

This should be run when ``auto`` is called and may fix the problem. If not, I agree with @vascotenner that a warning would help.

**Comment by philippjfr** [comment] 2015-11-30 15:34
Can't we simply add a ``import holoviews`` when calling the Python kernel from JS?

**Comment by jlstevens** [comment] 2015-11-30 15:42
Ok, I seem to have it working nicely in 5bab92b - I can find the name the user has available to access holoviews and remove the fragile namespace parameter entirely.

Now I need to revert my change to the tutorial....

**Comment by jbednar** [comment] 2015-11-30 20:30
Looks much less fragile, thanks.
