### ISSUE TITLE
Title is only partially visible on animated gif output

### ISSUE THREAD

**Issue by jordansamuels** [ioam/holoviews#1614] opened 2017-06-26 18:41 UTC
It appears that the title text at top is partially clipped for animated gif output.  E.g.  http://build.holoviews.org/Tutorials/Showcase.html and http://holoviews.org/Tutorials/Showcase.html both show clipped output on the first demo of `%output holomap='gif'`:

<img width="997" alt="screen shot 2017-06-26 at 2 39 07 pm" src="https://user-images.githubusercontent.com/610909/27554731-5d38e5dc-5a7d-11e7-90ee-974991a1ac15.png">

If it helps, I'm on OSX 10.11.6 and Chrome Version 58.0.3029.110 (64-bit).

**Comment by philippjfr** [comment] 2017-06-26 18:52
Related to https://github.com/ioam/holoviews/issues/287. This is related to how bokeh handles bounding boxes on AnimationWriters.

**Comment by jlstevens** [comment] 2017-06-26 19:03
@jordansamuels Thanks for pointing this out although I should note we are about to deprecate Showcase from the docs. One reason being that the gif support requires imagemagick which we cannot assume will always be installed.

**Comment by jordansamuels** [comment] 2017-06-26 23:08
@jlstevens Understood.  My $.02 is that the gif support is really sweet, and in my opinion it's not much of an incremental burden to install it.   Will the gif support stuff move to another area of the docs?

**Comment by jlstevens** [comment] 2017-06-26 23:18
> My $.02 is that the gif support is really sweet ...

I like it too but I really wish I could be sure it works reliably for everyone. I don't want people trying early examples and having things break because ImageMagick isn't installed!

@philippjfr

> Will the gif support stuff move to another area of the docs?

I suppose this belongs in the matplotlib specific user guide? Also, I think a gif example in demos would actually be a good thing to have...

**Comment by philippjfr** [comment] 2017-06-26 23:21
>I suppose this belongs in the matplotlib specific user guide? Also, I think a gif example in demos would actually be a good thing to have...

I think that's a good idea, we also want a "Plotting with matplotlib" user guide which currently don't exist, where gif support and other output (svg/pdf) can be described. Would you want to work on that @jordansamuels? Would be hugely appreciated.

**Comment by jlstevens** [comment] 2017-06-26 23:24
That would be great! My main advice for the gifs would be to come up with some different examples from the ones used in Showcase: we have gotten sick of those sinusoidal rings over the years. ;-p

**Comment by jordansamuels** [comment] 2017-06-27 02:18
@philippjfr @jlstevens sure, I'll give it a shot in the next few days.  And yes, I'll try to come up with another example topic.

**Comment by philippjfr** [comment] 2017-12-08 17:28
Since this is mostly a duplicate of #287 I've repurposed it to be about documenting gif support, which is related to https://github.com/ioam/holoviews/issues/2095.

**Comment by philippjfr** [comment] 2018-05-25 17:56
There is now documentation about gif support in the Plotting with matplotlib user guide.

**Closed by philippjfr** 2018-05-25 17:56 UTC
Labels: bug, mpl
